// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_160_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_address0,
        x_ce0,
        x_q0,
        x_2_address0,
        x_2_ce0,
        x_2_q0,
        x_4_address0,
        x_4_ce0,
        x_4_q0,
        x_6_address0,
        x_6_ce0,
        x_6_q0,
        x_8_address0,
        x_8_ce0,
        x_8_q0,
        x_10_address0,
        x_10_ce0,
        x_10_q0,
        x_12_address0,
        x_12_ce0,
        x_12_q0,
        x_14_address0,
        x_14_ce0,
        x_14_q0,
        x_16_address0,
        x_16_ce0,
        x_16_q0,
        x_18_address0,
        x_18_ce0,
        x_18_q0,
        x_20_address0,
        x_20_ce0,
        x_20_q0,
        x_22_address0,
        x_22_ce0,
        x_22_q0,
        x_24_address0,
        x_24_ce0,
        x_24_q0,
        x_26_address0,
        x_26_ce0,
        x_26_q0,
        x_28_address0,
        x_28_ce0,
        x_28_q0,
        x_30_address0,
        x_30_ce0,
        x_30_q0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_address0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_ce0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_we0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_d0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_address0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_ce0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_we0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_d0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_address0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_ce0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_we0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_d0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_address0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_ce0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_we0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_d0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_address0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_ce0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_we0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_d0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_address0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_ce0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_we0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_d0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_address0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_ce0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_we0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_d0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_address0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_ce0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_we0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_d0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_address0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_ce0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_we0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_d0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_address0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_ce0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_we0,
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_d0,
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_10_address0,
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_10_ce0,
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_10_we0,
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_10_d0,
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_11_address0,
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_11_ce0,
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_11_we0,
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_11_d0,
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_12_address0,
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_12_ce0,
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_12_we0,
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_12_d0,
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_13_address0,
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_13_ce0,
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_13_we0,
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_13_d0,
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_14_address0,
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_14_ce0,
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_14_we0,
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_14_d0,
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_15_address0,
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_15_ce0,
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_15_we0,
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_15_d0,
        grp_fu_1416_p_din0,
        grp_fu_1416_p_din1,
        grp_fu_1416_p_opcode,
        grp_fu_1416_p_dout0,
        grp_fu_1416_p_ce,
        grp_fu_1201_p_din0,
        grp_fu_1201_p_din1,
        grp_fu_1201_p_dout0,
        grp_fu_1201_p_ce,
        grp_fu_1420_p_din0,
        grp_fu_1420_p_din1,
        grp_fu_1420_p_dout0,
        grp_fu_1420_p_ce,
        grp_fu_1424_p_din0,
        grp_fu_1424_p_din1,
        grp_fu_1424_p_dout0,
        grp_fu_1424_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] x_address0;
output   x_ce0;
input  [31:0] x_q0;
output  [10:0] x_2_address0;
output   x_2_ce0;
input  [31:0] x_2_q0;
output  [10:0] x_4_address0;
output   x_4_ce0;
input  [31:0] x_4_q0;
output  [10:0] x_6_address0;
output   x_6_ce0;
input  [31:0] x_6_q0;
output  [10:0] x_8_address0;
output   x_8_ce0;
input  [31:0] x_8_q0;
output  [10:0] x_10_address0;
output   x_10_ce0;
input  [31:0] x_10_q0;
output  [10:0] x_12_address0;
output   x_12_ce0;
input  [31:0] x_12_q0;
output  [10:0] x_14_address0;
output   x_14_ce0;
input  [31:0] x_14_q0;
output  [10:0] x_16_address0;
output   x_16_ce0;
input  [31:0] x_16_q0;
output  [10:0] x_18_address0;
output   x_18_ce0;
input  [31:0] x_18_q0;
output  [10:0] x_20_address0;
output   x_20_ce0;
input  [31:0] x_20_q0;
output  [10:0] x_22_address0;
output   x_22_ce0;
input  [31:0] x_22_q0;
output  [10:0] x_24_address0;
output   x_24_ce0;
input  [31:0] x_24_q0;
output  [10:0] x_26_address0;
output   x_26_ce0;
input  [31:0] x_26_q0;
output  [10:0] x_28_address0;
output   x_28_ce0;
input  [31:0] x_28_q0;
output  [10:0] x_30_address0;
output   x_30_ce0;
input  [31:0] x_30_q0;
output  [10:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_address0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_ce0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_we0;
output  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_d0;
output  [10:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_address0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_ce0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_we0;
output  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_d0;
output  [10:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_address0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_ce0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_we0;
output  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_d0;
output  [10:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_address0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_ce0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_we0;
output  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_d0;
output  [10:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_address0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_ce0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_we0;
output  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_d0;
output  [10:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_address0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_ce0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_we0;
output  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_d0;
output  [10:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_address0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_ce0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_we0;
output  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_d0;
output  [10:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_address0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_ce0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_we0;
output  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_d0;
output  [10:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_address0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_ce0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_we0;
output  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_d0;
output  [10:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_address0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_ce0;
output   activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_we0;
output  [15:0] activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_d0;
output  [10:0] p_ZZ22activation_acceleratorPtS_S_iiE4buf2_10_address0;
output   p_ZZ22activation_acceleratorPtS_S_iiE4buf2_10_ce0;
output   p_ZZ22activation_acceleratorPtS_S_iiE4buf2_10_we0;
output  [15:0] p_ZZ22activation_acceleratorPtS_S_iiE4buf2_10_d0;
output  [10:0] p_ZZ22activation_acceleratorPtS_S_iiE4buf2_11_address0;
output   p_ZZ22activation_acceleratorPtS_S_iiE4buf2_11_ce0;
output   p_ZZ22activation_acceleratorPtS_S_iiE4buf2_11_we0;
output  [15:0] p_ZZ22activation_acceleratorPtS_S_iiE4buf2_11_d0;
output  [10:0] p_ZZ22activation_acceleratorPtS_S_iiE4buf2_12_address0;
output   p_ZZ22activation_acceleratorPtS_S_iiE4buf2_12_ce0;
output   p_ZZ22activation_acceleratorPtS_S_iiE4buf2_12_we0;
output  [15:0] p_ZZ22activation_acceleratorPtS_S_iiE4buf2_12_d0;
output  [10:0] p_ZZ22activation_acceleratorPtS_S_iiE4buf2_13_address0;
output   p_ZZ22activation_acceleratorPtS_S_iiE4buf2_13_ce0;
output   p_ZZ22activation_acceleratorPtS_S_iiE4buf2_13_we0;
output  [15:0] p_ZZ22activation_acceleratorPtS_S_iiE4buf2_13_d0;
output  [10:0] p_ZZ22activation_acceleratorPtS_S_iiE4buf2_14_address0;
output   p_ZZ22activation_acceleratorPtS_S_iiE4buf2_14_ce0;
output   p_ZZ22activation_acceleratorPtS_S_iiE4buf2_14_we0;
output  [15:0] p_ZZ22activation_acceleratorPtS_S_iiE4buf2_14_d0;
output  [10:0] p_ZZ22activation_acceleratorPtS_S_iiE4buf2_15_address0;
output   p_ZZ22activation_acceleratorPtS_S_iiE4buf2_15_ce0;
output   p_ZZ22activation_acceleratorPtS_S_iiE4buf2_15_we0;
output  [15:0] p_ZZ22activation_acceleratorPtS_S_iiE4buf2_15_d0;
output  [31:0] grp_fu_1416_p_din0;
output  [31:0] grp_fu_1416_p_din1;
output  [0:0] grp_fu_1416_p_opcode;
input  [31:0] grp_fu_1416_p_dout0;
output   grp_fu_1416_p_ce;
output  [31:0] grp_fu_1201_p_din0;
output  [31:0] grp_fu_1201_p_din1;
input  [31:0] grp_fu_1201_p_dout0;
output   grp_fu_1201_p_ce;
output  [31:0] grp_fu_1420_p_din0;
output  [31:0] grp_fu_1420_p_din1;
input  [31:0] grp_fu_1420_p_dout0;
output   grp_fu_1420_p_ce;
output  [31:0] grp_fu_1424_p_din0;
output  [31:0] grp_fu_1424_p_din1;
input  [31:0] grp_fu_1424_p_dout0;
output   grp_fu_1424_p_ce;

reg ap_idle;
reg x_ce0;
reg x_2_ce0;
reg x_4_ce0;
reg x_6_ce0;
reg x_8_ce0;
reg x_10_ce0;
reg x_12_ce0;
reg x_14_ce0;
reg x_16_ce0;
reg x_18_ce0;
reg x_20_ce0;
reg x_22_ce0;
reg x_24_ce0;
reg x_26_ce0;
reg x_28_ce0;
reg x_30_ce0;
reg activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_ce0;
reg activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_we0;
reg activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_ce0;
reg activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_we0;
reg activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_ce0;
reg activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_we0;
reg activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_ce0;
reg activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_we0;
reg activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_ce0;
reg activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_we0;
reg activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_ce0;
reg activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_we0;
reg activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_ce0;
reg activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_we0;
reg activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_ce0;
reg activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_we0;
reg activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_ce0;
reg activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_we0;
reg activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_ce0;
reg activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_we0;
reg p_ZZ22activation_acceleratorPtS_S_iiE4buf2_10_ce0;
reg p_ZZ22activation_acceleratorPtS_S_iiE4buf2_10_we0;
reg p_ZZ22activation_acceleratorPtS_S_iiE4buf2_11_ce0;
reg p_ZZ22activation_acceleratorPtS_S_iiE4buf2_11_we0;
reg p_ZZ22activation_acceleratorPtS_S_iiE4buf2_12_ce0;
reg p_ZZ22activation_acceleratorPtS_S_iiE4buf2_12_we0;
reg p_ZZ22activation_acceleratorPtS_S_iiE4buf2_13_ce0;
reg p_ZZ22activation_acceleratorPtS_S_iiE4buf2_13_we0;
reg p_ZZ22activation_acceleratorPtS_S_iiE4buf2_14_ce0;
reg p_ZZ22activation_acceleratorPtS_S_iiE4buf2_14_we0;
reg p_ZZ22activation_acceleratorPtS_S_iiE4buf2_15_ce0;
reg p_ZZ22activation_acceleratorPtS_S_iiE4buf2_15_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_state19_pp0_stage0_iter18;
wire    ap_block_state20_pp0_stage0_iter19;
wire    ap_block_state21_pp0_stage0_iter20;
wire    ap_block_state22_pp0_stage0_iter21;
wire    ap_block_state23_pp0_stage0_iter22;
wire    ap_block_state24_pp0_stage0_iter23;
wire    ap_block_state25_pp0_stage0_iter24;
wire    ap_block_state26_pp0_stage0_iter25;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln160_fu_587_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln161_fu_609_p1;
reg   [63:0] zext_ln161_reg_715;
reg   [63:0] zext_ln161_reg_715_pp0_iter1_reg;
reg   [63:0] zext_ln161_reg_715_pp0_iter2_reg;
reg   [63:0] zext_ln161_reg_715_pp0_iter3_reg;
reg   [63:0] zext_ln161_reg_715_pp0_iter4_reg;
reg   [63:0] zext_ln161_reg_715_pp0_iter5_reg;
reg   [63:0] zext_ln161_reg_715_pp0_iter6_reg;
reg   [63:0] zext_ln161_reg_715_pp0_iter7_reg;
reg   [63:0] zext_ln161_reg_715_pp0_iter8_reg;
reg   [63:0] zext_ln161_reg_715_pp0_iter9_reg;
reg   [63:0] zext_ln161_reg_715_pp0_iter10_reg;
reg   [63:0] zext_ln161_reg_715_pp0_iter11_reg;
reg   [63:0] zext_ln161_reg_715_pp0_iter12_reg;
reg   [63:0] zext_ln161_reg_715_pp0_iter13_reg;
reg   [63:0] zext_ln161_reg_715_pp0_iter14_reg;
reg   [63:0] zext_ln161_reg_715_pp0_iter15_reg;
reg   [63:0] zext_ln161_reg_715_pp0_iter16_reg;
reg   [63:0] zext_ln161_reg_715_pp0_iter17_reg;
reg   [63:0] zext_ln161_reg_715_pp0_iter18_reg;
reg   [63:0] zext_ln161_reg_715_pp0_iter19_reg;
reg   [63:0] zext_ln161_reg_715_pp0_iter20_reg;
reg   [63:0] zext_ln161_reg_715_pp0_iter21_reg;
reg   [63:0] zext_ln161_reg_715_pp0_iter22_reg;
reg   [63:0] zext_ln161_reg_715_pp0_iter23_reg;
reg   [63:0] zext_ln161_reg_715_pp0_iter24_reg;
wire   [3:0] trunc_ln161_fu_629_p1;
reg   [3:0] trunc_ln161_reg_815;
reg   [3:0] trunc_ln161_reg_815_pp0_iter1_reg;
reg   [3:0] trunc_ln161_reg_815_pp0_iter2_reg;
reg   [3:0] trunc_ln161_reg_815_pp0_iter3_reg;
reg   [3:0] trunc_ln161_reg_815_pp0_iter4_reg;
reg   [3:0] trunc_ln161_reg_815_pp0_iter5_reg;
reg   [3:0] trunc_ln161_reg_815_pp0_iter6_reg;
reg   [3:0] trunc_ln161_reg_815_pp0_iter7_reg;
reg   [3:0] trunc_ln161_reg_815_pp0_iter8_reg;
reg   [3:0] trunc_ln161_reg_815_pp0_iter9_reg;
reg   [3:0] trunc_ln161_reg_815_pp0_iter10_reg;
reg   [3:0] trunc_ln161_reg_815_pp0_iter11_reg;
reg   [3:0] trunc_ln161_reg_815_pp0_iter12_reg;
reg   [3:0] trunc_ln161_reg_815_pp0_iter13_reg;
reg   [3:0] trunc_ln161_reg_815_pp0_iter14_reg;
reg   [3:0] trunc_ln161_reg_815_pp0_iter15_reg;
reg   [3:0] trunc_ln161_reg_815_pp0_iter16_reg;
reg   [3:0] trunc_ln161_reg_815_pp0_iter17_reg;
reg   [3:0] trunc_ln161_reg_815_pp0_iter18_reg;
reg   [3:0] trunc_ln161_reg_815_pp0_iter19_reg;
reg   [3:0] trunc_ln161_reg_815_pp0_iter20_reg;
reg   [3:0] trunc_ln161_reg_815_pp0_iter21_reg;
reg   [3:0] trunc_ln161_reg_815_pp0_iter22_reg;
reg   [3:0] trunc_ln161_reg_815_pp0_iter23_reg;
reg   [3:0] trunc_ln161_reg_815_pp0_iter24_reg;
wire   [31:0] tmp_3_fu_638_p18;
reg   [31:0] tmp_3_reg_820;
reg   [31:0] tmp_3_reg_820_pp0_iter2_reg;
reg   [31:0] tmp_3_reg_820_pp0_iter3_reg;
reg   [31:0] tmp_3_reg_820_pp0_iter4_reg;
reg   [31:0] tmp_3_reg_820_pp0_iter5_reg;
reg   [31:0] tmp_3_reg_820_pp0_iter6_reg;
reg   [31:0] tmp_3_reg_820_pp0_iter7_reg;
reg   [31:0] tmp_3_reg_820_pp0_iter8_reg;
reg   [31:0] tmp_3_reg_820_pp0_iter9_reg;
reg   [31:0] tmp_3_reg_820_pp0_iter10_reg;
reg   [31:0] tmp_3_reg_820_pp0_iter11_reg;
reg   [31:0] tmp_3_reg_820_pp0_iter12_reg;
reg   [31:0] tmp_3_reg_820_pp0_iter13_reg;
reg   [31:0] tmp_3_reg_820_pp0_iter14_reg;
reg   [31:0] tmp_3_reg_820_pp0_iter15_reg;
reg   [31:0] tmp_3_reg_820_pp0_iter16_reg;
reg   [31:0] tmp_3_reg_820_pp0_iter17_reg;
reg   [31:0] tmp_3_reg_820_pp0_iter18_reg;
reg   [31:0] tmp_3_reg_820_pp0_iter19_reg;
reg   [31:0] tmp_3_reg_820_pp0_iter20_reg;
reg   [31:0] tmp_3_reg_820_pp0_iter21_reg;
wire   [31:0] bitcast_ln161_1_fu_685_p1;
reg   [31:0] tmp_4_reg_830;
reg   [31:0] add_i2_reg_835;
reg   [31:0] sig_reg_840;
reg   [15:0] trunc_ln_reg_845;
wire    ap_block_pp0_stage0;
reg   [15:0] i_fu_140;
wire   [15:0] add_ln160_fu_593_p2;
wire    ap_loop_init;
reg   [15:0] ap_sig_allocacmp_i_15;
wire   [10:0] lshr_ln6_fu_599_p4;
wire   [31:0] bitcast_ln161_fu_675_p1;
wire   [31:0] xor_ln161_fu_679_p2;
wire   [31:0] bitcast_ln164_fu_690_p1;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg    ap_loop_exit_ready_pp0_iter22_reg;
reg    ap_loop_exit_ready_pp0_iter23_reg;
reg    ap_loop_exit_ready_pp0_iter24_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_done_reg = 1'b0;
end

activation_accelerator_mux_164_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_164_32_1_1_U209(
    .din0(x_q0),
    .din1(x_2_q0),
    .din2(x_4_q0),
    .din3(x_6_q0),
    .din4(x_8_q0),
    .din5(x_10_q0),
    .din6(x_12_q0),
    .din7(x_14_q0),
    .din8(x_16_q0),
    .din9(x_18_q0),
    .din10(x_20_q0),
    .din11(x_22_q0),
    .din12(x_24_q0),
    .din13(x_26_q0),
    .din14(x_28_q0),
    .din15(x_30_q0),
    .din16(trunc_ln161_reg_815),
    .dout(tmp_3_fu_638_p18)
);

activation_accelerator_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter24_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln160_fu_587_p2 == 1'd0))) begin
            i_fu_140 <= add_ln160_fu_593_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_140 <= 16'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_i2_reg_835 <= grp_fu_1416_p_dout0;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
        ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
        ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
        ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        sig_reg_840 <= grp_fu_1420_p_dout0;
        tmp_3_reg_820_pp0_iter10_reg <= tmp_3_reg_820_pp0_iter9_reg;
        tmp_3_reg_820_pp0_iter11_reg <= tmp_3_reg_820_pp0_iter10_reg;
        tmp_3_reg_820_pp0_iter12_reg <= tmp_3_reg_820_pp0_iter11_reg;
        tmp_3_reg_820_pp0_iter13_reg <= tmp_3_reg_820_pp0_iter12_reg;
        tmp_3_reg_820_pp0_iter14_reg <= tmp_3_reg_820_pp0_iter13_reg;
        tmp_3_reg_820_pp0_iter15_reg <= tmp_3_reg_820_pp0_iter14_reg;
        tmp_3_reg_820_pp0_iter16_reg <= tmp_3_reg_820_pp0_iter15_reg;
        tmp_3_reg_820_pp0_iter17_reg <= tmp_3_reg_820_pp0_iter16_reg;
        tmp_3_reg_820_pp0_iter18_reg <= tmp_3_reg_820_pp0_iter17_reg;
        tmp_3_reg_820_pp0_iter19_reg <= tmp_3_reg_820_pp0_iter18_reg;
        tmp_3_reg_820_pp0_iter20_reg <= tmp_3_reg_820_pp0_iter19_reg;
        tmp_3_reg_820_pp0_iter21_reg <= tmp_3_reg_820_pp0_iter20_reg;
        tmp_3_reg_820_pp0_iter2_reg <= tmp_3_reg_820;
        tmp_3_reg_820_pp0_iter3_reg <= tmp_3_reg_820_pp0_iter2_reg;
        tmp_3_reg_820_pp0_iter4_reg <= tmp_3_reg_820_pp0_iter3_reg;
        tmp_3_reg_820_pp0_iter5_reg <= tmp_3_reg_820_pp0_iter4_reg;
        tmp_3_reg_820_pp0_iter6_reg <= tmp_3_reg_820_pp0_iter5_reg;
        tmp_3_reg_820_pp0_iter7_reg <= tmp_3_reg_820_pp0_iter6_reg;
        tmp_3_reg_820_pp0_iter8_reg <= tmp_3_reg_820_pp0_iter7_reg;
        tmp_3_reg_820_pp0_iter9_reg <= tmp_3_reg_820_pp0_iter8_reg;
        tmp_4_reg_830 <= grp_fu_1424_p_dout0;
        trunc_ln161_reg_815_pp0_iter10_reg <= trunc_ln161_reg_815_pp0_iter9_reg;
        trunc_ln161_reg_815_pp0_iter11_reg <= trunc_ln161_reg_815_pp0_iter10_reg;
        trunc_ln161_reg_815_pp0_iter12_reg <= trunc_ln161_reg_815_pp0_iter11_reg;
        trunc_ln161_reg_815_pp0_iter13_reg <= trunc_ln161_reg_815_pp0_iter12_reg;
        trunc_ln161_reg_815_pp0_iter14_reg <= trunc_ln161_reg_815_pp0_iter13_reg;
        trunc_ln161_reg_815_pp0_iter15_reg <= trunc_ln161_reg_815_pp0_iter14_reg;
        trunc_ln161_reg_815_pp0_iter16_reg <= trunc_ln161_reg_815_pp0_iter15_reg;
        trunc_ln161_reg_815_pp0_iter17_reg <= trunc_ln161_reg_815_pp0_iter16_reg;
        trunc_ln161_reg_815_pp0_iter18_reg <= trunc_ln161_reg_815_pp0_iter17_reg;
        trunc_ln161_reg_815_pp0_iter19_reg <= trunc_ln161_reg_815_pp0_iter18_reg;
        trunc_ln161_reg_815_pp0_iter20_reg <= trunc_ln161_reg_815_pp0_iter19_reg;
        trunc_ln161_reg_815_pp0_iter21_reg <= trunc_ln161_reg_815_pp0_iter20_reg;
        trunc_ln161_reg_815_pp0_iter22_reg <= trunc_ln161_reg_815_pp0_iter21_reg;
        trunc_ln161_reg_815_pp0_iter23_reg <= trunc_ln161_reg_815_pp0_iter22_reg;
        trunc_ln161_reg_815_pp0_iter24_reg <= trunc_ln161_reg_815_pp0_iter23_reg;
        trunc_ln161_reg_815_pp0_iter2_reg <= trunc_ln161_reg_815_pp0_iter1_reg;
        trunc_ln161_reg_815_pp0_iter3_reg <= trunc_ln161_reg_815_pp0_iter2_reg;
        trunc_ln161_reg_815_pp0_iter4_reg <= trunc_ln161_reg_815_pp0_iter3_reg;
        trunc_ln161_reg_815_pp0_iter5_reg <= trunc_ln161_reg_815_pp0_iter4_reg;
        trunc_ln161_reg_815_pp0_iter6_reg <= trunc_ln161_reg_815_pp0_iter5_reg;
        trunc_ln161_reg_815_pp0_iter7_reg <= trunc_ln161_reg_815_pp0_iter6_reg;
        trunc_ln161_reg_815_pp0_iter8_reg <= trunc_ln161_reg_815_pp0_iter7_reg;
        trunc_ln161_reg_815_pp0_iter9_reg <= trunc_ln161_reg_815_pp0_iter8_reg;
        trunc_ln_reg_845 <= {{bitcast_ln164_fu_690_p1[31:16]}};
        zext_ln161_reg_715_pp0_iter10_reg[10 : 0] <= zext_ln161_reg_715_pp0_iter9_reg[10 : 0];
        zext_ln161_reg_715_pp0_iter11_reg[10 : 0] <= zext_ln161_reg_715_pp0_iter10_reg[10 : 0];
        zext_ln161_reg_715_pp0_iter12_reg[10 : 0] <= zext_ln161_reg_715_pp0_iter11_reg[10 : 0];
        zext_ln161_reg_715_pp0_iter13_reg[10 : 0] <= zext_ln161_reg_715_pp0_iter12_reg[10 : 0];
        zext_ln161_reg_715_pp0_iter14_reg[10 : 0] <= zext_ln161_reg_715_pp0_iter13_reg[10 : 0];
        zext_ln161_reg_715_pp0_iter15_reg[10 : 0] <= zext_ln161_reg_715_pp0_iter14_reg[10 : 0];
        zext_ln161_reg_715_pp0_iter16_reg[10 : 0] <= zext_ln161_reg_715_pp0_iter15_reg[10 : 0];
        zext_ln161_reg_715_pp0_iter17_reg[10 : 0] <= zext_ln161_reg_715_pp0_iter16_reg[10 : 0];
        zext_ln161_reg_715_pp0_iter18_reg[10 : 0] <= zext_ln161_reg_715_pp0_iter17_reg[10 : 0];
        zext_ln161_reg_715_pp0_iter19_reg[10 : 0] <= zext_ln161_reg_715_pp0_iter18_reg[10 : 0];
        zext_ln161_reg_715_pp0_iter20_reg[10 : 0] <= zext_ln161_reg_715_pp0_iter19_reg[10 : 0];
        zext_ln161_reg_715_pp0_iter21_reg[10 : 0] <= zext_ln161_reg_715_pp0_iter20_reg[10 : 0];
        zext_ln161_reg_715_pp0_iter22_reg[10 : 0] <= zext_ln161_reg_715_pp0_iter21_reg[10 : 0];
        zext_ln161_reg_715_pp0_iter23_reg[10 : 0] <= zext_ln161_reg_715_pp0_iter22_reg[10 : 0];
        zext_ln161_reg_715_pp0_iter24_reg[10 : 0] <= zext_ln161_reg_715_pp0_iter23_reg[10 : 0];
        zext_ln161_reg_715_pp0_iter2_reg[10 : 0] <= zext_ln161_reg_715_pp0_iter1_reg[10 : 0];
        zext_ln161_reg_715_pp0_iter3_reg[10 : 0] <= zext_ln161_reg_715_pp0_iter2_reg[10 : 0];
        zext_ln161_reg_715_pp0_iter4_reg[10 : 0] <= zext_ln161_reg_715_pp0_iter3_reg[10 : 0];
        zext_ln161_reg_715_pp0_iter5_reg[10 : 0] <= zext_ln161_reg_715_pp0_iter4_reg[10 : 0];
        zext_ln161_reg_715_pp0_iter6_reg[10 : 0] <= zext_ln161_reg_715_pp0_iter5_reg[10 : 0];
        zext_ln161_reg_715_pp0_iter7_reg[10 : 0] <= zext_ln161_reg_715_pp0_iter6_reg[10 : 0];
        zext_ln161_reg_715_pp0_iter8_reg[10 : 0] <= zext_ln161_reg_715_pp0_iter7_reg[10 : 0];
        zext_ln161_reg_715_pp0_iter9_reg[10 : 0] <= zext_ln161_reg_715_pp0_iter8_reg[10 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        tmp_3_reg_820 <= tmp_3_fu_638_p18;
        trunc_ln161_reg_815_pp0_iter1_reg <= trunc_ln161_reg_815;
        zext_ln161_reg_715_pp0_iter1_reg[10 : 0] <= zext_ln161_reg_715[10 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln160_fu_587_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        trunc_ln161_reg_815 <= trunc_ln161_fu_629_p1;
        zext_ln161_reg_715[10 : 0] <= zext_ln161_fu_609_p1[10 : 0];
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_ce0 = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (trunc_ln161_reg_815_pp0_iter24_reg == 4'd8) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_we0 = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_ce0 = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (trunc_ln161_reg_815_pp0_iter24_reg == 4'd7) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_we0 = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_ce0 = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (trunc_ln161_reg_815_pp0_iter24_reg == 4'd6) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_we0 = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_ce0 = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (trunc_ln161_reg_815_pp0_iter24_reg == 4'd5) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_we0 = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_ce0 = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (trunc_ln161_reg_815_pp0_iter24_reg == 4'd4) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_we0 = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_ce0 = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (trunc_ln161_reg_815_pp0_iter24_reg == 4'd3) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_we0 = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_ce0 = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (trunc_ln161_reg_815_pp0_iter24_reg == 4'd2) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_we0 = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_ce0 = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (trunc_ln161_reg_815_pp0_iter24_reg == 4'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_we0 = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_ce0 = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (trunc_ln161_reg_815_pp0_iter24_reg == 4'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_we0 = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_ce0 = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (trunc_ln161_reg_815_pp0_iter24_reg == 4'd9) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_we0 = 1'b1;
    end else begin
        activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln160_fu_587_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter24_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_i_15 = 16'd0;
    end else begin
        ap_sig_allocacmp_i_15 = i_fu_140;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_10_ce0 = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (trunc_ln161_reg_815_pp0_iter24_reg == 4'd10) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_10_we0 = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_11_ce0 = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (trunc_ln161_reg_815_pp0_iter24_reg == 4'd11) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_11_we0 = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_12_ce0 = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (trunc_ln161_reg_815_pp0_iter24_reg == 4'd12) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_12_we0 = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_13_ce0 = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (trunc_ln161_reg_815_pp0_iter24_reg == 4'd13) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_13_we0 = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_14_ce0 = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (trunc_ln161_reg_815_pp0_iter24_reg == 4'd14) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_14_we0 = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_15_ce0 = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (trunc_ln161_reg_815_pp0_iter24_reg == 4'd15) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_15_we0 = 1'b1;
    end else begin
        p_ZZ22activation_acceleratorPtS_S_iiE4buf2_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_10_ce0 = 1'b1;
    end else begin
        x_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_12_ce0 = 1'b1;
    end else begin
        x_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_14_ce0 = 1'b1;
    end else begin
        x_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_16_ce0 = 1'b1;
    end else begin
        x_16_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_18_ce0 = 1'b1;
    end else begin
        x_18_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_20_ce0 = 1'b1;
    end else begin
        x_20_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_22_ce0 = 1'b1;
    end else begin
        x_22_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_24_ce0 = 1'b1;
    end else begin
        x_24_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_26_ce0 = 1'b1;
    end else begin
        x_26_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_28_ce0 = 1'b1;
    end else begin
        x_28_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_2_ce0 = 1'b1;
    end else begin
        x_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_30_ce0 = 1'b1;
    end else begin
        x_30_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_4_ce0 = 1'b1;
    end else begin
        x_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_6_ce0 = 1'b1;
    end else begin
        x_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_8_ce0 = 1'b1;
    end else begin
        x_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_ce0 = 1'b1;
    end else begin
        x_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_address0 = zext_ln161_reg_715_pp0_iter24_reg;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_1_d0 = trunc_ln_reg_845;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_address0 = zext_ln161_reg_715_pp0_iter24_reg;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_2_d0 = trunc_ln_reg_845;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_address0 = zext_ln161_reg_715_pp0_iter24_reg;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_3_d0 = trunc_ln_reg_845;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_address0 = zext_ln161_reg_715_pp0_iter24_reg;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_4_d0 = trunc_ln_reg_845;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_address0 = zext_ln161_reg_715_pp0_iter24_reg;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_5_d0 = trunc_ln_reg_845;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_address0 = zext_ln161_reg_715_pp0_iter24_reg;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_6_d0 = trunc_ln_reg_845;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_address0 = zext_ln161_reg_715_pp0_iter24_reg;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_7_d0 = trunc_ln_reg_845;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_address0 = zext_ln161_reg_715_pp0_iter24_reg;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_8_d0 = trunc_ln_reg_845;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_address0 = zext_ln161_reg_715_pp0_iter24_reg;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_d0 = trunc_ln_reg_845;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_address0 = zext_ln161_reg_715_pp0_iter24_reg;

assign activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_d0 = trunc_ln_reg_845;

assign add_ln160_fu_593_p2 = (ap_sig_allocacmp_i_15 + 16'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter22 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage0_iter23 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter24 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage0_iter25 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign bitcast_ln161_1_fu_685_p1 = xor_ln161_fu_679_p2;

assign bitcast_ln161_fu_675_p1 = tmp_3_fu_638_p18;

assign bitcast_ln164_fu_690_p1 = grp_fu_1201_p_dout0;

assign grp_fu_1201_p_ce = 1'b1;

assign grp_fu_1201_p_din0 = tmp_3_reg_820_pp0_iter21_reg;

assign grp_fu_1201_p_din1 = sig_reg_840;

assign grp_fu_1416_p_ce = 1'b1;

assign grp_fu_1416_p_din0 = tmp_4_reg_830;

assign grp_fu_1416_p_din1 = 32'd1065353216;

assign grp_fu_1416_p_opcode = 2'd0;

assign grp_fu_1420_p_ce = 1'b1;

assign grp_fu_1420_p_din0 = 32'd1065353216;

assign grp_fu_1420_p_din1 = add_i2_reg_835;

assign grp_fu_1424_p_ce = 1'b1;

assign grp_fu_1424_p_din0 = 32'd0;

assign grp_fu_1424_p_din1 = bitcast_ln161_1_fu_685_p1;

assign icmp_ln160_fu_587_p2 = ((ap_sig_allocacmp_i_15 == 16'd32768) ? 1'b1 : 1'b0);

assign lshr_ln6_fu_599_p4 = {{ap_sig_allocacmp_i_15[14:4]}};

assign p_ZZ22activation_acceleratorPtS_S_iiE4buf2_10_address0 = zext_ln161_reg_715_pp0_iter24_reg;

assign p_ZZ22activation_acceleratorPtS_S_iiE4buf2_10_d0 = trunc_ln_reg_845;

assign p_ZZ22activation_acceleratorPtS_S_iiE4buf2_11_address0 = zext_ln161_reg_715_pp0_iter24_reg;

assign p_ZZ22activation_acceleratorPtS_S_iiE4buf2_11_d0 = trunc_ln_reg_845;

assign p_ZZ22activation_acceleratorPtS_S_iiE4buf2_12_address0 = zext_ln161_reg_715_pp0_iter24_reg;

assign p_ZZ22activation_acceleratorPtS_S_iiE4buf2_12_d0 = trunc_ln_reg_845;

assign p_ZZ22activation_acceleratorPtS_S_iiE4buf2_13_address0 = zext_ln161_reg_715_pp0_iter24_reg;

assign p_ZZ22activation_acceleratorPtS_S_iiE4buf2_13_d0 = trunc_ln_reg_845;

assign p_ZZ22activation_acceleratorPtS_S_iiE4buf2_14_address0 = zext_ln161_reg_715_pp0_iter24_reg;

assign p_ZZ22activation_acceleratorPtS_S_iiE4buf2_14_d0 = trunc_ln_reg_845;

assign p_ZZ22activation_acceleratorPtS_S_iiE4buf2_15_address0 = zext_ln161_reg_715_pp0_iter24_reg;

assign p_ZZ22activation_acceleratorPtS_S_iiE4buf2_15_d0 = trunc_ln_reg_845;

assign trunc_ln161_fu_629_p1 = ap_sig_allocacmp_i_15[3:0];

assign x_10_address0 = zext_ln161_fu_609_p1;

assign x_12_address0 = zext_ln161_fu_609_p1;

assign x_14_address0 = zext_ln161_fu_609_p1;

assign x_16_address0 = zext_ln161_fu_609_p1;

assign x_18_address0 = zext_ln161_fu_609_p1;

assign x_20_address0 = zext_ln161_fu_609_p1;

assign x_22_address0 = zext_ln161_fu_609_p1;

assign x_24_address0 = zext_ln161_fu_609_p1;

assign x_26_address0 = zext_ln161_fu_609_p1;

assign x_28_address0 = zext_ln161_fu_609_p1;

assign x_2_address0 = zext_ln161_fu_609_p1;

assign x_30_address0 = zext_ln161_fu_609_p1;

assign x_4_address0 = zext_ln161_fu_609_p1;

assign x_6_address0 = zext_ln161_fu_609_p1;

assign x_8_address0 = zext_ln161_fu_609_p1;

assign x_address0 = zext_ln161_fu_609_p1;

assign xor_ln161_fu_679_p2 = (bitcast_ln161_fu_675_p1 ^ 32'd2147483648);

assign zext_ln161_fu_609_p1 = lshr_ln6_fu_599_p4;

always @ (posedge ap_clk) begin
    zext_ln161_reg_715[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln161_reg_715_pp0_iter1_reg[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln161_reg_715_pp0_iter2_reg[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln161_reg_715_pp0_iter3_reg[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln161_reg_715_pp0_iter4_reg[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln161_reg_715_pp0_iter5_reg[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln161_reg_715_pp0_iter6_reg[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln161_reg_715_pp0_iter7_reg[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln161_reg_715_pp0_iter8_reg[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln161_reg_715_pp0_iter9_reg[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln161_reg_715_pp0_iter10_reg[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln161_reg_715_pp0_iter11_reg[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln161_reg_715_pp0_iter12_reg[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln161_reg_715_pp0_iter13_reg[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln161_reg_715_pp0_iter14_reg[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln161_reg_715_pp0_iter15_reg[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln161_reg_715_pp0_iter16_reg[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln161_reg_715_pp0_iter17_reg[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln161_reg_715_pp0_iter18_reg[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln161_reg_715_pp0_iter19_reg[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln161_reg_715_pp0_iter20_reg[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln161_reg_715_pp0_iter21_reg[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln161_reg_715_pp0_iter22_reg[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln161_reg_715_pp0_iter23_reg[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln161_reg_715_pp0_iter24_reg[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
end

endmodule //activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_160_1
