set SynModuleInfo {
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_499_4 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_499_4 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_499_4
    SUBMODULES {
      {MODELNAME activation_accelerator_flow_control_loop_pipe_sequential_init RTLNAME activation_accelerator_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME activation_accelerator_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_145_18 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_145_18 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_145_18}
  {SRCNAME activation_accelerator_Pipeline_layer_norm_loop1 MODELNAME activation_accelerator_Pipeline_layer_norm_loop1 RTLNAME activation_accelerator_activation_accelerator_Pipeline_layer_norm_loop1}
  {SRCNAME activation_accelerator_Pipeline_layer_norm_loop2 MODELNAME activation_accelerator_Pipeline_layer_norm_loop2 RTLNAME activation_accelerator_activation_accelerator_Pipeline_layer_norm_loop2}
  {SRCNAME activation_accelerator_Pipeline_layer_norm_loop3 MODELNAME activation_accelerator_Pipeline_layer_norm_loop3 RTLNAME activation_accelerator_activation_accelerator_Pipeline_layer_norm_loop3}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_145_17 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_145_17 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_145_17}
  {SRCNAME activation_accelerator_Pipeline_rms_norm_loop1 MODELNAME activation_accelerator_Pipeline_rms_norm_loop1 RTLNAME activation_accelerator_activation_accelerator_Pipeline_rms_norm_loop1}
  {SRCNAME activation_accelerator_Pipeline_rms_norm_loop2 MODELNAME activation_accelerator_Pipeline_rms_norm_loop2 RTLNAME activation_accelerator_activation_accelerator_Pipeline_rms_norm_loop2}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_145_16 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_145_16 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_145_16}
  {SRCNAME activation_accelerator_Pipeline_silu_loop MODELNAME activation_accelerator_Pipeline_silu_loop RTLNAME activation_accelerator_activation_accelerator_Pipeline_silu_loop
    SUBMODULES {
      {MODELNAME activation_accelerator_fadd_32ns_32ns_32_4_full_dsp_1 RTLNAME activation_accelerator_fadd_32ns_32ns_32_4_full_dsp_1 BINDTYPE op TYPE fadd IMPL fulldsp LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_fexp_32ns_32ns_32_8_full_dsp_1 RTLNAME activation_accelerator_fexp_32ns_32ns_32_8_full_dsp_1 BINDTYPE op TYPE fexp IMPL fulldsp LATENCY 7 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_145_15 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_145_15 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_145_15}
  {SRCNAME generic_erf<float> MODELNAME generic_erf_float_s RTLNAME activation_accelerator_generic_erf_float_s
    SUBMODULES {
      {MODELNAME activation_accelerator_faddfsub_32ns_32ns_32_4_full_dsp_1_x RTLNAME activation_accelerator_faddfsub_32ns_32ns_32_4_full_dsp_1_x BINDTYPE op TYPE fsub IMPL fulldsp LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_fadd_32ns_32ns_32_4_full_dsp_1_x RTLNAME activation_accelerator_fadd_32ns_32ns_32_4_full_dsp_1_x BINDTYPE op TYPE fadd IMPL fulldsp LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_fmul_32ns_32ns_32_3_max_dsp_1_x RTLNAME activation_accelerator_fmul_32ns_32ns_32_3_max_dsp_1_x BINDTYPE op TYPE fmul IMPL maxdsp LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_fdiv_32ns_32ns_32_9_no_dsp_1_x RTLNAME activation_accelerator_fdiv_32ns_32ns_32_9_no_dsp_1_x BINDTYPE op TYPE fdiv IMPL fabric LATENCY 8 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_fexp_32ns_32ns_32_8_full_dsp_1_x RTLNAME activation_accelerator_fexp_32ns_32ns_32_8_full_dsp_1_x BINDTYPE op TYPE fexp IMPL fulldsp LATENCY 7 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME activation_accelerator_Pipeline_gelu_loop MODELNAME activation_accelerator_Pipeline_gelu_loop RTLNAME activation_accelerator_activation_accelerator_Pipeline_gelu_loop}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_145_13 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_145_13 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_145_13}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_145_14 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_145_14 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_145_14}
  {SRCNAME activation_accelerator_Pipeline_float_multiply_loop MODELNAME activation_accelerator_Pipeline_float_multiply_loop RTLNAME activation_accelerator_activation_accelerator_Pipeline_float_multiply_loop}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_145_12 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_145_12 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_145_12}
  {SRCNAME float_safe_softmax_Pipeline_softmax_loop_1 MODELNAME float_safe_softmax_Pipeline_softmax_loop_1 RTLNAME activation_accelerator_float_safe_softmax_Pipeline_softmax_loop_1
    SUBMODULES {
      {MODELNAME activation_accelerator_fcmp_32ns_32ns_1_2_no_dsp_1 RTLNAME activation_accelerator_fcmp_32ns_32ns_1_2_no_dsp_1 BINDTYPE op TYPE fcmp IMPL auto LATENCY 1 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME float_safe_softmax_Pipeline_softmax_loop_2 MODELNAME float_safe_softmax_Pipeline_softmax_loop_2 RTLNAME activation_accelerator_float_safe_softmax_Pipeline_softmax_loop_2}
  {SRCNAME float_safe_softmax_Pipeline_softmax_loop_3 MODELNAME float_safe_softmax_Pipeline_softmax_loop_3 RTLNAME activation_accelerator_float_safe_softmax_Pipeline_softmax_loop_3}
  {SRCNAME float_safe_softmax MODELNAME float_safe_softmax RTLNAME activation_accelerator_float_safe_softmax
    SUBMODULES {
      {MODELNAME activation_accelerator_float_safe_softmax_exp_x_RAM_AUTO_1R1W RTLNAME activation_accelerator_float_safe_softmax_exp_x_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_145_1 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_145_1 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_145_1}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_145_11 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_145_11 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_145_11}
  {SRCNAME activation_accelerator_Pipeline_float_add_loop MODELNAME activation_accelerator_Pipeline_float_add_loop RTLNAME activation_accelerator_activation_accelerator_Pipeline_float_add_loop}
  {SRCNAME bf16add MODELNAME bf16add RTLNAME activation_accelerator_bf16add}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_458_3 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_458_3 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_458_3}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_445_1 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_445_1 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_445_1}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_448_2 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_448_2 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_448_2}
  {SRCNAME activation_accelerator MODELNAME activation_accelerator RTLNAME activation_accelerator IS_TOP 1
    SUBMODULES {
      {MODELNAME activation_accelerator_faddfsub_32ns_32ns_32_4_full_dsp_1 RTLNAME activation_accelerator_faddfsub_32ns_32ns_32_4_full_dsp_1 BINDTYPE op TYPE fadd IMPL fulldsp LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_fdiv_32ns_32ns_32_9_no_dsp_1 RTLNAME activation_accelerator_fdiv_32ns_32ns_32_9_no_dsp_1 BINDTYPE op TYPE fdiv IMPL fabric LATENCY 8 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_fsqrt_32ns_32ns_32_8_no_dsp_1 RTLNAME activation_accelerator_fsqrt_32ns_32ns_32_8_no_dsp_1 BINDTYPE op TYPE fsqrt IMPL fabric LATENCY 7 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_fmul_32ns_32ns_32_3_max_dsp_1 RTLNAME activation_accelerator_fmul_32ns_32ns_32_3_max_dsp_1 BINDTYPE op TYPE fmul IMPL maxdsp LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_buf0_RAM_AUTO_1R1W RTLNAME activation_accelerator_buf0_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_x_RAM_AUTO_1R1W RTLNAME activation_accelerator_x_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_gmem0_m_axi RTLNAME activation_accelerator_gmem0_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME activation_accelerator_gmem1_m_axi RTLNAME activation_accelerator_gmem1_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME activation_accelerator_gmem2_m_axi RTLNAME activation_accelerator_gmem2_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME activation_accelerator_control_s_axi RTLNAME activation_accelerator_control_s_axi BINDTYPE interface TYPE interface_s_axilite}
    }
  }
}
