set SynModuleInfo {
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_316_6 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_316_6 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_316_6
    SUBMODULES {
      {MODELNAME activation_accelerator_flow_control_loop_pipe_sequential_init RTLNAME activation_accelerator_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME activation_accelerator_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_144_15 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_144_15 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_144_15}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_185_1 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_185_1 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_185_1}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_190_2 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_190_2 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_190_2}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_196_3 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_196_3 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_196_3}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_144_14 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_144_14 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_144_14}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_170_1 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_170_1 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_170_1}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_175_2 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_175_2 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_175_2}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_144_13 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_144_13 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_144_13}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_159_1 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_159_1 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_159_1
    SUBMODULES {
      {MODELNAME activation_accelerator_fadd_32ns_32ns_32_4_full_dsp_1 RTLNAME activation_accelerator_fadd_32ns_32ns_32_4_full_dsp_1 BINDTYPE op TYPE fadd IMPL fulldsp LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_fexp_32ns_32ns_32_8_full_dsp_1 RTLNAME activation_accelerator_fexp_32ns_32ns_32_8_full_dsp_1 BINDTYPE op TYPE fexp IMPL fulldsp LATENCY 7 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_144_12 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_144_12 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_144_12}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_151_1 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_151_1 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_151_1}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_292_5 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_292_5 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_292_5}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_283_4 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_283_4 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_283_4}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_144_1 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_144_1 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_144_1}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_144_11 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_144_11 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_144_11}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_205_1 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_205_1 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_205_1}
  {SRCNAME bf16add MODELNAME bf16add RTLNAME activation_accelerator_bf16add}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_275_3 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_275_3 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_275_3}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_262_1 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_262_1 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_262_1}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_265_2 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_265_2 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_265_2}
  {SRCNAME activation_accelerator MODELNAME activation_accelerator RTLNAME activation_accelerator IS_TOP 1
    SUBMODULES {
      {MODELNAME activation_accelerator_faddfsub_32ns_32ns_32_4_full_dsp_1 RTLNAME activation_accelerator_faddfsub_32ns_32ns_32_4_full_dsp_1 BINDTYPE op TYPE fadd IMPL fulldsp LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_fmul_32ns_32ns_32_3_max_dsp_1 RTLNAME activation_accelerator_fmul_32ns_32ns_32_3_max_dsp_1 BINDTYPE op TYPE fmul IMPL maxdsp LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_fsqrt_32ns_32ns_32_8_no_dsp_1 RTLNAME activation_accelerator_fsqrt_32ns_32ns_32_8_no_dsp_1 BINDTYPE op TYPE fsqrt IMPL fabric LATENCY 7 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_fdiv_32ns_32ns_32_9_no_dsp_1 RTLNAME activation_accelerator_fdiv_32ns_32ns_32_9_no_dsp_1 BINDTYPE op TYPE fdiv IMPL fabric LATENCY 8 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_buf0_RAM_AUTO_1R1W RTLNAME activation_accelerator_buf0_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_x_RAM_AUTO_1R1W RTLNAME activation_accelerator_x_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_gmem0_m_axi RTLNAME activation_accelerator_gmem0_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME activation_accelerator_gmem1_m_axi RTLNAME activation_accelerator_gmem1_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME activation_accelerator_gmem2_m_axi RTLNAME activation_accelerator_gmem2_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME activation_accelerator_control_s_axi RTLNAME activation_accelerator_control_s_axi BINDTYPE interface TYPE interface_s_axilite}
    }
  }
}
