set SynModuleInfo {
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_336_1 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_336_1 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_336_1
    SUBMODULES {
      {MODELNAME activation_accelerator_flow_control_loop_pipe_sequential_init RTLNAME activation_accelerator_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME activation_accelerator_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME bf16_to_float MODELNAME bf16_to_float RTLNAME activation_accelerator_bf16_to_float
    SUBMODULES {
      {MODELNAME activation_accelerator_mux_325_16_1_1 RTLNAME activation_accelerator_mux_325_16_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME activation_accelerator_Pipeline_layer_loop_0 MODELNAME activation_accelerator_Pipeline_layer_loop_0 RTLNAME activation_accelerator_activation_accelerator_Pipeline_layer_loop_0}
  {SRCNAME activation_accelerator_Pipeline_layer_loop_1 MODELNAME activation_accelerator_Pipeline_layer_loop_1 RTLNAME activation_accelerator_activation_accelerator_Pipeline_layer_loop_1}
  {SRCNAME activation_accelerator_Pipeline_layer_loop_2 MODELNAME activation_accelerator_Pipeline_layer_loop_2 RTLNAME activation_accelerator_activation_accelerator_Pipeline_layer_loop_2}
  {SRCNAME activation_accelerator_Pipeline_rms_loop_0 MODELNAME activation_accelerator_Pipeline_rms_loop_0 RTLNAME activation_accelerator_activation_accelerator_Pipeline_rms_loop_0}
  {SRCNAME activation_accelerator_Pipeline_rms_loop_1 MODELNAME activation_accelerator_Pipeline_rms_loop_1 RTLNAME activation_accelerator_activation_accelerator_Pipeline_rms_loop_1}
  {SRCNAME activation_accelerator_Pipeline_silu_loop MODELNAME activation_accelerator_Pipeline_silu_loop RTLNAME activation_accelerator_activation_accelerator_Pipeline_silu_loop
    SUBMODULES {
      {MODELNAME activation_accelerator_fadd_32ns_32ns_32_4_full_dsp_1 RTLNAME activation_accelerator_fadd_32ns_32ns_32_4_full_dsp_1 BINDTYPE op TYPE fadd IMPL fulldsp LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_fexp_32ns_32ns_32_8_full_dsp_1 RTLNAME activation_accelerator_fexp_32ns_32ns_32_8_full_dsp_1 BINDTYPE op TYPE fexp IMPL fulldsp LATENCY 7 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME activation_accelerator_Pipeline_sigmoid_loop MODELNAME activation_accelerator_Pipeline_sigmoid_loop RTLNAME activation_accelerator_activation_accelerator_Pipeline_sigmoid_loop}
  {SRCNAME float_mask_safe_softmax_Pipeline_mask_softmax_loop_0 MODELNAME float_mask_safe_softmax_Pipeline_mask_softmax_loop_0 RTLNAME activation_accelerator_float_mask_safe_softmax_Pipeline_mask_softmax_loop_0}
  {SRCNAME float_mask_safe_softmax_Pipeline_mask_softmax_loop_1 MODELNAME float_mask_safe_softmax_Pipeline_mask_softmax_loop_1 RTLNAME activation_accelerator_float_mask_safe_softmax_Pipeline_mask_softmax_loop_1}
  {SRCNAME float_mask_safe_softmax_Pipeline_mask_softmax_loop_2 MODELNAME float_mask_safe_softmax_Pipeline_mask_softmax_loop_2 RTLNAME activation_accelerator_float_mask_safe_softmax_Pipeline_mask_softmax_loop_2
    SUBMODULES {
      {MODELNAME activation_accelerator_fsub_32ns_32ns_32_4_full_dsp_1 RTLNAME activation_accelerator_fsub_32ns_32ns_32_4_full_dsp_1 BINDTYPE op TYPE fsub IMPL fulldsp LATENCY 3 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME float_mask_safe_softmax_Pipeline_mask_softmax_loop_3 MODELNAME float_mask_safe_softmax_Pipeline_mask_softmax_loop_3 RTLNAME activation_accelerator_float_mask_safe_softmax_Pipeline_mask_softmax_loop_3}
  {SRCNAME float_mask_safe_softmax MODELNAME float_mask_safe_softmax RTLNAME activation_accelerator_float_mask_safe_softmax
    SUBMODULES {
      {MODELNAME activation_accelerator_fcmp_32ns_32ns_1_2_no_dsp_1 RTLNAME activation_accelerator_fcmp_32ns_32ns_1_2_no_dsp_1 BINDTYPE op TYPE fcmp IMPL auto LATENCY 1 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_float_mask_safe_softmax_x_mask_RAM_S2P_BRAM_1R1W RTLNAME activation_accelerator_float_mask_safe_softmax_x_mask_RAM_S2P_BRAM_1R1W BINDTYPE storage TYPE ram_s2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME float_safe_softmax_Pipeline_softmax_loop_0 MODELNAME float_safe_softmax_Pipeline_softmax_loop_0 RTLNAME activation_accelerator_float_safe_softmax_Pipeline_softmax_loop_0}
  {SRCNAME float_safe_softmax_Pipeline_softmax_loop_1 MODELNAME float_safe_softmax_Pipeline_softmax_loop_1 RTLNAME activation_accelerator_float_safe_softmax_Pipeline_softmax_loop_1}
  {SRCNAME float_safe_softmax_Pipeline_softmax_loop_2 MODELNAME float_safe_softmax_Pipeline_softmax_loop_2 RTLNAME activation_accelerator_float_safe_softmax_Pipeline_softmax_loop_2}
  {SRCNAME float_safe_softmax MODELNAME float_safe_softmax RTLNAME activation_accelerator_float_safe_softmax}
  {SRCNAME activation_accelerator_Pipeline_add_loop MODELNAME activation_accelerator_Pipeline_add_loop RTLNAME activation_accelerator_activation_accelerator_Pipeline_add_loop}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_387_3 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_387_3 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_387_3}
  {SRCNAME activation_accelerator MODELNAME activation_accelerator RTLNAME activation_accelerator IS_TOP 1
    SUBMODULES {
      {MODELNAME activation_accelerator_faddfsub_32ns_32ns_32_4_full_dsp_1 RTLNAME activation_accelerator_faddfsub_32ns_32ns_32_4_full_dsp_1 BINDTYPE op TYPE fadd IMPL fulldsp LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_fmul_32ns_32ns_32_3_max_dsp_1 RTLNAME activation_accelerator_fmul_32ns_32ns_32_3_max_dsp_1 BINDTYPE op TYPE fmul IMPL maxdsp LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_fsqrt_32ns_32ns_32_8_no_dsp_1 RTLNAME activation_accelerator_fsqrt_32ns_32ns_32_8_no_dsp_1 BINDTYPE op TYPE fsqrt IMPL fabric LATENCY 7 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_fadd_32ns_32ns_32_4_no_dsp_1 RTLNAME activation_accelerator_fadd_32ns_32ns_32_4_no_dsp_1 BINDTYPE op TYPE fadd IMPL fabric LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_fdiv_32ns_32ns_32_9_no_dsp_1 RTLNAME activation_accelerator_fdiv_32ns_32ns_32_9_no_dsp_1 BINDTYPE op TYPE fdiv IMPL fabric LATENCY 8 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_activation_accelerator_ap_uint_ap_uint_512_ap_uint_512_int_int_tile0_9_RAM_2Pbkb RTLNAME activation_accelerator_activation_accelerator_ap_uint_ap_uint_512_ap_uint_512_int_int_tile0_9_RAM_2Pbkb BINDTYPE storage TYPE ram_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_xt_RAM_S2P_BRAM_1R1W RTLNAME activation_accelerator_xt_RAM_S2P_BRAM_1R1W BINDTYPE storage TYPE ram_s2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_gmem0_m_axi RTLNAME activation_accelerator_gmem0_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME activation_accelerator_gmem1_m_axi RTLNAME activation_accelerator_gmem1_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME activation_accelerator_gmem2_m_axi RTLNAME activation_accelerator_gmem2_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME activation_accelerator_control_s_axi RTLNAME activation_accelerator_control_s_axi BINDTYPE interface TYPE interface_s_axilite}
    }
  }
}
