set ModuleHierarchy {[{
"Name" : "activation_accelerator","ID" : "0","Type" : "sequential",
"SubInsts" : [
	{"Name" : "grp_activation_accelerator_Pipeline_gelu_blocks_fu_6692","ID" : "1","Type" : "sequential",
		"SubLoops" : [
		{"Name" : "gelu_blocks","ID" : "2","Type" : "pipeline"},]},
	{"Name" : "grp_activation_accelerator_Pipeline_add_blocks_add_fu_6952","ID" : "3","Type" : "sequential",
		"SubLoops" : [
		{"Name" : "add_blocks_add","ID" : "4","Type" : "pipeline",
		"SubInsts" : [
		{"Name" : "round_float32_to_bf16_ieee","ID" : "5","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "6","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "7","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "8","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "9","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "10","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "11","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "12","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "13","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "14","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "15","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "16","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "17","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "18","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "19","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "20","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "21","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "22","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "23","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "24","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "25","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "26","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "27","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "28","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "29","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "30","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "31","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "32","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "33","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "34","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "35","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "36","Type" : "pipeline"},]},]},
	{"Name" : "grp_activation_accelerator_Pipeline_multiply_blocks_Multiply_fu_7276","ID" : "37","Type" : "sequential",
		"SubLoops" : [
		{"Name" : "multiply_blocks_Multiply","ID" : "38","Type" : "pipeline"},]},
	{"Name" : "grp_activation_accelerator_Pipeline_rms_sum_square_fu_7600","ID" : "39","Type" : "sequential",
		"SubLoops" : [
		{"Name" : "rms_sum_square","ID" : "40","Type" : "pipeline"},]},
	{"Name" : "grp_activation_accelerator_Pipeline_layernorm_sum_square_fu_7796","ID" : "41","Type" : "sequential",
		"SubLoops" : [
		{"Name" : "layernorm_sum_square","ID" : "42","Type" : "pipeline"},]},
	{"Name" : "grp_activation_accelerator_Pipeline_softmax_max_step_loop_fu_8056","ID" : "43","Type" : "sequential",
		"SubLoops" : [
		{"Name" : "softmax_max_step_loop","ID" : "44","Type" : "pipeline",
		"SubInsts" : [
		{"Name" : "grp_fmaxf_fu_1832","ID" : "45","Type" : "pipeline"},
		{"Name" : "grp_fmaxf_fu_1838","ID" : "46","Type" : "pipeline"},
		{"Name" : "grp_fmaxf_fu_1844","ID" : "47","Type" : "pipeline"},
		{"Name" : "grp_fmaxf_fu_1850","ID" : "48","Type" : "pipeline"},
		{"Name" : "grp_fmaxf_fu_1856","ID" : "49","Type" : "pipeline"},
		{"Name" : "grp_fmaxf_fu_1862","ID" : "50","Type" : "pipeline"},
		{"Name" : "grp_fmaxf_fu_1868","ID" : "51","Type" : "pipeline"},
		{"Name" : "grp_fmaxf_fu_1874","ID" : "52","Type" : "pipeline"},
		{"Name" : "grp_fmaxf_fu_1880","ID" : "53","Type" : "pipeline"},
		{"Name" : "grp_fmaxf_fu_1886","ID" : "54","Type" : "pipeline"},
		{"Name" : "grp_fmaxf_fu_1892","ID" : "55","Type" : "pipeline"},
		{"Name" : "grp_fmaxf_fu_1898","ID" : "56","Type" : "pipeline"},
		{"Name" : "grp_fmaxf_fu_1904","ID" : "57","Type" : "pipeline"},
		{"Name" : "grp_fmaxf_fu_1910","ID" : "58","Type" : "pipeline"},
		{"Name" : "grp_fmaxf_fu_1916","ID" : "59","Type" : "pipeline"},
		{"Name" : "grp_fmaxf_fu_1922","ID" : "60","Type" : "pipeline"},]},]},
	{"Name" : "grp_activation_accelerator_Pipeline_silu_blocks_fu_8252","ID" : "61","Type" : "sequential",
		"SubLoops" : [
		{"Name" : "silu_blocks","ID" : "62","Type" : "pipeline",
		"SubInsts" : [
		{"Name" : "round_float32_to_bf16_ieee","ID" : "63","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "64","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "65","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "66","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "67","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "68","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "69","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "70","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "71","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "72","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "73","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "74","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "75","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "76","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "77","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "78","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "79","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "80","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "81","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "82","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "83","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "84","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "85","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "86","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "87","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "88","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "89","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "90","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "91","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "92","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "93","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "94","Type" : "pipeline"},]},]},
	{"Name" : "grp_activation_accelerator_Pipeline_stage_2_store_fu_8512","ID" : "95","Type" : "sequential",
		"SubLoops" : [
		{"Name" : "stage_2_store","ID" : "96","Type" : "pipeline"},]},
	{"Name" : "grp_activation_accelerator_Pipeline_rms_norm_normalize_blocks_fu_8647","ID" : "97","Type" : "sequential",
		"SubLoops" : [
		{"Name" : "rms_norm_normalize_blocks","ID" : "98","Type" : "pipeline",
		"SubInsts" : [
		{"Name" : "round_float32_to_bf16_ieee","ID" : "99","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "100","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "101","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "102","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "103","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "104","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "105","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "106","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "107","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "108","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "109","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "110","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "111","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "112","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "113","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "114","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "115","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "116","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "117","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "118","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "119","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "120","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "121","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "122","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "123","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "124","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "125","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "126","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "127","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "128","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "129","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "130","Type" : "pipeline"},]},]},
	{"Name" : "grp_activation_accelerator_Pipeline_layer_norm_std_blocks_fu_8971","ID" : "131","Type" : "sequential",
		"SubLoops" : [
		{"Name" : "layer_norm_std_blocks","ID" : "132","Type" : "pipeline"},]},
	{"Name" : "grp_activation_accelerator_Pipeline_layer_norm_normalize_blocks_fu_9167","ID" : "133","Type" : "sequential",
		"SubLoops" : [
		{"Name" : "layer_norm_normalize_blocks","ID" : "134","Type" : "pipeline",
		"SubInsts" : [
		{"Name" : "round_float32_to_bf16_ieee","ID" : "135","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "136","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "137","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "138","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "139","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "140","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "141","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "142","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "143","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "144","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "145","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "146","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "147","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "148","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "149","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "150","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "151","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "152","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "153","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "154","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "155","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "156","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "157","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "158","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "159","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "160","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "161","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "162","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "163","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "164","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "165","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "166","Type" : "pipeline"},]},]},
	{"Name" : "grp_activation_accelerator_Pipeline_softmax_exp_and_bucket_fu_9555","ID" : "167","Type" : "sequential",
		"SubLoops" : [
		{"Name" : "softmax_exp_and_bucket","ID" : "168","Type" : "pipeline"},]},
	{"Name" : "grp_activation_accelerator_Pipeline_softmax_final_fu_9815","ID" : "169","Type" : "sequential",
		"SubLoops" : [
		{"Name" : "softmax_final","ID" : "170","Type" : "pipeline",
		"SubInsts" : [
		{"Name" : "round_float32_to_bf16_ieee","ID" : "171","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "172","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "173","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "174","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "175","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "176","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "177","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "178","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "179","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "180","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "181","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "182","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "183","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "184","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "185","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "186","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "187","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "188","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "189","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "190","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "191","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "192","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "193","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "194","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "195","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "196","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "197","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "198","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "199","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "200","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "201","Type" : "pipeline"},
		{"Name" : "round_float32_to_bf16_ieee","ID" : "202","Type" : "pipeline"},]},]},
	{"Name" : "grp_activation_accelerator_Pipeline_stage_0_load0_fu_10203","ID" : "203","Type" : "sequential",
		"SubLoops" : [
		{"Name" : "stage_0_load0","ID" : "204","Type" : "pipeline"},]},
	{"Name" : "grp_activation_accelerator_Pipeline_stage_0_load1_fu_10338","ID" : "205","Type" : "sequential",
		"SubLoops" : [
		{"Name" : "stage_0_load1","ID" : "206","Type" : "pipeline"},]},]
}]}