// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module activation_accelerator_compute_rows_Pipeline_smx_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        xt_address0,
        xt_ce0,
        xt_q0,
        xt_39_address0,
        xt_39_ce0,
        xt_39_q0,
        xt_47_address0,
        xt_47_ce0,
        xt_47_q0,
        xt_55_address0,
        xt_55_ce0,
        xt_55_q0,
        xmax_3_reload,
        xt_32_address0,
        xt_32_ce0,
        xt_32_q0,
        xt_40_address0,
        xt_40_ce0,
        xt_40_q0,
        xt_48_address0,
        xt_48_ce0,
        xt_48_q0,
        xt_56_address0,
        xt_56_ce0,
        xt_56_q0,
        xt_33_address0,
        xt_33_ce0,
        xt_33_q0,
        xt_41_address0,
        xt_41_ce0,
        xt_41_q0,
        xt_49_address0,
        xt_49_ce0,
        xt_49_q0,
        xt_57_address0,
        xt_57_ce0,
        xt_57_q0,
        xt_34_address0,
        xt_34_ce0,
        xt_34_q0,
        xt_42_address0,
        xt_42_ce0,
        xt_42_q0,
        xt_50_address0,
        xt_50_ce0,
        xt_50_q0,
        xt_58_address0,
        xt_58_ce0,
        xt_58_q0,
        xt_35_address0,
        xt_35_ce0,
        xt_35_q0,
        xt_43_address0,
        xt_43_ce0,
        xt_43_q0,
        xt_51_address0,
        xt_51_ce0,
        xt_51_q0,
        xt_59_address0,
        xt_59_ce0,
        xt_59_q0,
        xt_36_address0,
        xt_36_ce0,
        xt_36_q0,
        xt_44_address0,
        xt_44_ce0,
        xt_44_q0,
        xt_52_address0,
        xt_52_ce0,
        xt_52_q0,
        xt_60_address0,
        xt_60_ce0,
        xt_60_q0,
        xt_37_address0,
        xt_37_ce0,
        xt_37_q0,
        xt_45_address0,
        xt_45_ce0,
        xt_45_q0,
        xt_53_address0,
        xt_53_ce0,
        xt_53_q0,
        xt_61_address0,
        xt_61_ce0,
        xt_61_q0,
        xt_38_address0,
        xt_38_ce0,
        xt_38_q0,
        xt_46_address0,
        xt_46_ce0,
        xt_46_q0,
        xt_54_address0,
        xt_54_ce0,
        xt_54_q0,
        xt_62_address0,
        xt_62_ce0,
        xt_62_q0,
        sum_4_out,
        sum_4_out_ap_vld,
        grp_fu_2042_p_din0,
        grp_fu_2042_p_din1,
        grp_fu_2042_p_opcode,
        grp_fu_2042_p_dout0,
        grp_fu_2042_p_ce,
        grp_fu_2058_p_din0,
        grp_fu_2058_p_din1,
        grp_fu_2058_p_opcode,
        grp_fu_2058_p_dout0,
        grp_fu_2058_p_ce,
        grp_fu_2062_p_din0,
        grp_fu_2062_p_din1,
        grp_fu_2062_p_opcode,
        grp_fu_2062_p_dout0,
        grp_fu_2062_p_ce,
        grp_fu_2066_p_din0,
        grp_fu_2066_p_din1,
        grp_fu_2066_p_opcode,
        grp_fu_2066_p_dout0,
        grp_fu_2066_p_ce,
        grp_fu_2070_p_din0,
        grp_fu_2070_p_din1,
        grp_fu_2070_p_opcode,
        grp_fu_2070_p_dout0,
        grp_fu_2070_p_ce,
        grp_fu_2074_p_din0,
        grp_fu_2074_p_din1,
        grp_fu_2074_p_opcode,
        grp_fu_2074_p_dout0,
        grp_fu_2074_p_ce,
        grp_fu_2054_p_din0,
        grp_fu_2054_p_din1,
        grp_fu_2054_p_dout0,
        grp_fu_2054_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 3'd1;
parameter    ap_ST_fsm_pp0_stage1 = 3'd2;
parameter    ap_ST_fsm_pp0_stage2 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] xt_address0;
output   xt_ce0;
input  [31:0] xt_q0;
output  [4:0] xt_39_address0;
output   xt_39_ce0;
input  [31:0] xt_39_q0;
output  [4:0] xt_47_address0;
output   xt_47_ce0;
input  [31:0] xt_47_q0;
output  [4:0] xt_55_address0;
output   xt_55_ce0;
input  [31:0] xt_55_q0;
input  [31:0] xmax_3_reload;
output  [4:0] xt_32_address0;
output   xt_32_ce0;
input  [31:0] xt_32_q0;
output  [4:0] xt_40_address0;
output   xt_40_ce0;
input  [31:0] xt_40_q0;
output  [4:0] xt_48_address0;
output   xt_48_ce0;
input  [31:0] xt_48_q0;
output  [4:0] xt_56_address0;
output   xt_56_ce0;
input  [31:0] xt_56_q0;
output  [4:0] xt_33_address0;
output   xt_33_ce0;
input  [31:0] xt_33_q0;
output  [4:0] xt_41_address0;
output   xt_41_ce0;
input  [31:0] xt_41_q0;
output  [4:0] xt_49_address0;
output   xt_49_ce0;
input  [31:0] xt_49_q0;
output  [4:0] xt_57_address0;
output   xt_57_ce0;
input  [31:0] xt_57_q0;
output  [4:0] xt_34_address0;
output   xt_34_ce0;
input  [31:0] xt_34_q0;
output  [4:0] xt_42_address0;
output   xt_42_ce0;
input  [31:0] xt_42_q0;
output  [4:0] xt_50_address0;
output   xt_50_ce0;
input  [31:0] xt_50_q0;
output  [4:0] xt_58_address0;
output   xt_58_ce0;
input  [31:0] xt_58_q0;
output  [4:0] xt_35_address0;
output   xt_35_ce0;
input  [31:0] xt_35_q0;
output  [4:0] xt_43_address0;
output   xt_43_ce0;
input  [31:0] xt_43_q0;
output  [4:0] xt_51_address0;
output   xt_51_ce0;
input  [31:0] xt_51_q0;
output  [4:0] xt_59_address0;
output   xt_59_ce0;
input  [31:0] xt_59_q0;
output  [4:0] xt_36_address0;
output   xt_36_ce0;
input  [31:0] xt_36_q0;
output  [4:0] xt_44_address0;
output   xt_44_ce0;
input  [31:0] xt_44_q0;
output  [4:0] xt_52_address0;
output   xt_52_ce0;
input  [31:0] xt_52_q0;
output  [4:0] xt_60_address0;
output   xt_60_ce0;
input  [31:0] xt_60_q0;
output  [4:0] xt_37_address0;
output   xt_37_ce0;
input  [31:0] xt_37_q0;
output  [4:0] xt_45_address0;
output   xt_45_ce0;
input  [31:0] xt_45_q0;
output  [4:0] xt_53_address0;
output   xt_53_ce0;
input  [31:0] xt_53_q0;
output  [4:0] xt_61_address0;
output   xt_61_ce0;
input  [31:0] xt_61_q0;
output  [4:0] xt_38_address0;
output   xt_38_ce0;
input  [31:0] xt_38_q0;
output  [4:0] xt_46_address0;
output   xt_46_ce0;
input  [31:0] xt_46_q0;
output  [4:0] xt_54_address0;
output   xt_54_ce0;
input  [31:0] xt_54_q0;
output  [4:0] xt_62_address0;
output   xt_62_ce0;
input  [31:0] xt_62_q0;
output  [31:0] sum_4_out;
output   sum_4_out_ap_vld;
output  [31:0] grp_fu_2042_p_din0;
output  [31:0] grp_fu_2042_p_din1;
output  [1:0] grp_fu_2042_p_opcode;
input  [31:0] grp_fu_2042_p_dout0;
output   grp_fu_2042_p_ce;
output  [31:0] grp_fu_2058_p_din0;
output  [31:0] grp_fu_2058_p_din1;
output  [1:0] grp_fu_2058_p_opcode;
input  [31:0] grp_fu_2058_p_dout0;
output   grp_fu_2058_p_ce;
output  [31:0] grp_fu_2062_p_din0;
output  [31:0] grp_fu_2062_p_din1;
output  [1:0] grp_fu_2062_p_opcode;
input  [31:0] grp_fu_2062_p_dout0;
output   grp_fu_2062_p_ce;
output  [31:0] grp_fu_2066_p_din0;
output  [31:0] grp_fu_2066_p_din1;
output  [1:0] grp_fu_2066_p_opcode;
input  [31:0] grp_fu_2066_p_dout0;
output   grp_fu_2066_p_ce;
output  [31:0] grp_fu_2070_p_din0;
output  [31:0] grp_fu_2070_p_din1;
output  [1:0] grp_fu_2070_p_opcode;
input  [31:0] grp_fu_2070_p_dout0;
output   grp_fu_2070_p_ce;
output  [31:0] grp_fu_2074_p_din0;
output  [31:0] grp_fu_2074_p_din1;
output  [1:0] grp_fu_2074_p_opcode;
input  [31:0] grp_fu_2074_p_dout0;
output   grp_fu_2074_p_ce;
output  [31:0] grp_fu_2054_p_din0;
output  [31:0] grp_fu_2054_p_din1;
input  [31:0] grp_fu_2054_p_dout0;
output   grp_fu_2054_p_ce;

reg ap_idle;
reg xt_ce0;
reg xt_39_ce0;
reg xt_47_ce0;
reg xt_55_ce0;
reg xt_32_ce0;
reg xt_40_ce0;
reg xt_48_ce0;
reg xt_56_ce0;
reg xt_33_ce0;
reg xt_41_ce0;
reg xt_49_ce0;
reg xt_57_ce0;
reg xt_34_ce0;
reg xt_42_ce0;
reg xt_50_ce0;
reg xt_58_ce0;
reg xt_35_ce0;
reg xt_43_ce0;
reg xt_51_ce0;
reg xt_59_ce0;
reg xt_36_ce0;
reg xt_44_ce0;
reg xt_52_ce0;
reg xt_60_ce0;
reg xt_37_ce0;
reg xt_45_ce0;
reg xt_53_ce0;
reg xt_61_ce0;
reg xt_38_ce0;
reg xt_46_ce0;
reg xt_54_ce0;
reg xt_62_ce0;
reg sum_4_out_ap_vld;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_state6_pp0_stage2_iter1;
wire    ap_block_state9_pp0_stage2_iter2;
wire    ap_block_state12_pp0_stage2_iter3;
wire    ap_block_state15_pp0_stage2_iter4;
wire    ap_block_state18_pp0_stage2_iter5;
wire    ap_block_state21_pp0_stage2_iter6;
wire    ap_block_state24_pp0_stage2_iter7;
wire    ap_block_state27_pp0_stage2_iter8;
wire    ap_block_state30_pp0_stage2_iter9;
wire    ap_block_state33_pp0_stage2_iter10;
wire    ap_block_state36_pp0_stage2_iter11;
wire    ap_block_pp0_stage2_subdone;
reg   [0:0] icmp_ln528_reg_1151;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_state7_pp0_stage0_iter2;
wire    ap_block_state10_pp0_stage0_iter3;
wire    ap_block_state13_pp0_stage0_iter4;
wire    ap_block_state16_pp0_stage0_iter5;
wire    ap_block_state19_pp0_stage0_iter6;
wire    ap_block_state22_pp0_stage0_iter7;
wire    ap_block_state25_pp0_stage0_iter8;
wire    ap_block_state28_pp0_stage0_iter9;
wire    ap_block_state31_pp0_stage0_iter10;
wire    ap_block_state34_pp0_stage0_iter11;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln528_fu_607_p2;
reg   [0:0] icmp_ln528_reg_1151_pp0_iter1_reg;
reg   [0:0] icmp_ln528_reg_1151_pp0_iter2_reg;
reg   [0:0] icmp_ln528_reg_1151_pp0_iter3_reg;
reg   [0:0] icmp_ln528_reg_1151_pp0_iter4_reg;
reg   [0:0] icmp_ln528_reg_1151_pp0_iter5_reg;
reg   [0:0] icmp_ln528_reg_1151_pp0_iter6_reg;
reg   [0:0] icmp_ln528_reg_1151_pp0_iter7_reg;
reg   [0:0] icmp_ln528_reg_1151_pp0_iter8_reg;
reg   [0:0] icmp_ln528_reg_1151_pp0_iter9_reg;
reg   [0:0] icmp_ln528_reg_1151_pp0_iter10_reg;
wire   [4:0] trunc_ln537_fu_659_p1;
reg   [4:0] trunc_ln537_reg_1175;
wire   [31:0] tmp_s_fu_674_p27;
reg   [31:0] tmp_s_reg_1327;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state5_pp0_stage1_iter1;
wire    ap_block_state8_pp0_stage1_iter2;
wire    ap_block_state11_pp0_stage1_iter3;
wire    ap_block_state14_pp0_stage1_iter4;
wire    ap_block_state17_pp0_stage1_iter5;
wire    ap_block_state20_pp0_stage1_iter6;
wire    ap_block_state23_pp0_stage1_iter7;
wire    ap_block_state26_pp0_stage1_iter8;
wire    ap_block_state29_pp0_stage1_iter9;
wire    ap_block_state32_pp0_stage1_iter10;
wire    ap_block_state35_pp0_stage1_iter11;
wire    ap_block_pp0_stage1_11001;
wire   [31:0] tmp_2_fu_729_p27;
reg   [31:0] tmp_2_reg_1332;
wire   [31:0] tmp_4_fu_784_p27;
reg   [31:0] tmp_4_reg_1337;
wire   [31:0] tmp_6_fu_839_p27;
reg   [31:0] tmp_6_reg_1342;
wire   [31:0] tmp_8_fu_894_p27;
reg   [31:0] tmp_8_reg_1347;
wire   [31:0] tmp_10_fu_949_p27;
reg   [31:0] tmp_10_reg_1352;
wire   [31:0] tmp_12_fu_1004_p27;
reg   [31:0] tmp_12_reg_1357;
wire   [31:0] tmp_14_fu_1059_p27;
reg   [31:0] tmp_14_reg_1362;
reg   [31:0] x_assign_3_reg_1367;
wire    ap_block_pp0_stage2_11001;
reg   [31:0] x_assign_4_reg_1372;
reg   [31:0] x_assign_5_reg_1377;
reg   [31:0] x_assign_6_reg_1382;
reg   [31:0] x_assign_7_reg_1387;
reg   [31:0] x_assign_8_reg_1392;
reg   [31:0] x_assign_9_reg_1397;
reg   [31:0] x_assign_s_reg_1402;
reg   [31:0] tmp_1_reg_1407;
wire   [31:0] grp_fu_584_p2;
reg   [31:0] tmp_3_reg_1412;
wire   [31:0] grp_fu_589_p2;
reg   [31:0] tmp_5_reg_1417;
reg   [31:0] tmp_7_reg_1422;
reg   [31:0] tmp_9_reg_1427;
reg   [31:0] tmp_11_reg_1432;
reg   [31:0] tmp_13_reg_1437;
reg   [31:0] tmp_15_reg_1442;
reg   [31:0] s0_reg_1447;
reg   [31:0] s1_reg_1452;
reg   [31:0] s2_reg_1457;
reg   [31:0] s3_reg_1462;
reg   [31:0] t0_reg_1467;
reg   [31:0] t0_reg_1467_pp0_iter8_reg;
reg   [31:0] t1_reg_1472;
reg   [31:0] block_reg_1477;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [63:0] zext_ln537_fu_623_p1;
wire    ap_block_pp0_stage0;
reg   [31:0] sum_fu_118;
reg   [31:0] ap_sig_allocacmp_sum_load;
wire    ap_block_pp0_stage2;
wire    ap_loop_init;
reg   [9:0] idx_fu_122;
wire   [9:0] add_ln528_fu_663_p2;
reg   [9:0] ap_sig_allocacmp_i;
wire    ap_block_pp0_stage2_01001;
reg   [31:0] grp_fu_555_p0;
reg   [31:0] grp_fu_555_p1;
wire    ap_block_pp0_stage1;
reg   [31:0] grp_fu_559_p0;
reg   [31:0] grp_fu_559_p1;
reg   [31:0] grp_fu_563_p0;
reg   [31:0] grp_fu_563_p1;
reg   [31:0] grp_fu_567_p0;
reg   [31:0] grp_fu_567_p1;
reg   [31:0] grp_fu_571_p0;
reg   [31:0] grp_fu_571_p1;
reg   [31:0] grp_fu_579_p1;
reg   [31:0] grp_fu_584_p1;
reg   [31:0] grp_fu_589_p1;
wire   [4:0] lshr_ln7_fu_613_p4;
reg   [1:0] grp_fu_555_opcode;
wire    ap_block_pp0_stage1_00001;
wire    ap_block_pp0_stage2_00001;
wire    ap_block_pp0_stage0_00001;
reg   [1:0] grp_fu_559_opcode;
reg   [1:0] grp_fu_563_opcode;
reg   [1:0] grp_fu_567_opcode;
reg   [1:0] grp_fu_571_opcode;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg   [2:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to11;
wire    ap_block_pp0_stage1_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

activation_accelerator_fexp_32ns_32ns_32_8_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fexp_32ns_32ns_32_8_full_dsp_1_U267(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(grp_fu_584_p1),
    .ce(1'b1),
    .dout(grp_fu_584_p2)
);

activation_accelerator_fexp_32ns_32ns_32_8_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fexp_32ns_32ns_32_8_full_dsp_1_U268(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(grp_fu_589_p1),
    .ce(1'b1),
    .dout(grp_fu_589_p2)
);

activation_accelerator_mux_255_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
mux_255_32_1_1_U269(
    .din0(xt_q0),
    .din1(32'd0),
    .din2(32'd0),
    .din3(32'd0),
    .din4(32'd0),
    .din5(32'd0),
    .din6(32'd0),
    .din7(32'd0),
    .din8(xt_39_q0),
    .din9(32'd0),
    .din10(32'd0),
    .din11(32'd0),
    .din12(32'd0),
    .din13(32'd0),
    .din14(32'd0),
    .din15(32'd0),
    .din16(xt_47_q0),
    .din17(32'd0),
    .din18(32'd0),
    .din19(32'd0),
    .din20(32'd0),
    .din21(32'd0),
    .din22(32'd0),
    .din23(32'd0),
    .din24(xt_55_q0),
    .din25(trunc_ln537_reg_1175),
    .dout(tmp_s_fu_674_p27)
);

activation_accelerator_mux_255_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
mux_255_32_1_1_U270(
    .din0(xt_32_q0),
    .din1(32'd0),
    .din2(32'd0),
    .din3(32'd0),
    .din4(32'd0),
    .din5(32'd0),
    .din6(32'd0),
    .din7(32'd0),
    .din8(xt_40_q0),
    .din9(32'd0),
    .din10(32'd0),
    .din11(32'd0),
    .din12(32'd0),
    .din13(32'd0),
    .din14(32'd0),
    .din15(32'd0),
    .din16(xt_48_q0),
    .din17(32'd0),
    .din18(32'd0),
    .din19(32'd0),
    .din20(32'd0),
    .din21(32'd0),
    .din22(32'd0),
    .din23(32'd0),
    .din24(xt_56_q0),
    .din25(trunc_ln537_reg_1175),
    .dout(tmp_2_fu_729_p27)
);

activation_accelerator_mux_255_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
mux_255_32_1_1_U271(
    .din0(xt_33_q0),
    .din1(32'd0),
    .din2(32'd0),
    .din3(32'd0),
    .din4(32'd0),
    .din5(32'd0),
    .din6(32'd0),
    .din7(32'd0),
    .din8(xt_41_q0),
    .din9(32'd0),
    .din10(32'd0),
    .din11(32'd0),
    .din12(32'd0),
    .din13(32'd0),
    .din14(32'd0),
    .din15(32'd0),
    .din16(xt_49_q0),
    .din17(32'd0),
    .din18(32'd0),
    .din19(32'd0),
    .din20(32'd0),
    .din21(32'd0),
    .din22(32'd0),
    .din23(32'd0),
    .din24(xt_57_q0),
    .din25(trunc_ln537_reg_1175),
    .dout(tmp_4_fu_784_p27)
);

activation_accelerator_mux_255_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
mux_255_32_1_1_U272(
    .din0(xt_34_q0),
    .din1(32'd0),
    .din2(32'd0),
    .din3(32'd0),
    .din4(32'd0),
    .din5(32'd0),
    .din6(32'd0),
    .din7(32'd0),
    .din8(xt_42_q0),
    .din9(32'd0),
    .din10(32'd0),
    .din11(32'd0),
    .din12(32'd0),
    .din13(32'd0),
    .din14(32'd0),
    .din15(32'd0),
    .din16(xt_50_q0),
    .din17(32'd0),
    .din18(32'd0),
    .din19(32'd0),
    .din20(32'd0),
    .din21(32'd0),
    .din22(32'd0),
    .din23(32'd0),
    .din24(xt_58_q0),
    .din25(trunc_ln537_reg_1175),
    .dout(tmp_6_fu_839_p27)
);

activation_accelerator_mux_255_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
mux_255_32_1_1_U273(
    .din0(xt_35_q0),
    .din1(32'd0),
    .din2(32'd0),
    .din3(32'd0),
    .din4(32'd0),
    .din5(32'd0),
    .din6(32'd0),
    .din7(32'd0),
    .din8(xt_43_q0),
    .din9(32'd0),
    .din10(32'd0),
    .din11(32'd0),
    .din12(32'd0),
    .din13(32'd0),
    .din14(32'd0),
    .din15(32'd0),
    .din16(xt_51_q0),
    .din17(32'd0),
    .din18(32'd0),
    .din19(32'd0),
    .din20(32'd0),
    .din21(32'd0),
    .din22(32'd0),
    .din23(32'd0),
    .din24(xt_59_q0),
    .din25(trunc_ln537_reg_1175),
    .dout(tmp_8_fu_894_p27)
);

activation_accelerator_mux_255_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
mux_255_32_1_1_U274(
    .din0(xt_36_q0),
    .din1(32'd0),
    .din2(32'd0),
    .din3(32'd0),
    .din4(32'd0),
    .din5(32'd0),
    .din6(32'd0),
    .din7(32'd0),
    .din8(xt_44_q0),
    .din9(32'd0),
    .din10(32'd0),
    .din11(32'd0),
    .din12(32'd0),
    .din13(32'd0),
    .din14(32'd0),
    .din15(32'd0),
    .din16(xt_52_q0),
    .din17(32'd0),
    .din18(32'd0),
    .din19(32'd0),
    .din20(32'd0),
    .din21(32'd0),
    .din22(32'd0),
    .din23(32'd0),
    .din24(xt_60_q0),
    .din25(trunc_ln537_reg_1175),
    .dout(tmp_10_fu_949_p27)
);

activation_accelerator_mux_255_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
mux_255_32_1_1_U275(
    .din0(xt_37_q0),
    .din1(32'd0),
    .din2(32'd0),
    .din3(32'd0),
    .din4(32'd0),
    .din5(32'd0),
    .din6(32'd0),
    .din7(32'd0),
    .din8(xt_45_q0),
    .din9(32'd0),
    .din10(32'd0),
    .din11(32'd0),
    .din12(32'd0),
    .din13(32'd0),
    .din14(32'd0),
    .din15(32'd0),
    .din16(xt_53_q0),
    .din17(32'd0),
    .din18(32'd0),
    .din19(32'd0),
    .din20(32'd0),
    .din21(32'd0),
    .din22(32'd0),
    .din23(32'd0),
    .din24(xt_61_q0),
    .din25(trunc_ln537_reg_1175),
    .dout(tmp_12_fu_1004_p27)
);

activation_accelerator_mux_255_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
mux_255_32_1_1_U276(
    .din0(xt_38_q0),
    .din1(32'd0),
    .din2(32'd0),
    .din3(32'd0),
    .din4(32'd0),
    .din5(32'd0),
    .din6(32'd0),
    .din7(32'd0),
    .din8(xt_46_q0),
    .din9(32'd0),
    .din10(32'd0),
    .din11(32'd0),
    .din12(32'd0),
    .din13(32'd0),
    .din14(32'd0),
    .din15(32'd0),
    .din16(xt_54_q0),
    .din17(32'd0),
    .din18(32'd0),
    .din19(32'd0),
    .din20(32'd0),
    .din21(32'd0),
    .din22(32'd0),
    .din23(32'd0),
    .din24(xt_62_q0),
    .din25(trunc_ln537_reg_1175),
    .dout(tmp_14_fu_1059_p27)
);

activation_accelerator_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter10_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage2)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln528_fu_607_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            idx_fu_122 <= add_ln528_fu_663_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            idx_fu_122 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sum_fu_118 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        sum_fu_118 <= grp_fu_2074_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        block_reg_1477 <= grp_fu_2070_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln528_reg_1151 <= icmp_ln528_fu_607_p2;
        icmp_ln528_reg_1151_pp0_iter10_reg <= icmp_ln528_reg_1151_pp0_iter9_reg;
        icmp_ln528_reg_1151_pp0_iter1_reg <= icmp_ln528_reg_1151;
        icmp_ln528_reg_1151_pp0_iter2_reg <= icmp_ln528_reg_1151_pp0_iter1_reg;
        icmp_ln528_reg_1151_pp0_iter3_reg <= icmp_ln528_reg_1151_pp0_iter2_reg;
        icmp_ln528_reg_1151_pp0_iter4_reg <= icmp_ln528_reg_1151_pp0_iter3_reg;
        icmp_ln528_reg_1151_pp0_iter5_reg <= icmp_ln528_reg_1151_pp0_iter4_reg;
        icmp_ln528_reg_1151_pp0_iter6_reg <= icmp_ln528_reg_1151_pp0_iter5_reg;
        icmp_ln528_reg_1151_pp0_iter7_reg <= icmp_ln528_reg_1151_pp0_iter6_reg;
        icmp_ln528_reg_1151_pp0_iter8_reg <= icmp_ln528_reg_1151_pp0_iter7_reg;
        icmp_ln528_reg_1151_pp0_iter9_reg <= icmp_ln528_reg_1151_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s0_reg_1447 <= grp_fu_2066_p_dout0;
        s1_reg_1452 <= grp_fu_2070_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        s2_reg_1457 <= grp_fu_2042_p_dout0;
        s3_reg_1462 <= grp_fu_2058_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        t0_reg_1467 <= grp_fu_2062_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        t0_reg_1467_pp0_iter8_reg <= t0_reg_1467;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        t1_reg_1472 <= grp_fu_2066_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln528_reg_1151 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_10_reg_1352 <= tmp_10_fu_949_p27;
        tmp_12_reg_1357 <= tmp_12_fu_1004_p27;
        tmp_14_reg_1362 <= tmp_14_fu_1059_p27;
        tmp_2_reg_1332 <= tmp_2_fu_729_p27;
        tmp_4_reg_1337 <= tmp_4_fu_784_p27;
        tmp_6_reg_1342 <= tmp_6_fu_839_p27;
        tmp_8_reg_1347 <= tmp_8_fu_894_p27;
        tmp_s_reg_1327 <= tmp_s_fu_674_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        tmp_11_reg_1432 <= grp_fu_589_p2;
        tmp_7_reg_1422 <= grp_fu_2054_p_dout0;
        tmp_9_reg_1427 <= grp_fu_584_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_13_reg_1437 <= grp_fu_2054_p_dout0;
        tmp_15_reg_1442 <= grp_fu_584_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_1_reg_1407 <= grp_fu_2054_p_dout0;
        tmp_3_reg_1412 <= grp_fu_584_p2;
        tmp_5_reg_1417 <= grp_fu_589_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln528_fu_607_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln537_reg_1175 <= trunc_ln537_fu_659_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        x_assign_3_reg_1367 <= grp_fu_2042_p_dout0;
        x_assign_4_reg_1372 <= grp_fu_2058_p_dout0;
        x_assign_5_reg_1377 <= grp_fu_2062_p_dout0;
        x_assign_6_reg_1382 <= grp_fu_2066_p_dout0;
        x_assign_7_reg_1387 <= grp_fu_2070_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_assign_8_reg_1392 <= grp_fu_2042_p_dout0;
        x_assign_9_reg_1397 <= grp_fu_2058_p_dout0;
        x_assign_s_reg_1402 <= grp_fu_2062_p_dout0;
    end
end

always @ (*) begin
    if (((icmp_ln528_reg_1151 == 1'd0) & (1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter10_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to11 = 1'b1;
    end else begin
        ap_idle_pp0_1to11 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i = 10'd0;
    end else begin
        ap_sig_allocacmp_i = idx_fu_122;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_sig_allocacmp_sum_load = grp_fu_2074_p_dout0;
    end else begin
        ap_sig_allocacmp_sum_load = sum_fu_118;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_00001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln528_reg_1151 == 1'd1) & (1'b0 == ap_block_pp0_stage2_00001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        grp_fu_555_opcode = 2'd1;
    end else if (((1'b0 == ap_block_pp0_stage1_00001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_555_opcode = 2'd0;
    end else begin
        grp_fu_555_opcode = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_555_p0 = tmp_9_reg_1427;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_555_p0 = tmp_10_reg_1352;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_555_p0 = tmp_s_reg_1327;
    end else begin
        grp_fu_555_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_555_p1 = tmp_11_reg_1432;
    end else if ((((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_555_p1 = xmax_3_reload;
    end else begin
        grp_fu_555_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_00001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln528_reg_1151 == 1'd1) & (1'b0 == ap_block_pp0_stage2_00001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        grp_fu_559_opcode = 2'd1;
    end else if (((1'b0 == ap_block_pp0_stage1_00001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_559_opcode = 2'd0;
    end else begin
        grp_fu_559_opcode = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_559_p0 = tmp_13_reg_1437;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_559_p0 = tmp_12_reg_1357;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_559_p0 = tmp_2_reg_1332;
    end else begin
        grp_fu_559_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_559_p1 = tmp_15_reg_1442;
    end else if ((((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_559_p1 = xmax_3_reload;
    end else begin
        grp_fu_559_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_00001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln528_reg_1151 == 1'd1) & (1'b0 == ap_block_pp0_stage2_00001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        grp_fu_563_opcode = 2'd1;
    end else if (((1'b0 == ap_block_pp0_stage1_00001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_563_opcode = 2'd0;
    end else begin
        grp_fu_563_opcode = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_563_p0 = s0_reg_1447;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_563_p0 = tmp_14_reg_1362;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_563_p0 = tmp_4_reg_1337;
    end else begin
        grp_fu_563_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_563_p1 = s1_reg_1452;
    end else if ((((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_563_p1 = xmax_3_reload;
    end else begin
        grp_fu_563_p1 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln528_reg_1151 == 1'd1) & (1'b0 == ap_block_pp0_stage2_00001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_567_opcode = 2'd1;
    end else if ((((1'b0 == ap_block_pp0_stage0_00001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_00001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_567_opcode = 2'd0;
    end else begin
        grp_fu_567_opcode = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_567_p0 = s2_reg_1457;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_567_p0 = tmp_1_reg_1407;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_567_p0 = tmp_6_reg_1342;
    end else begin
        grp_fu_567_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_567_p1 = s3_reg_1462;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_567_p1 = tmp_3_reg_1412;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_567_p1 = xmax_3_reload;
    end else begin
        grp_fu_567_p1 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln528_reg_1151 == 1'd1) & (1'b0 == ap_block_pp0_stage2_00001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_571_opcode = 2'd1;
    end else if ((((1'b0 == ap_block_pp0_stage0_00001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_00001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_571_opcode = 2'd0;
    end else begin
        grp_fu_571_opcode = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_571_p0 = t0_reg_1467_pp0_iter8_reg;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_571_p0 = tmp_5_reg_1417;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_571_p0 = tmp_8_reg_1347;
    end else begin
        grp_fu_571_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_571_p1 = t1_reg_1472;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_571_p1 = tmp_7_reg_1422;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_571_p1 = xmax_3_reload;
    end else begin
        grp_fu_571_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_579_p1 = x_assign_9_reg_1397;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_579_p1 = x_assign_6_reg_1382;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_579_p1 = x_assign_3_reg_1367;
        end else begin
            grp_fu_579_p1 = 'bx;
        end
    end else begin
        grp_fu_579_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_584_p1 = x_assign_s_reg_1402;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_584_p1 = x_assign_7_reg_1387;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_584_p1 = x_assign_4_reg_1372;
        end else begin
            grp_fu_584_p1 = 'bx;
        end
    end else begin
        grp_fu_584_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_589_p1 = x_assign_8_reg_1392;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_589_p1 = x_assign_5_reg_1377;
        end else begin
            grp_fu_589_p1 = 'bx;
        end
    end else begin
        grp_fu_589_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln528_reg_1151_pp0_iter10_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        sum_4_out_ap_vld = 1'b1;
    end else begin
        sum_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xt_32_ce0 = 1'b1;
    end else begin
        xt_32_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xt_33_ce0 = 1'b1;
    end else begin
        xt_33_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xt_34_ce0 = 1'b1;
    end else begin
        xt_34_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xt_35_ce0 = 1'b1;
    end else begin
        xt_35_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xt_36_ce0 = 1'b1;
    end else begin
        xt_36_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xt_37_ce0 = 1'b1;
    end else begin
        xt_37_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xt_38_ce0 = 1'b1;
    end else begin
        xt_38_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xt_39_ce0 = 1'b1;
    end else begin
        xt_39_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xt_40_ce0 = 1'b1;
    end else begin
        xt_40_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xt_41_ce0 = 1'b1;
    end else begin
        xt_41_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xt_42_ce0 = 1'b1;
    end else begin
        xt_42_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xt_43_ce0 = 1'b1;
    end else begin
        xt_43_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xt_44_ce0 = 1'b1;
    end else begin
        xt_44_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xt_45_ce0 = 1'b1;
    end else begin
        xt_45_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xt_46_ce0 = 1'b1;
    end else begin
        xt_46_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xt_47_ce0 = 1'b1;
    end else begin
        xt_47_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xt_48_ce0 = 1'b1;
    end else begin
        xt_48_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xt_49_ce0 = 1'b1;
    end else begin
        xt_49_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xt_50_ce0 = 1'b1;
    end else begin
        xt_50_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xt_51_ce0 = 1'b1;
    end else begin
        xt_51_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xt_52_ce0 = 1'b1;
    end else begin
        xt_52_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xt_53_ce0 = 1'b1;
    end else begin
        xt_53_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xt_54_ce0 = 1'b1;
    end else begin
        xt_54_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xt_55_ce0 = 1'b1;
    end else begin
        xt_55_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xt_56_ce0 = 1'b1;
    end else begin
        xt_56_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xt_57_ce0 = 1'b1;
    end else begin
        xt_57_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xt_58_ce0 = 1'b1;
    end else begin
        xt_58_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xt_59_ce0 = 1'b1;
    end else begin
        xt_59_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xt_60_ce0 = 1'b1;
    end else begin
        xt_60_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xt_61_ce0 = 1'b1;
    end else begin
        xt_61_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xt_62_ce0 = 1'b1;
    end else begin
        xt_62_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xt_ce0 = 1'b1;
    end else begin
        xt_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to11 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln528_fu_663_p2 = (ap_sig_allocacmp_i + 10'd8);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage2_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage1_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage2_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage1_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage2_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage1_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage2_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage1_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage2_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage1_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage2_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage1_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp0_stage2_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage1_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp0_stage2_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp0_stage1_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state36_pp0_stage2_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

assign grp_fu_2042_p_ce = 1'b1;

assign grp_fu_2042_p_din0 = grp_fu_555_p0;

assign grp_fu_2042_p_din1 = grp_fu_555_p1;

assign grp_fu_2042_p_opcode = grp_fu_555_opcode;

assign grp_fu_2054_p_ce = 1'b1;

assign grp_fu_2054_p_din0 = 32'd0;

assign grp_fu_2054_p_din1 = grp_fu_579_p1;

assign grp_fu_2058_p_ce = 1'b1;

assign grp_fu_2058_p_din0 = grp_fu_559_p0;

assign grp_fu_2058_p_din1 = grp_fu_559_p1;

assign grp_fu_2058_p_opcode = grp_fu_559_opcode;

assign grp_fu_2062_p_ce = 1'b1;

assign grp_fu_2062_p_din0 = grp_fu_563_p0;

assign grp_fu_2062_p_din1 = grp_fu_563_p1;

assign grp_fu_2062_p_opcode = grp_fu_563_opcode;

assign grp_fu_2066_p_ce = 1'b1;

assign grp_fu_2066_p_din0 = grp_fu_567_p0;

assign grp_fu_2066_p_din1 = grp_fu_567_p1;

assign grp_fu_2066_p_opcode = grp_fu_567_opcode;

assign grp_fu_2070_p_ce = 1'b1;

assign grp_fu_2070_p_din0 = grp_fu_571_p0;

assign grp_fu_2070_p_din1 = grp_fu_571_p1;

assign grp_fu_2070_p_opcode = grp_fu_571_opcode;

assign grp_fu_2074_p_ce = 1'b1;

assign grp_fu_2074_p_din0 = ap_sig_allocacmp_sum_load;

assign grp_fu_2074_p_din1 = block_reg_1477;

assign grp_fu_2074_p_opcode = 2'd0;

assign icmp_ln528_fu_607_p2 = ((ap_sig_allocacmp_i < 10'd768) ? 1'b1 : 1'b0);

assign lshr_ln7_fu_613_p4 = {{ap_sig_allocacmp_i[9:5]}};

assign sum_4_out = sum_fu_118;

assign trunc_ln537_fu_659_p1 = ap_sig_allocacmp_i[4:0];

assign xt_32_address0 = zext_ln537_fu_623_p1;

assign xt_33_address0 = zext_ln537_fu_623_p1;

assign xt_34_address0 = zext_ln537_fu_623_p1;

assign xt_35_address0 = zext_ln537_fu_623_p1;

assign xt_36_address0 = zext_ln537_fu_623_p1;

assign xt_37_address0 = zext_ln537_fu_623_p1;

assign xt_38_address0 = zext_ln537_fu_623_p1;

assign xt_39_address0 = zext_ln537_fu_623_p1;

assign xt_40_address0 = zext_ln537_fu_623_p1;

assign xt_41_address0 = zext_ln537_fu_623_p1;

assign xt_42_address0 = zext_ln537_fu_623_p1;

assign xt_43_address0 = zext_ln537_fu_623_p1;

assign xt_44_address0 = zext_ln537_fu_623_p1;

assign xt_45_address0 = zext_ln537_fu_623_p1;

assign xt_46_address0 = zext_ln537_fu_623_p1;

assign xt_47_address0 = zext_ln537_fu_623_p1;

assign xt_48_address0 = zext_ln537_fu_623_p1;

assign xt_49_address0 = zext_ln537_fu_623_p1;

assign xt_50_address0 = zext_ln537_fu_623_p1;

assign xt_51_address0 = zext_ln537_fu_623_p1;

assign xt_52_address0 = zext_ln537_fu_623_p1;

assign xt_53_address0 = zext_ln537_fu_623_p1;

assign xt_54_address0 = zext_ln537_fu_623_p1;

assign xt_55_address0 = zext_ln537_fu_623_p1;

assign xt_56_address0 = zext_ln537_fu_623_p1;

assign xt_57_address0 = zext_ln537_fu_623_p1;

assign xt_58_address0 = zext_ln537_fu_623_p1;

assign xt_59_address0 = zext_ln537_fu_623_p1;

assign xt_60_address0 = zext_ln537_fu_623_p1;

assign xt_61_address0 = zext_ln537_fu_623_p1;

assign xt_62_address0 = zext_ln537_fu_623_p1;

assign xt_address0 = zext_ln537_fu_623_p1;

assign zext_ln537_fu_623_p1 = lshr_ln7_fu_613_p4;

endmodule //activation_accelerator_compute_rows_Pipeline_smx_1
