set SynModuleInfo {
  {SRCNAME activation_accelerator_Pipeline_stage_2_store MODELNAME activation_accelerator_Pipeline_stage_2_store RTLNAME activation_accelerator_activation_accelerator_Pipeline_stage_2_store
    SUBMODULES {
      {MODELNAME activation_accelerator_sparsemux_129_6_16_1_1 RTLNAME activation_accelerator_sparsemux_129_6_16_1_1 BINDTYPE op TYPE sparsemux IMPL compactencoding_dontcare}
      {MODELNAME activation_accelerator_flow_control_loop_pipe_sequential_init RTLNAME activation_accelerator_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME activation_accelerator_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME activation_accelerator_Pipeline_gelu_blocks MODELNAME activation_accelerator_Pipeline_gelu_blocks RTLNAME activation_accelerator_activation_accelerator_Pipeline_gelu_blocks
    SUBMODULES {
      {MODELNAME activation_accelerator_fmul_32ns_32ns_32_3_max_dsp_1 RTLNAME activation_accelerator_fmul_32ns_32ns_32_3_max_dsp_1 BINDTYPE op TYPE fmul IMPL maxdsp LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_sparsemux_9_2_16_1_1 RTLNAME activation_accelerator_sparsemux_9_2_16_1_1 BINDTYPE op TYPE sparsemux IMPL compactencoding_dontcare}
    }
  }
  {SRCNAME round_float32_to_bf16_ieee MODELNAME round_float32_to_bf16_ieee RTLNAME activation_accelerator_round_float32_to_bf16_ieee}
  {SRCNAME activation_accelerator_Pipeline_add_blocks_add MODELNAME activation_accelerator_Pipeline_add_blocks_add RTLNAME activation_accelerator_activation_accelerator_Pipeline_add_blocks_add}
  {SRCNAME activation_accelerator_Pipeline_multiply_blocks_Multiply MODELNAME activation_accelerator_Pipeline_multiply_blocks_Multiply RTLNAME activation_accelerator_activation_accelerator_Pipeline_multiply_blocks_Multiply}
  {SRCNAME activation_accelerator_Pipeline_rms_sum_square MODELNAME activation_accelerator_Pipeline_rms_sum_square RTLNAME activation_accelerator_activation_accelerator_Pipeline_rms_sum_square}
  {SRCNAME activation_accelerator_Pipeline_rms_norm_normalize_blocks MODELNAME activation_accelerator_Pipeline_rms_norm_normalize_blocks RTLNAME activation_accelerator_activation_accelerator_Pipeline_rms_norm_normalize_blocks}
  {SRCNAME activation_accelerator_Pipeline_layernorm_sum_square MODELNAME activation_accelerator_Pipeline_layernorm_sum_square RTLNAME activation_accelerator_activation_accelerator_Pipeline_layernorm_sum_square}
  {SRCNAME activation_accelerator_Pipeline_layer_norm_std_blocks MODELNAME activation_accelerator_Pipeline_layer_norm_std_blocks RTLNAME activation_accelerator_activation_accelerator_Pipeline_layer_norm_std_blocks
    SUBMODULES {
      {MODELNAME activation_accelerator_sparsemux_129_6_32_1_1 RTLNAME activation_accelerator_sparsemux_129_6_32_1_1 BINDTYPE op TYPE sparsemux IMPL compactencoding_dontcare}
    }
  }
  {SRCNAME activation_accelerator_Pipeline_layer_norm_normalize_blocks MODELNAME activation_accelerator_Pipeline_layer_norm_normalize_blocks RTLNAME activation_accelerator_activation_accelerator_Pipeline_layer_norm_normalize_blocks}
  {SRCNAME bf16_fmax_u16 MODELNAME bf16_fmax_u16 RTLNAME activation_accelerator_bf16_fmax_u16}
  {SRCNAME activation_accelerator_Pipeline_softmax_max_step_loop MODELNAME activation_accelerator_Pipeline_softmax_max_step_loop RTLNAME activation_accelerator_activation_accelerator_Pipeline_softmax_max_step_loop}
  {SRCNAME activation_accelerator_Pipeline_softmax_exp_and_bucket_exp_inner_softmax MODELNAME activation_accelerator_Pipeline_softmax_exp_and_bucket_exp_inner_softmax RTLNAME activation_accelerator_activation_accelerator_Pipeline_softmax_exp_and_bucket_exp_inner_softmax}
  {SRCNAME activation_accelerator_Pipeline_softmax_final MODELNAME activation_accelerator_Pipeline_softmax_final RTLNAME activation_accelerator_activation_accelerator_Pipeline_softmax_final}
  {SRCNAME activation_accelerator_Pipeline_silu_blocks MODELNAME activation_accelerator_Pipeline_silu_blocks RTLNAME activation_accelerator_activation_accelerator_Pipeline_silu_blocks}
  {SRCNAME activation_accelerator_Pipeline_stage_0_load0 MODELNAME activation_accelerator_Pipeline_stage_0_load0 RTLNAME activation_accelerator_activation_accelerator_Pipeline_stage_0_load0}
  {SRCNAME activation_accelerator_Pipeline_stage_0_load1 MODELNAME activation_accelerator_Pipeline_stage_0_load1 RTLNAME activation_accelerator_activation_accelerator_Pipeline_stage_0_load1}
  {SRCNAME activation_accelerator MODELNAME activation_accelerator RTLNAME activation_accelerator IS_TOP 1
    SUBMODULES {
      {MODELNAME activation_accelerator_faddfsub_32ns_32ns_32_4_full_dsp_1 RTLNAME activation_accelerator_faddfsub_32ns_32ns_32_4_full_dsp_1 BINDTYPE op TYPE fadd IMPL fulldsp LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_fdiv_32ns_32ns_32_9_no_dsp_1 RTLNAME activation_accelerator_fdiv_32ns_32ns_32_9_no_dsp_1 BINDTYPE op TYPE fdiv IMPL fabric LATENCY 8 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_fsqrt_32ns_32ns_32_8_no_dsp_1 RTLNAME activation_accelerator_fsqrt_32ns_32ns_32_8_no_dsp_1 BINDTYPE op TYPE fsqrt IMPL fabric LATENCY 7 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_fadd_32ns_32ns_32_4_full_dsp_1 RTLNAME activation_accelerator_fadd_32ns_32ns_32_4_full_dsp_1 BINDTYPE op TYPE fadd IMPL fulldsp LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_fexp_32ns_32ns_32_8_full_dsp_1 RTLNAME activation_accelerator_fexp_32ns_32ns_32_8_full_dsp_1 BINDTYPE op TYPE fexp IMPL fulldsp LATENCY 7 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_29_bkb RTLNAME activation_accelerator_activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_29_bkb BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_19_lbW RTLNAME activation_accelerator_activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_19_lbW BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_gmem0_m_axi RTLNAME activation_accelerator_gmem0_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME activation_accelerator_gmem1_m_axi RTLNAME activation_accelerator_gmem1_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME activation_accelerator_gmem2_m_axi RTLNAME activation_accelerator_gmem2_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME activation_accelerator_control_s_axi RTLNAME activation_accelerator_control_s_axi BINDTYPE interface TYPE interface_s_axilite}
    }
  }
}
