-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity activation_accelerator_compute_rows_Pipeline_smx_0 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    xmax : IN STD_LOGIC_VECTOR (31 downto 0);
    xt_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    xt_ce0 : OUT STD_LOGIC;
    xt_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    xt_32_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    xt_32_ce0 : OUT STD_LOGIC;
    xt_32_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    xt_33_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    xt_33_ce0 : OUT STD_LOGIC;
    xt_33_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    xt_34_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    xt_34_ce0 : OUT STD_LOGIC;
    xt_34_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    xt_35_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    xt_35_ce0 : OUT STD_LOGIC;
    xt_35_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    xt_36_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    xt_36_ce0 : OUT STD_LOGIC;
    xt_36_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    xt_37_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    xt_37_ce0 : OUT STD_LOGIC;
    xt_37_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    xt_38_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    xt_38_ce0 : OUT STD_LOGIC;
    xt_38_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    xt_39_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    xt_39_ce0 : OUT STD_LOGIC;
    xt_39_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    xt_40_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    xt_40_ce0 : OUT STD_LOGIC;
    xt_40_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    xt_41_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    xt_41_ce0 : OUT STD_LOGIC;
    xt_41_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    xt_42_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    xt_42_ce0 : OUT STD_LOGIC;
    xt_42_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    xt_43_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    xt_43_ce0 : OUT STD_LOGIC;
    xt_43_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    xt_44_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    xt_44_ce0 : OUT STD_LOGIC;
    xt_44_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    xt_45_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    xt_45_ce0 : OUT STD_LOGIC;
    xt_45_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    xt_46_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    xt_46_ce0 : OUT STD_LOGIC;
    xt_46_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    xt_47_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    xt_47_ce0 : OUT STD_LOGIC;
    xt_47_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    xt_48_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    xt_48_ce0 : OUT STD_LOGIC;
    xt_48_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    xt_49_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    xt_49_ce0 : OUT STD_LOGIC;
    xt_49_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    xt_50_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    xt_50_ce0 : OUT STD_LOGIC;
    xt_50_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    xt_51_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    xt_51_ce0 : OUT STD_LOGIC;
    xt_51_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    xt_52_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    xt_52_ce0 : OUT STD_LOGIC;
    xt_52_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    xt_53_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    xt_53_ce0 : OUT STD_LOGIC;
    xt_53_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    xt_54_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    xt_54_ce0 : OUT STD_LOGIC;
    xt_54_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    xt_55_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    xt_55_ce0 : OUT STD_LOGIC;
    xt_55_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    xt_56_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    xt_56_ce0 : OUT STD_LOGIC;
    xt_56_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    xt_57_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    xt_57_ce0 : OUT STD_LOGIC;
    xt_57_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    xt_58_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    xt_58_ce0 : OUT STD_LOGIC;
    xt_58_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    xt_59_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    xt_59_ce0 : OUT STD_LOGIC;
    xt_59_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    xt_60_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    xt_60_ce0 : OUT STD_LOGIC;
    xt_60_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    xt_61_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    xt_61_ce0 : OUT STD_LOGIC;
    xt_61_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    xt_62_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    xt_62_ce0 : OUT STD_LOGIC;
    xt_62_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    xmax_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    xmax_3_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of activation_accelerator_compute_rows_Pipeline_smx_0 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv10_300 : STD_LOGIC_VECTOR (9 downto 0) := "1100000000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln572_fu_584_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln574_fu_636_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln574_reg_1178 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln574_fu_600_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal xmax_3_fu_134 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_5_fu_983_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal i_fu_138 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln572_fu_640_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_sig_allocacmp_i_5 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal lshr_ln6_fu_590_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal data_V_fu_723_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal dc_fu_654_p34 : STD_LOGIC_VECTOR (31 downto 0);
    signal data_V_1_fu_749_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal y_fp_exp_V_fu_761_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal x_fp_exp_V_fu_735_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln25_fu_775_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal y_fp_sig_V_fu_771_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal x_fp_sig_V_fu_745_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal or_ln25_1_fu_787_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln25_1_fu_793_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_fu_781_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1019_fu_805_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1023_fu_817_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1019_1_fu_811_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1023_1_fu_829_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_fu_727_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_2_fu_841_p4 : STD_LOGIC_VECTOR (22 downto 0);
    signal p_Result_3_fu_851_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ymaggreater_fu_865_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln39_fu_871_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_1_fu_753_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln39_fu_877_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ymaggreater_1_fu_885_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln25_1_fu_901_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_fu_823_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_1_fu_835_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_2_fu_913_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln25_fu_907_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_3_fu_919_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_fu_861_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_1_fu_893_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln18_4_fu_933_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln18_fu_939_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln25_fu_799_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_5_fu_945_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln18_fu_951_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_2_fu_925_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln18_1_fu_965_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln18_1_fu_971_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_6_fu_977_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_3_fu_957_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component activation_accelerator_mux_325_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        din9_WIDTH : INTEGER;
        din10_WIDTH : INTEGER;
        din11_WIDTH : INTEGER;
        din12_WIDTH : INTEGER;
        din13_WIDTH : INTEGER;
        din14_WIDTH : INTEGER;
        din15_WIDTH : INTEGER;
        din16_WIDTH : INTEGER;
        din17_WIDTH : INTEGER;
        din18_WIDTH : INTEGER;
        din19_WIDTH : INTEGER;
        din20_WIDTH : INTEGER;
        din21_WIDTH : INTEGER;
        din22_WIDTH : INTEGER;
        din23_WIDTH : INTEGER;
        din24_WIDTH : INTEGER;
        din25_WIDTH : INTEGER;
        din26_WIDTH : INTEGER;
        din27_WIDTH : INTEGER;
        din28_WIDTH : INTEGER;
        din29_WIDTH : INTEGER;
        din30_WIDTH : INTEGER;
        din31_WIDTH : INTEGER;
        din32_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        din8 : IN STD_LOGIC_VECTOR (31 downto 0);
        din9 : IN STD_LOGIC_VECTOR (31 downto 0);
        din10 : IN STD_LOGIC_VECTOR (31 downto 0);
        din11 : IN STD_LOGIC_VECTOR (31 downto 0);
        din12 : IN STD_LOGIC_VECTOR (31 downto 0);
        din13 : IN STD_LOGIC_VECTOR (31 downto 0);
        din14 : IN STD_LOGIC_VECTOR (31 downto 0);
        din15 : IN STD_LOGIC_VECTOR (31 downto 0);
        din16 : IN STD_LOGIC_VECTOR (31 downto 0);
        din17 : IN STD_LOGIC_VECTOR (31 downto 0);
        din18 : IN STD_LOGIC_VECTOR (31 downto 0);
        din19 : IN STD_LOGIC_VECTOR (31 downto 0);
        din20 : IN STD_LOGIC_VECTOR (31 downto 0);
        din21 : IN STD_LOGIC_VECTOR (31 downto 0);
        din22 : IN STD_LOGIC_VECTOR (31 downto 0);
        din23 : IN STD_LOGIC_VECTOR (31 downto 0);
        din24 : IN STD_LOGIC_VECTOR (31 downto 0);
        din25 : IN STD_LOGIC_VECTOR (31 downto 0);
        din26 : IN STD_LOGIC_VECTOR (31 downto 0);
        din27 : IN STD_LOGIC_VECTOR (31 downto 0);
        din28 : IN STD_LOGIC_VECTOR (31 downto 0);
        din29 : IN STD_LOGIC_VECTOR (31 downto 0);
        din30 : IN STD_LOGIC_VECTOR (31 downto 0);
        din31 : IN STD_LOGIC_VECTOR (31 downto 0);
        din32 : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component activation_accelerator_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mux_325_32_1_1_U225 : component activation_accelerator_mux_325_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 32,
        din6_WIDTH => 32,
        din7_WIDTH => 32,
        din8_WIDTH => 32,
        din9_WIDTH => 32,
        din10_WIDTH => 32,
        din11_WIDTH => 32,
        din12_WIDTH => 32,
        din13_WIDTH => 32,
        din14_WIDTH => 32,
        din15_WIDTH => 32,
        din16_WIDTH => 32,
        din17_WIDTH => 32,
        din18_WIDTH => 32,
        din19_WIDTH => 32,
        din20_WIDTH => 32,
        din21_WIDTH => 32,
        din22_WIDTH => 32,
        din23_WIDTH => 32,
        din24_WIDTH => 32,
        din25_WIDTH => 32,
        din26_WIDTH => 32,
        din27_WIDTH => 32,
        din28_WIDTH => 32,
        din29_WIDTH => 32,
        din30_WIDTH => 32,
        din31_WIDTH => 32,
        din32_WIDTH => 5,
        dout_WIDTH => 32)
    port map (
        din0 => xt_q0,
        din1 => xt_32_q0,
        din2 => xt_33_q0,
        din3 => xt_34_q0,
        din4 => xt_35_q0,
        din5 => xt_36_q0,
        din6 => xt_37_q0,
        din7 => xt_38_q0,
        din8 => xt_39_q0,
        din9 => xt_40_q0,
        din10 => xt_41_q0,
        din11 => xt_42_q0,
        din12 => xt_43_q0,
        din13 => xt_44_q0,
        din14 => xt_45_q0,
        din15 => xt_46_q0,
        din16 => xt_47_q0,
        din17 => xt_48_q0,
        din18 => xt_49_q0,
        din19 => xt_50_q0,
        din20 => xt_51_q0,
        din21 => xt_52_q0,
        din22 => xt_53_q0,
        din23 => xt_54_q0,
        din24 => xt_55_q0,
        din25 => xt_56_q0,
        din26 => xt_57_q0,
        din27 => xt_58_q0,
        din28 => xt_59_q0,
        din29 => xt_60_q0,
        din30 => xt_61_q0,
        din31 => xt_62_q0,
        din32 => trunc_ln574_reg_1178,
        dout => dc_fu_654_p34);

    flow_control_loop_pipe_sequential_init_U : component activation_accelerator_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    i_fu_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln572_fu_584_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_138 <= add_ln572_fu_640_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_138 <= ap_const_lv10_1;
                end if;
            end if; 
        end if;
    end process;

    xmax_3_fu_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    xmax_3_fu_134 <= xmax;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    xmax_3_fu_134 <= res_5_fu_983_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln572_fu_584_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                trunc_ln574_reg_1178 <= trunc_ln574_fu_636_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln572_fu_640_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_5) + unsigned(ap_const_lv10_1));
    and_ln18_1_fu_835_p2 <= (icmp_ln1023_1_fu_829_p2 and icmp_ln1019_1_fu_811_p2);
    and_ln18_2_fu_913_p2 <= (and_ln18_fu_823_p2 and and_ln18_1_fu_835_p2);
    and_ln18_3_fu_919_p2 <= (xor_ln25_fu_907_p2 and and_ln18_2_fu_913_p2);
    and_ln18_4_fu_933_p2 <= (icmp_ln1023_1_fu_829_p2 and icmp_ln1019_1_fu_811_p2);
    and_ln18_5_fu_945_p2 <= (xor_ln18_fu_939_p2 and and_ln18_fu_823_p2);
    and_ln18_6_fu_977_p2 <= (xor_ln18_1_fu_971_p2 and and_ln18_1_fu_835_p2);
    and_ln18_fu_823_p2 <= (icmp_ln1023_fu_817_p2 and icmp_ln1019_fu_805_p2);
    and_ln25_1_fu_901_p2 <= (icmp_ln25_fu_781_p2 and icmp_ln25_1_fu_793_p2);
    and_ln25_fu_799_p2 <= (icmp_ln25_fu_781_p2 and icmp_ln25_1_fu_793_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln572_fu_584_p2)
    begin
        if (((icmp_ln572_fu_584_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_5_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_fu_138)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_5 <= ap_const_lv10_1;
        else 
            ap_sig_allocacmp_i_5 <= i_fu_138;
        end if; 
    end process;

    data_V_1_fu_749_p1 <= dc_fu_654_p34;
    data_V_fu_723_p1 <= xmax_3_fu_134;
    icmp_ln1019_1_fu_811_p2 <= "1" when (y_fp_exp_V_fu_761_p4 = ap_const_lv8_FF) else "0";
    icmp_ln1019_fu_805_p2 <= "1" when (x_fp_exp_V_fu_735_p4 = ap_const_lv8_FF) else "0";
    icmp_ln1023_1_fu_829_p2 <= "0" when (y_fp_sig_V_fu_771_p1 = ap_const_lv23_0) else "1";
    icmp_ln1023_fu_817_p2 <= "0" when (x_fp_sig_V_fu_745_p1 = ap_const_lv23_0) else "1";
    icmp_ln25_1_fu_793_p2 <= "1" when (or_ln25_1_fu_787_p2 = ap_const_lv23_0) else "0";
    icmp_ln25_fu_781_p2 <= "1" when (or_ln25_fu_775_p2 = ap_const_lv8_0) else "0";
    icmp_ln572_fu_584_p2 <= "1" when (ap_sig_allocacmp_i_5 = ap_const_lv10_300) else "0";
    lshr_ln6_fu_590_p4 <= ap_sig_allocacmp_i_5(9 downto 5);
    or_ln18_1_fu_965_p2 <= (and_ln25_fu_799_p2 or and_ln18_fu_823_p2);
    or_ln18_fu_951_p2 <= (and_ln25_fu_799_p2 or and_ln18_5_fu_945_p2);
    or_ln25_1_fu_787_p2 <= (y_fp_sig_V_fu_771_p1 or x_fp_sig_V_fu_745_p1);
    or_ln25_fu_775_p2 <= (y_fp_exp_V_fu_761_p4 or x_fp_exp_V_fu_735_p4);
    p_Result_1_fu_753_p3 <= data_V_1_fu_749_p1(31 downto 31);
    
    p_Result_2_fu_841_p4_proc : process(x_fp_sig_V_fu_745_p1)
    begin
        p_Result_2_fu_841_p4 <= x_fp_sig_V_fu_745_p1;
        p_Result_2_fu_841_p4(22) <= ap_const_lv1_1(0);
    end process;

    p_Result_3_fu_851_p4 <= ((p_Result_s_fu_727_p3 & ap_const_lv8_FF) & p_Result_2_fu_841_p4);
    p_Result_s_fu_727_p3 <= data_V_fu_723_p1(31 downto 31);
    res_1_fu_893_p3 <= 
        dc_fu_654_p34 when (ymaggreater_1_fu_885_p3(0) = '1') else 
        xmax_3_fu_134;
    res_2_fu_925_p3 <= 
        res_fu_861_p1 when (and_ln18_3_fu_919_p2(0) = '1') else 
        res_1_fu_893_p3;
    res_3_fu_957_p3 <= 
        dc_fu_654_p34 when (or_ln18_fu_951_p2(0) = '1') else 
        res_2_fu_925_p3;
    res_5_fu_983_p3 <= 
        xmax_3_fu_134 when (and_ln18_6_fu_977_p2(0) = '1') else 
        res_3_fu_957_p3;
    res_fu_861_p1 <= p_Result_3_fu_851_p4;
    select_ln39_fu_877_p3 <= 
        xor_ln39_fu_871_p2 when (p_Result_s_fu_727_p3(0) = '1') else 
        ymaggreater_fu_865_p2;
    trunc_ln574_fu_636_p1 <= ap_sig_allocacmp_i_5(5 - 1 downto 0);
    x_fp_exp_V_fu_735_p4 <= data_V_fu_723_p1(30 downto 23);
    x_fp_sig_V_fu_745_p1 <= data_V_fu_723_p1(23 - 1 downto 0);
    xmax_3_out <= xmax_3_fu_134;

    xmax_3_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln572_fu_584_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln572_fu_584_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xmax_3_out_ap_vld <= ap_const_logic_1;
        else 
            xmax_3_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln18_1_fu_971_p2 <= (or_ln18_1_fu_965_p2 xor ap_const_lv1_1);
    xor_ln18_fu_939_p2 <= (ap_const_lv1_1 xor and_ln18_4_fu_933_p2);
    xor_ln25_fu_907_p2 <= (ap_const_lv1_1 xor and_ln25_1_fu_901_p2);
    xor_ln39_fu_871_p2 <= (ymaggreater_fu_865_p2 xor ap_const_lv1_1);
    xt_32_address0 <= zext_ln574_fu_600_p1(5 - 1 downto 0);

    xt_32_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xt_32_ce0 <= ap_const_logic_1;
        else 
            xt_32_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xt_33_address0 <= zext_ln574_fu_600_p1(5 - 1 downto 0);

    xt_33_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xt_33_ce0 <= ap_const_logic_1;
        else 
            xt_33_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xt_34_address0 <= zext_ln574_fu_600_p1(5 - 1 downto 0);

    xt_34_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xt_34_ce0 <= ap_const_logic_1;
        else 
            xt_34_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xt_35_address0 <= zext_ln574_fu_600_p1(5 - 1 downto 0);

    xt_35_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xt_35_ce0 <= ap_const_logic_1;
        else 
            xt_35_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xt_36_address0 <= zext_ln574_fu_600_p1(5 - 1 downto 0);

    xt_36_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xt_36_ce0 <= ap_const_logic_1;
        else 
            xt_36_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xt_37_address0 <= zext_ln574_fu_600_p1(5 - 1 downto 0);

    xt_37_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xt_37_ce0 <= ap_const_logic_1;
        else 
            xt_37_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xt_38_address0 <= zext_ln574_fu_600_p1(5 - 1 downto 0);

    xt_38_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xt_38_ce0 <= ap_const_logic_1;
        else 
            xt_38_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xt_39_address0 <= zext_ln574_fu_600_p1(5 - 1 downto 0);

    xt_39_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xt_39_ce0 <= ap_const_logic_1;
        else 
            xt_39_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xt_40_address0 <= zext_ln574_fu_600_p1(5 - 1 downto 0);

    xt_40_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xt_40_ce0 <= ap_const_logic_1;
        else 
            xt_40_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xt_41_address0 <= zext_ln574_fu_600_p1(5 - 1 downto 0);

    xt_41_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xt_41_ce0 <= ap_const_logic_1;
        else 
            xt_41_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xt_42_address0 <= zext_ln574_fu_600_p1(5 - 1 downto 0);

    xt_42_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xt_42_ce0 <= ap_const_logic_1;
        else 
            xt_42_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xt_43_address0 <= zext_ln574_fu_600_p1(5 - 1 downto 0);

    xt_43_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xt_43_ce0 <= ap_const_logic_1;
        else 
            xt_43_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xt_44_address0 <= zext_ln574_fu_600_p1(5 - 1 downto 0);

    xt_44_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xt_44_ce0 <= ap_const_logic_1;
        else 
            xt_44_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xt_45_address0 <= zext_ln574_fu_600_p1(5 - 1 downto 0);

    xt_45_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xt_45_ce0 <= ap_const_logic_1;
        else 
            xt_45_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xt_46_address0 <= zext_ln574_fu_600_p1(5 - 1 downto 0);

    xt_46_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xt_46_ce0 <= ap_const_logic_1;
        else 
            xt_46_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xt_47_address0 <= zext_ln574_fu_600_p1(5 - 1 downto 0);

    xt_47_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xt_47_ce0 <= ap_const_logic_1;
        else 
            xt_47_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xt_48_address0 <= zext_ln574_fu_600_p1(5 - 1 downto 0);

    xt_48_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xt_48_ce0 <= ap_const_logic_1;
        else 
            xt_48_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xt_49_address0 <= zext_ln574_fu_600_p1(5 - 1 downto 0);

    xt_49_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xt_49_ce0 <= ap_const_logic_1;
        else 
            xt_49_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xt_50_address0 <= zext_ln574_fu_600_p1(5 - 1 downto 0);

    xt_50_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xt_50_ce0 <= ap_const_logic_1;
        else 
            xt_50_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xt_51_address0 <= zext_ln574_fu_600_p1(5 - 1 downto 0);

    xt_51_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xt_51_ce0 <= ap_const_logic_1;
        else 
            xt_51_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xt_52_address0 <= zext_ln574_fu_600_p1(5 - 1 downto 0);

    xt_52_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xt_52_ce0 <= ap_const_logic_1;
        else 
            xt_52_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xt_53_address0 <= zext_ln574_fu_600_p1(5 - 1 downto 0);

    xt_53_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xt_53_ce0 <= ap_const_logic_1;
        else 
            xt_53_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xt_54_address0 <= zext_ln574_fu_600_p1(5 - 1 downto 0);

    xt_54_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xt_54_ce0 <= ap_const_logic_1;
        else 
            xt_54_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xt_55_address0 <= zext_ln574_fu_600_p1(5 - 1 downto 0);

    xt_55_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xt_55_ce0 <= ap_const_logic_1;
        else 
            xt_55_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xt_56_address0 <= zext_ln574_fu_600_p1(5 - 1 downto 0);

    xt_56_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xt_56_ce0 <= ap_const_logic_1;
        else 
            xt_56_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xt_57_address0 <= zext_ln574_fu_600_p1(5 - 1 downto 0);

    xt_57_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xt_57_ce0 <= ap_const_logic_1;
        else 
            xt_57_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xt_58_address0 <= zext_ln574_fu_600_p1(5 - 1 downto 0);

    xt_58_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xt_58_ce0 <= ap_const_logic_1;
        else 
            xt_58_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xt_59_address0 <= zext_ln574_fu_600_p1(5 - 1 downto 0);

    xt_59_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xt_59_ce0 <= ap_const_logic_1;
        else 
            xt_59_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xt_60_address0 <= zext_ln574_fu_600_p1(5 - 1 downto 0);

    xt_60_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xt_60_ce0 <= ap_const_logic_1;
        else 
            xt_60_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xt_61_address0 <= zext_ln574_fu_600_p1(5 - 1 downto 0);

    xt_61_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xt_61_ce0 <= ap_const_logic_1;
        else 
            xt_61_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xt_62_address0 <= zext_ln574_fu_600_p1(5 - 1 downto 0);

    xt_62_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xt_62_ce0 <= ap_const_logic_1;
        else 
            xt_62_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xt_address0 <= zext_ln574_fu_600_p1(5 - 1 downto 0);

    xt_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xt_ce0 <= ap_const_logic_1;
        else 
            xt_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    y_fp_exp_V_fu_761_p4 <= data_V_1_fu_749_p1(30 downto 23);
    y_fp_sig_V_fu_771_p1 <= data_V_1_fu_749_p1(23 - 1 downto 0);
    ymaggreater_1_fu_885_p3 <= 
        select_ln39_fu_877_p3 when (p_Result_1_fu_753_p3(0) = '1') else 
        ymaggreater_fu_865_p2;
    ymaggreater_fu_865_p2 <= "1" when (signed(data_V_fu_723_p1) < signed(data_V_1_fu_749_p1)) else "0";
    zext_ln574_fu_600_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln6_fu_590_p4),64));
end behav;
