// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module activation_accelerator_load_rows (
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        in0,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RFIFONUM,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        in1,
        s_in01_din,
        s_in01_full_n,
        s_in01_write,
        s_in12_din,
        s_in12_full_n,
        s_in12_write,
        ap_clk,
        ap_rst,
        in0_ap_vld,
        in1_ap_vld,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [63:0] m_axi_gmem0_AWADDR;
output  [0:0] m_axi_gmem0_AWID;
output  [31:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [0:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [511:0] m_axi_gmem0_WDATA;
output  [63:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [0:0] m_axi_gmem0_WID;
output  [0:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [63:0] m_axi_gmem0_ARADDR;
output  [0:0] m_axi_gmem0_ARID;
output  [31:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [0:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [511:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [0:0] m_axi_gmem0_RID;
input  [9:0] m_axi_gmem0_RFIFONUM;
input  [0:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [0:0] m_axi_gmem0_BID;
input  [0:0] m_axi_gmem0_BUSER;
input  [63:0] in0;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [63:0] m_axi_gmem1_AWADDR;
output  [0:0] m_axi_gmem1_AWID;
output  [31:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [0:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [511:0] m_axi_gmem1_WDATA;
output  [63:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [0:0] m_axi_gmem1_WID;
output  [0:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [63:0] m_axi_gmem1_ARADDR;
output  [0:0] m_axi_gmem1_ARID;
output  [31:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [0:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [511:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [0:0] m_axi_gmem1_RID;
input  [9:0] m_axi_gmem1_RFIFONUM;
input  [0:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [0:0] m_axi_gmem1_BID;
input  [0:0] m_axi_gmem1_BUSER;
input  [63:0] in1;
output  [511:0] s_in01_din;
input   s_in01_full_n;
output   s_in01_write;
output  [511:0] s_in12_din;
input   s_in12_full_n;
output   s_in12_write;
input   ap_clk;
input   ap_rst;
input   in0_ap_vld;
input   in1_ap_vld;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    load_rows_Loop_LOAD_ROW_proc1_U0_ap_start;
wire    load_rows_Loop_LOAD_ROW_proc1_U0_ap_done;
wire    load_rows_Loop_LOAD_ROW_proc1_U0_ap_continue;
wire    load_rows_Loop_LOAD_ROW_proc1_U0_ap_idle;
wire    load_rows_Loop_LOAD_ROW_proc1_U0_ap_ready;
wire    load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_AWVALID;
wire   [63:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_AWADDR;
wire   [0:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_AWID;
wire   [31:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_AWLEN;
wire   [2:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_AWSIZE;
wire   [1:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_AWBURST;
wire   [1:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_AWLOCK;
wire   [3:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_AWCACHE;
wire   [2:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_AWPROT;
wire   [3:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_AWQOS;
wire   [3:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_AWREGION;
wire   [0:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_AWUSER;
wire    load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_WVALID;
wire   [511:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_WDATA;
wire   [63:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_WSTRB;
wire    load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_WLAST;
wire   [0:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_WID;
wire   [0:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_WUSER;
wire    load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARVALID;
wire   [63:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARADDR;
wire   [0:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARID;
wire   [31:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARLEN;
wire   [2:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARSIZE;
wire   [1:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARBURST;
wire   [1:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARLOCK;
wire   [3:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARCACHE;
wire   [2:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARPROT;
wire   [3:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARQOS;
wire   [3:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARREGION;
wire   [0:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARUSER;
wire    load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_RREADY;
wire    load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_BREADY;
wire    load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_AWVALID;
wire   [63:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_AWADDR;
wire   [0:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_AWID;
wire   [31:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_AWLEN;
wire   [2:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_AWSIZE;
wire   [1:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_AWBURST;
wire   [1:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_AWLOCK;
wire   [3:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_AWCACHE;
wire   [2:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_AWPROT;
wire   [3:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_AWQOS;
wire   [3:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_AWREGION;
wire   [0:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_AWUSER;
wire    load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_WVALID;
wire   [511:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_WDATA;
wire   [63:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_WSTRB;
wire    load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_WLAST;
wire   [0:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_WID;
wire   [0:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_WUSER;
wire    load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARVALID;
wire   [63:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARADDR;
wire   [0:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARID;
wire   [31:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARLEN;
wire   [2:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARSIZE;
wire   [1:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARBURST;
wire   [1:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARLOCK;
wire   [3:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARCACHE;
wire   [2:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARPROT;
wire   [3:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARQOS;
wire   [3:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARREGION;
wire   [0:0] load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARUSER;
wire    load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_RREADY;
wire    load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_BREADY;
wire   [511:0] load_rows_Loop_LOAD_ROW_proc1_U0_s_in01_din;
wire    load_rows_Loop_LOAD_ROW_proc1_U0_s_in01_write;
wire   [511:0] load_rows_Loop_LOAD_ROW_proc1_U0_s_in12_din;
wire    load_rows_Loop_LOAD_ROW_proc1_U0_s_in12_write;

activation_accelerator_load_rows_Loop_LOAD_ROW_proc1 load_rows_Loop_LOAD_ROW_proc1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(load_rows_Loop_LOAD_ROW_proc1_U0_ap_start),
    .ap_done(load_rows_Loop_LOAD_ROW_proc1_U0_ap_done),
    .ap_continue(load_rows_Loop_LOAD_ROW_proc1_U0_ap_continue),
    .ap_idle(load_rows_Loop_LOAD_ROW_proc1_U0_ap_idle),
    .ap_ready(load_rows_Loop_LOAD_ROW_proc1_U0_ap_ready),
    .in0(in0),
    .m_axi_gmem0_AWVALID(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_AWVALID),
    .m_axi_gmem0_AWREADY(1'b0),
    .m_axi_gmem0_AWADDR(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_AWADDR),
    .m_axi_gmem0_AWID(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_AWID),
    .m_axi_gmem0_AWLEN(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_AWLEN),
    .m_axi_gmem0_AWSIZE(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_AWSIZE),
    .m_axi_gmem0_AWBURST(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_AWBURST),
    .m_axi_gmem0_AWLOCK(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_AWLOCK),
    .m_axi_gmem0_AWCACHE(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_AWCACHE),
    .m_axi_gmem0_AWPROT(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_AWPROT),
    .m_axi_gmem0_AWQOS(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_AWQOS),
    .m_axi_gmem0_AWREGION(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_AWREGION),
    .m_axi_gmem0_AWUSER(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_AWUSER),
    .m_axi_gmem0_WVALID(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_WVALID),
    .m_axi_gmem0_WREADY(1'b0),
    .m_axi_gmem0_WDATA(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_WDATA),
    .m_axi_gmem0_WSTRB(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_WSTRB),
    .m_axi_gmem0_WLAST(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_WLAST),
    .m_axi_gmem0_WID(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_WID),
    .m_axi_gmem0_WUSER(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_WUSER),
    .m_axi_gmem0_ARVALID(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARVALID),
    .m_axi_gmem0_ARREADY(m_axi_gmem0_ARREADY),
    .m_axi_gmem0_ARADDR(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARADDR),
    .m_axi_gmem0_ARID(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARID),
    .m_axi_gmem0_ARLEN(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARLEN),
    .m_axi_gmem0_ARSIZE(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARSIZE),
    .m_axi_gmem0_ARBURST(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARBURST),
    .m_axi_gmem0_ARLOCK(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARLOCK),
    .m_axi_gmem0_ARCACHE(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARCACHE),
    .m_axi_gmem0_ARPROT(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARPROT),
    .m_axi_gmem0_ARQOS(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARQOS),
    .m_axi_gmem0_ARREGION(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARREGION),
    .m_axi_gmem0_ARUSER(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARUSER),
    .m_axi_gmem0_RVALID(m_axi_gmem0_RVALID),
    .m_axi_gmem0_RREADY(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_RREADY),
    .m_axi_gmem0_RDATA(m_axi_gmem0_RDATA),
    .m_axi_gmem0_RLAST(m_axi_gmem0_RLAST),
    .m_axi_gmem0_RID(m_axi_gmem0_RID),
    .m_axi_gmem0_RFIFONUM(m_axi_gmem0_RFIFONUM),
    .m_axi_gmem0_RUSER(m_axi_gmem0_RUSER),
    .m_axi_gmem0_RRESP(m_axi_gmem0_RRESP),
    .m_axi_gmem0_BVALID(1'b0),
    .m_axi_gmem0_BREADY(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_BREADY),
    .m_axi_gmem0_BRESP(2'd0),
    .m_axi_gmem0_BID(1'd0),
    .m_axi_gmem0_BUSER(1'd0),
    .in1(in1),
    .m_axi_gmem1_AWVALID(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_AWVALID),
    .m_axi_gmem1_AWREADY(1'b0),
    .m_axi_gmem1_AWADDR(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_AWADDR),
    .m_axi_gmem1_AWID(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_AWID),
    .m_axi_gmem1_AWLEN(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_AWLEN),
    .m_axi_gmem1_AWSIZE(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_AWSIZE),
    .m_axi_gmem1_AWBURST(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_AWBURST),
    .m_axi_gmem1_AWLOCK(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_AWLOCK),
    .m_axi_gmem1_AWCACHE(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_AWCACHE),
    .m_axi_gmem1_AWPROT(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_AWPROT),
    .m_axi_gmem1_AWQOS(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_AWQOS),
    .m_axi_gmem1_AWREGION(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_AWREGION),
    .m_axi_gmem1_AWUSER(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_AWUSER),
    .m_axi_gmem1_WVALID(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_WVALID),
    .m_axi_gmem1_WREADY(1'b0),
    .m_axi_gmem1_WDATA(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_WDATA),
    .m_axi_gmem1_WSTRB(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_WSTRB),
    .m_axi_gmem1_WLAST(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_WLAST),
    .m_axi_gmem1_WID(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_WID),
    .m_axi_gmem1_WUSER(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_WUSER),
    .m_axi_gmem1_ARVALID(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARVALID),
    .m_axi_gmem1_ARREADY(m_axi_gmem1_ARREADY),
    .m_axi_gmem1_ARADDR(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARADDR),
    .m_axi_gmem1_ARID(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARID),
    .m_axi_gmem1_ARLEN(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARLEN),
    .m_axi_gmem1_ARSIZE(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARSIZE),
    .m_axi_gmem1_ARBURST(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARBURST),
    .m_axi_gmem1_ARLOCK(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARLOCK),
    .m_axi_gmem1_ARCACHE(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARCACHE),
    .m_axi_gmem1_ARPROT(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARPROT),
    .m_axi_gmem1_ARQOS(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARQOS),
    .m_axi_gmem1_ARREGION(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARREGION),
    .m_axi_gmem1_ARUSER(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARUSER),
    .m_axi_gmem1_RVALID(m_axi_gmem1_RVALID),
    .m_axi_gmem1_RREADY(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_RREADY),
    .m_axi_gmem1_RDATA(m_axi_gmem1_RDATA),
    .m_axi_gmem1_RLAST(m_axi_gmem1_RLAST),
    .m_axi_gmem1_RID(m_axi_gmem1_RID),
    .m_axi_gmem1_RFIFONUM(m_axi_gmem1_RFIFONUM),
    .m_axi_gmem1_RUSER(m_axi_gmem1_RUSER),
    .m_axi_gmem1_RRESP(m_axi_gmem1_RRESP),
    .m_axi_gmem1_BVALID(1'b0),
    .m_axi_gmem1_BREADY(load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_BREADY),
    .m_axi_gmem1_BRESP(2'd0),
    .m_axi_gmem1_BID(1'd0),
    .m_axi_gmem1_BUSER(1'd0),
    .s_in01_din(load_rows_Loop_LOAD_ROW_proc1_U0_s_in01_din),
    .s_in01_num_data_valid(7'd0),
    .s_in01_fifo_cap(7'd0),
    .s_in01_full_n(s_in01_full_n),
    .s_in01_write(load_rows_Loop_LOAD_ROW_proc1_U0_s_in01_write),
    .s_in12_din(load_rows_Loop_LOAD_ROW_proc1_U0_s_in12_din),
    .s_in12_num_data_valid(7'd0),
    .s_in12_fifo_cap(7'd0),
    .s_in12_full_n(s_in12_full_n),
    .s_in12_write(load_rows_Loop_LOAD_ROW_proc1_U0_s_in12_write)
);

assign ap_done = load_rows_Loop_LOAD_ROW_proc1_U0_ap_done;

assign ap_idle = load_rows_Loop_LOAD_ROW_proc1_U0_ap_idle;

assign ap_ready = load_rows_Loop_LOAD_ROW_proc1_U0_ap_ready;

assign load_rows_Loop_LOAD_ROW_proc1_U0_ap_continue = ap_continue;

assign load_rows_Loop_LOAD_ROW_proc1_U0_ap_start = ap_start;

assign m_axi_gmem0_ARADDR = load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARADDR;

assign m_axi_gmem0_ARBURST = load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARBURST;

assign m_axi_gmem0_ARCACHE = load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARCACHE;

assign m_axi_gmem0_ARID = load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARID;

assign m_axi_gmem0_ARLEN = load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARLEN;

assign m_axi_gmem0_ARLOCK = load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARLOCK;

assign m_axi_gmem0_ARPROT = load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARPROT;

assign m_axi_gmem0_ARQOS = load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARQOS;

assign m_axi_gmem0_ARREGION = load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARREGION;

assign m_axi_gmem0_ARSIZE = load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARSIZE;

assign m_axi_gmem0_ARUSER = load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARUSER;

assign m_axi_gmem0_ARVALID = load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_ARVALID;

assign m_axi_gmem0_AWADDR = 64'd0;

assign m_axi_gmem0_AWBURST = 2'd0;

assign m_axi_gmem0_AWCACHE = 4'd0;

assign m_axi_gmem0_AWID = 1'd0;

assign m_axi_gmem0_AWLEN = 32'd0;

assign m_axi_gmem0_AWLOCK = 2'd0;

assign m_axi_gmem0_AWPROT = 3'd0;

assign m_axi_gmem0_AWQOS = 4'd0;

assign m_axi_gmem0_AWREGION = 4'd0;

assign m_axi_gmem0_AWSIZE = 3'd0;

assign m_axi_gmem0_AWUSER = 1'd0;

assign m_axi_gmem0_AWVALID = 1'b0;

assign m_axi_gmem0_BREADY = 1'b0;

assign m_axi_gmem0_RREADY = load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem0_RREADY;

assign m_axi_gmem0_WDATA = 512'd0;

assign m_axi_gmem0_WID = 1'd0;

assign m_axi_gmem0_WLAST = 1'b0;

assign m_axi_gmem0_WSTRB = 64'd0;

assign m_axi_gmem0_WUSER = 1'd0;

assign m_axi_gmem0_WVALID = 1'b0;

assign m_axi_gmem1_ARADDR = load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARADDR;

assign m_axi_gmem1_ARBURST = load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARBURST;

assign m_axi_gmem1_ARCACHE = load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARCACHE;

assign m_axi_gmem1_ARID = load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARID;

assign m_axi_gmem1_ARLEN = load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARLEN;

assign m_axi_gmem1_ARLOCK = load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARLOCK;

assign m_axi_gmem1_ARPROT = load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARPROT;

assign m_axi_gmem1_ARQOS = load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARQOS;

assign m_axi_gmem1_ARREGION = load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARREGION;

assign m_axi_gmem1_ARSIZE = load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARSIZE;

assign m_axi_gmem1_ARUSER = load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARUSER;

assign m_axi_gmem1_ARVALID = load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_ARVALID;

assign m_axi_gmem1_AWADDR = 64'd0;

assign m_axi_gmem1_AWBURST = 2'd0;

assign m_axi_gmem1_AWCACHE = 4'd0;

assign m_axi_gmem1_AWID = 1'd0;

assign m_axi_gmem1_AWLEN = 32'd0;

assign m_axi_gmem1_AWLOCK = 2'd0;

assign m_axi_gmem1_AWPROT = 3'd0;

assign m_axi_gmem1_AWQOS = 4'd0;

assign m_axi_gmem1_AWREGION = 4'd0;

assign m_axi_gmem1_AWSIZE = 3'd0;

assign m_axi_gmem1_AWUSER = 1'd0;

assign m_axi_gmem1_AWVALID = 1'b0;

assign m_axi_gmem1_BREADY = 1'b0;

assign m_axi_gmem1_RREADY = load_rows_Loop_LOAD_ROW_proc1_U0_m_axi_gmem1_RREADY;

assign m_axi_gmem1_WDATA = 512'd0;

assign m_axi_gmem1_WID = 1'd0;

assign m_axi_gmem1_WLAST = 1'b0;

assign m_axi_gmem1_WSTRB = 64'd0;

assign m_axi_gmem1_WUSER = 1'd0;

assign m_axi_gmem1_WVALID = 1'b0;

assign s_in01_din = load_rows_Loop_LOAD_ROW_proc1_U0_s_in01_din;

assign s_in01_write = load_rows_Loop_LOAD_ROW_proc1_U0_s_in01_write;

assign s_in12_din = load_rows_Loop_LOAD_ROW_proc1_U0_s_in12_din;

assign s_in12_write = load_rows_Loop_LOAD_ROW_proc1_U0_s_in12_write;

endmodule //activation_accelerator_load_rows
