set SynModuleInfo {
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_465_4 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_465_4 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_465_4
    SUBMODULES {
      {MODELNAME activation_accelerator_mux_164_16_1_1 RTLNAME activation_accelerator_mux_164_16_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_flow_control_loop_pipe_sequential_init RTLNAME activation_accelerator_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME activation_accelerator_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_145_18 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_145_18 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_145_18}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_186_1 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_186_1 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_186_1
    SUBMODULES {
      {MODELNAME activation_accelerator_mux_164_32_1_1 RTLNAME activation_accelerator_mux_164_32_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_191_2 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_191_2 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_191_2}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_197_3 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_197_3 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_197_3}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_145_17 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_145_17 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_145_17}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_171_1 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_171_1 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_171_1}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_176_2 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_176_2 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_176_2}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_145_16 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_145_16 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_145_16}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_160_1 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_160_1 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_160_1}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_145_15 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_145_15 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_145_15}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_152_1 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_152_1 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_152_1}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_145_13 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_145_13 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_145_13}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_145_14 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_145_14 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_145_14}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_380_1 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_380_1 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_380_1}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_382_2 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_382_2 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_382_2
    SUBMODULES {
      {MODELNAME activation_accelerator_fcmp_32ns_32ns_1_2_no_dsp_1 RTLNAME activation_accelerator_fcmp_32ns_32ns_1_2_no_dsp_1 BINDTYPE op TYPE fcmp IMPL auto LATENCY 1 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_385_3 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_385_3 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_385_3}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_389_4 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_389_4 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_389_4}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_145_12 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_145_12 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_145_12}
  {SRCNAME fmaxf MODELNAME fmaxf RTLNAME activation_accelerator_fmaxf}
  {SRCNAME float_safe_softmax_Pipeline_find_max_blocks MODELNAME float_safe_softmax_Pipeline_find_max_blocks RTLNAME activation_accelerator_float_safe_softmax_Pipeline_find_max_blocks
    SUBMODULES {
      {MODELNAME activation_accelerator_mux_325_32_1_1 RTLNAME activation_accelerator_mux_325_32_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME float_safe_softmax_Pipeline_exp_and_bucket MODELNAME float_safe_softmax_Pipeline_exp_and_bucket RTLNAME activation_accelerator_float_safe_softmax_Pipeline_exp_and_bucket
    SUBMODULES {
      {MODELNAME activation_accelerator_fadd_32ns_32ns_32_4_no_dsp_1 RTLNAME activation_accelerator_fadd_32ns_32ns_32_4_no_dsp_1 BINDTYPE op TYPE fadd IMPL fabric LATENCY 3 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME float_safe_softmax_Pipeline_normalize_blocks MODELNAME float_safe_softmax_Pipeline_normalize_blocks RTLNAME activation_accelerator_float_safe_softmax_Pipeline_normalize_blocks}
  {SRCNAME float_safe_softmax MODELNAME float_safe_softmax RTLNAME activation_accelerator_float_safe_softmax
    SUBMODULES {
      {MODELNAME activation_accelerator_float_safe_softmax_exp_x_RAM_1P_BRAM_1R1W RTLNAME activation_accelerator_float_safe_softmax_exp_x_RAM_1P_BRAM_1R1W BINDTYPE storage TYPE ram_1p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_145_1 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_145_1 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_145_1}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_145_11 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_145_11 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_145_11}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_206_1 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_206_1 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_206_1}
  {SRCNAME bf16add MODELNAME bf16add RTLNAME activation_accelerator_bf16add}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_424_3 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_424_3 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_424_3}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_411_1 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_411_1 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_411_1}
  {SRCNAME activation_accelerator_Pipeline_VITIS_LOOP_414_2 MODELNAME activation_accelerator_Pipeline_VITIS_LOOP_414_2 RTLNAME activation_accelerator_activation_accelerator_Pipeline_VITIS_LOOP_414_2}
  {SRCNAME activation_accelerator MODELNAME activation_accelerator RTLNAME activation_accelerator IS_TOP 1
    SUBMODULES {
      {MODELNAME activation_accelerator_faddfsub_32ns_32ns_32_4_full_dsp_1 RTLNAME activation_accelerator_faddfsub_32ns_32ns_32_4_full_dsp_1 BINDTYPE op TYPE fadd IMPL fulldsp LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_fmul_32ns_32ns_32_3_max_dsp_1 RTLNAME activation_accelerator_fmul_32ns_32ns_32_3_max_dsp_1 BINDTYPE op TYPE fmul IMPL maxdsp LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_fsqrt_32ns_32ns_32_8_no_dsp_1 RTLNAME activation_accelerator_fsqrt_32ns_32ns_32_8_no_dsp_1 BINDTYPE op TYPE fsqrt IMPL fabric LATENCY 7 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_fdiv_32ns_32ns_32_9_no_dsp_1 RTLNAME activation_accelerator_fdiv_32ns_32ns_32_9_no_dsp_1 BINDTYPE op TYPE fdiv IMPL fabric LATENCY 8 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_fexp_32ns_32ns_32_8_full_dsp_1 RTLNAME activation_accelerator_fexp_32ns_32ns_32_8_full_dsp_1 BINDTYPE op TYPE fexp IMPL fulldsp LATENCY 7 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_buf0_RAM_AUTO_1R1W RTLNAME activation_accelerator_buf0_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_Rbkb RTLNAME activation_accelerator_activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_Rbkb BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_x_mask_RAM_AUTO_1R1W RTLNAME activation_accelerator_x_mask_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_x_RAM_AUTO_1R1W RTLNAME activation_accelerator_x_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_gmem0_m_axi RTLNAME activation_accelerator_gmem0_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME activation_accelerator_gmem1_m_axi RTLNAME activation_accelerator_gmem1_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME activation_accelerator_gmem2_m_axi RTLNAME activation_accelerator_gmem2_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME activation_accelerator_control_s_axi RTLNAME activation_accelerator_control_s_axi BINDTYPE interface TYPE interface_s_axilite}
    }
  }
}
