-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity activation_accelerator_round_float32_to_bf16_ieee is
port (
    ap_ready : OUT STD_LOGIC;
    x_in : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of activation_accelerator_round_float32_to_bf16_ieee is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv31_7F800000 : STD_LOGIC_VECTOR (30 downto 0) := "1111111100000000000000000000000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_8000 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000001000000000000000";
    constant ap_const_lv32_7FFF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000111111111111111";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal fbits_fu_44_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_52_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal exp_fu_62_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal mant_fu_48_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_1_fu_100_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_2_fu_110_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln29_fu_76_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln_fu_120_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln_fu_90_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_fu_82_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln34_fu_138_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal fbits_1_fu_146_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln27_fu_70_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln30_fu_130_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln1_fu_152_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_ce_reg : STD_LOGIC;


begin



    ap_ready <= ap_const_logic_1;
    ap_return <= 
        select_ln30_fu_130_p3 when (icmp_ln27_fu_70_p2(0) = '1') else 
        trunc_ln1_fu_152_p4;
    exp_fu_62_p3 <= (tmp_fu_52_p4 & ap_const_lv23_0);
    fbits_1_fu_146_p2 <= std_logic_vector(unsigned(select_ln34_fu_138_p3) + unsigned(fbits_fu_44_p1));
    fbits_fu_44_p1 <= x_in;
    icmp_ln27_fu_70_p2 <= "1" when (exp_fu_62_p3 = ap_const_lv31_7F800000) else "0";
    icmp_ln29_fu_76_p2 <= "0" when (mant_fu_48_p1 = ap_const_lv23_0) else "1";
    mant_fu_48_p1 <= fbits_fu_44_p1(23 - 1 downto 0);
    or_ln_fu_120_p4 <= ((tmp_1_fu_100_p4 & ap_const_lv1_1) & tmp_2_fu_110_p4);
    select_ln30_fu_130_p3 <= 
        or_ln_fu_120_p4 when (icmp_ln29_fu_76_p2(0) = '1') else 
        trunc_ln_fu_90_p4;
    select_ln34_fu_138_p3 <= 
        ap_const_lv32_8000 when (tmp_3_fu_82_p3(0) = '1') else 
        ap_const_lv32_7FFF;
    tmp_1_fu_100_p4 <= fbits_fu_44_p1(31 downto 23);
    tmp_2_fu_110_p4 <= fbits_fu_44_p1(21 downto 16);
    tmp_3_fu_82_p3 <= fbits_fu_44_p1(16 downto 16);
    tmp_fu_52_p4 <= fbits_fu_44_p1(30 downto 23);
    trunc_ln1_fu_152_p4 <= fbits_1_fu_146_p2(31 downto 16);
    trunc_ln_fu_90_p4 <= fbits_fu_44_p1(31 downto 16);
end behav;
