set SynModuleInfo {
  {SRCNAME activation_accelerator_Pipeline_stage_2_store MODELNAME activation_accelerator_Pipeline_stage_2_store RTLNAME activation_accelerator_activation_accelerator_Pipeline_stage_2_store
    SUBMODULES {
      {MODELNAME activation_accelerator_sparsemux_65_5_16_1_1 RTLNAME activation_accelerator_sparsemux_65_5_16_1_1 BINDTYPE op TYPE sparsemux IMPL compactencoding_dontcare}
      {MODELNAME activation_accelerator_flow_control_loop_pipe_sequential_init RTLNAME activation_accelerator_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME activation_accelerator_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME activation_accelerator_Pipeline_gelu_blocks MODELNAME activation_accelerator_Pipeline_gelu_blocks RTLNAME activation_accelerator_activation_accelerator_Pipeline_gelu_blocks}
  {SRCNAME round_float32_to_bf16_ieee MODELNAME round_float32_to_bf16_ieee RTLNAME activation_accelerator_round_float32_to_bf16_ieee}
  {SRCNAME f32_to_bf16_array MODELNAME f32_to_bf16_array RTLNAME activation_accelerator_f32_to_bf16_array}
  {SRCNAME activation_accelerator_Pipeline_add_blocks MODELNAME activation_accelerator_Pipeline_add_blocks RTLNAME activation_accelerator_activation_accelerator_Pipeline_add_blocks}
  {SRCNAME activation_accelerator_Pipeline_multiply_blocks_Multiply MODELNAME activation_accelerator_Pipeline_multiply_blocks_Multiply RTLNAME activation_accelerator_activation_accelerator_Pipeline_multiply_blocks_Multiply}
  {SRCNAME square_Pipeline_sum_square MODELNAME square_Pipeline_sum_square RTLNAME activation_accelerator_square_Pipeline_sum_square
    SUBMODULES {
      {MODELNAME activation_accelerator_fadd_32ns_32ns_32_4_full_dsp_1 RTLNAME activation_accelerator_fadd_32ns_32ns_32_4_full_dsp_1 BINDTYPE op TYPE fadd IMPL fulldsp LATENCY 3 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME square MODELNAME square RTLNAME activation_accelerator_square}
  {SRCNAME activation_accelerator_Pipeline_rms_calculate_loop_rms_norm3 MODELNAME activation_accelerator_Pipeline_rms_calculate_loop_rms_norm3 RTLNAME activation_accelerator_activation_accelerator_Pipeline_rms_calculate_loop_rms_norm3
    SUBMODULES {
      {MODELNAME activation_accelerator_sparsemux_129_6_32_1_1 RTLNAME activation_accelerator_sparsemux_129_6_32_1_1 BINDTYPE op TYPE sparsemux IMPL compactencoding_dontcare}
    }
  }
  {SRCNAME activation_accelerator_Pipeline_normalize_blocks_rms_norm3 MODELNAME activation_accelerator_Pipeline_normalize_blocks_rms_norm3 RTLNAME activation_accelerator_activation_accelerator_Pipeline_normalize_blocks_rms_norm3}
  {SRCNAME activation_accelerator_Pipeline_mean_blocks_layer_norm3 MODELNAME activation_accelerator_Pipeline_mean_blocks_layer_norm3 RTLNAME activation_accelerator_activation_accelerator_Pipeline_mean_blocks_layer_norm3}
  {SRCNAME activation_accelerator_Pipeline_normalize_blocks_layer_norm3 MODELNAME activation_accelerator_Pipeline_normalize_blocks_layer_norm3 RTLNAME activation_accelerator_activation_accelerator_Pipeline_normalize_blocks_layer_norm3}
  {SRCNAME generic_fmax<float> MODELNAME generic_fmax_float_s RTLNAME activation_accelerator_generic_fmax_float_s
    SUBMODULES {
      {MODELNAME activation_accelerator_sparsemux_9_3_32_1_1 RTLNAME activation_accelerator_sparsemux_9_3_32_1_1 BINDTYPE op TYPE sparsemux IMPL onehotencoding_realdef}
    }
  }
  {SRCNAME activation_accelerator_Pipeline_lane_reduce MODELNAME activation_accelerator_Pipeline_lane_reduce RTLNAME activation_accelerator_activation_accelerator_Pipeline_lane_reduce}
  {SRCNAME activation_accelerator_Pipeline_softmax_final MODELNAME activation_accelerator_Pipeline_softmax_final RTLNAME activation_accelerator_activation_accelerator_Pipeline_softmax_final}
  {SRCNAME activation_accelerator_Pipeline_silu_blocks MODELNAME activation_accelerator_Pipeline_silu_blocks RTLNAME activation_accelerator_activation_accelerator_Pipeline_silu_blocks}
  {SRCNAME activation_accelerator_Pipeline_stage_0_load0 MODELNAME activation_accelerator_Pipeline_stage_0_load0 RTLNAME activation_accelerator_activation_accelerator_Pipeline_stage_0_load0}
  {SRCNAME activation_accelerator_Pipeline_stage_0_load1 MODELNAME activation_accelerator_Pipeline_stage_0_load1 RTLNAME activation_accelerator_activation_accelerator_Pipeline_stage_0_load1}
  {SRCNAME activation_accelerator MODELNAME activation_accelerator RTLNAME activation_accelerator IS_TOP 1
    SUBMODULES {
      {MODELNAME activation_accelerator_faddfsub_32ns_32ns_32_4_full_dsp_1 RTLNAME activation_accelerator_faddfsub_32ns_32ns_32_4_full_dsp_1 BINDTYPE op TYPE fsub IMPL fulldsp LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_fmul_32ns_32ns_32_3_max_dsp_1 RTLNAME activation_accelerator_fmul_32ns_32ns_32_3_max_dsp_1 BINDTYPE op TYPE fmul IMPL maxdsp LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_fdiv_32ns_32ns_32_9_no_dsp_1 RTLNAME activation_accelerator_fdiv_32ns_32ns_32_9_no_dsp_1 BINDTYPE op TYPE fdiv IMPL fabric LATENCY 8 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_fsqrt_32ns_32ns_32_8_no_dsp_1 RTLNAME activation_accelerator_fsqrt_32ns_32ns_32_8_no_dsp_1 BINDTYPE op TYPE fsqrt IMPL fabric LATENCY 7 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_fexp_32ns_32ns_32_8_full_dsp_1 RTLNAME activation_accelerator_fexp_32ns_32ns_32_8_full_dsp_1 BINDTYPE op TYPE fexp IMPL fulldsp LATENCY 7 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_39_bkb RTLNAME activation_accelerator_activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_39_bkb BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_Rvdy RTLNAME activation_accelerator_activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_9_Rvdy BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_19_Ffa RTLNAME activation_accelerator_activation_accelerator_unsigned_short_unsigned_short_unsigned_short_int_i_19_Ffa BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME activation_accelerator_gmem0_m_axi RTLNAME activation_accelerator_gmem0_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME activation_accelerator_gmem1_m_axi RTLNAME activation_accelerator_gmem1_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME activation_accelerator_gmem2_m_axi RTLNAME activation_accelerator_gmem2_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME activation_accelerator_control_s_axi RTLNAME activation_accelerator_control_s_axi BINDTYPE interface TYPE interface_s_axilite}
    }
  }
}
