// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module activation_accelerator_float_layer_norm2_Pipeline_sum_blocks (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_0_address0,
        x_0_ce0,
        x_0_q0,
        x_0_address1,
        x_0_ce1,
        x_0_q1,
        x_1_address0,
        x_1_ce0,
        x_1_q0,
        x_1_address1,
        x_1_ce1,
        x_1_q1,
        x_2_address0,
        x_2_ce0,
        x_2_q0,
        x_2_address1,
        x_2_ce1,
        x_2_q1,
        x_3_address0,
        x_3_ce0,
        x_3_q0,
        x_3_address1,
        x_3_ce1,
        x_3_q1,
        x_4_address0,
        x_4_ce0,
        x_4_q0,
        x_4_address1,
        x_4_ce1,
        x_4_q1,
        x_5_address0,
        x_5_ce0,
        x_5_q0,
        x_5_address1,
        x_5_ce1,
        x_5_q1,
        x_6_address0,
        x_6_ce0,
        x_6_q0,
        x_6_address1,
        x_6_ce1,
        x_6_q1,
        x_7_address0,
        x_7_ce0,
        x_7_q0,
        x_7_address1,
        x_7_ce1,
        x_7_q1,
        x_8_address0,
        x_8_ce0,
        x_8_q0,
        x_8_address1,
        x_8_ce1,
        x_8_q1,
        x_9_address0,
        x_9_ce0,
        x_9_q0,
        x_9_address1,
        x_9_ce1,
        x_9_q1,
        x_10_address0,
        x_10_ce0,
        x_10_q0,
        x_10_address1,
        x_10_ce1,
        x_10_q1,
        x_11_address0,
        x_11_ce0,
        x_11_q0,
        x_11_address1,
        x_11_ce1,
        x_11_q1,
        x_12_address0,
        x_12_ce0,
        x_12_q0,
        x_12_address1,
        x_12_ce1,
        x_12_q1,
        x_13_address0,
        x_13_ce0,
        x_13_q0,
        x_13_address1,
        x_13_ce1,
        x_13_q1,
        x_14_address0,
        x_14_ce0,
        x_14_q0,
        x_14_address1,
        x_14_ce1,
        x_14_q1,
        x_15_address0,
        x_15_ce0,
        x_15_q0,
        x_15_address1,
        x_15_ce1,
        x_15_q1,
        add29_31143_out,
        add29_31143_out_ap_vld,
        add29_30141_out,
        add29_30141_out_ap_vld,
        add29_29139_out,
        add29_29139_out_ap_vld,
        add29_28137_out,
        add29_28137_out_ap_vld,
        add29_27135_out,
        add29_27135_out_ap_vld,
        add29_26133_out,
        add29_26133_out_ap_vld,
        add29_25131_out,
        add29_25131_out_ap_vld,
        add29_24129_out,
        add29_24129_out_ap_vld,
        add29_23127_out,
        add29_23127_out_ap_vld,
        add29_22125_out,
        add29_22125_out_ap_vld,
        add29_21123_out,
        add29_21123_out_ap_vld,
        add29_20121_out,
        add29_20121_out_ap_vld,
        add29_19119_out,
        add29_19119_out_ap_vld,
        add29_18117_out,
        add29_18117_out_ap_vld,
        add29_17115_out,
        add29_17115_out_ap_vld,
        add29_16113_out,
        add29_16113_out_ap_vld,
        add29_15111_out,
        add29_15111_out_ap_vld,
        add29_14109_out,
        add29_14109_out_ap_vld,
        add29_13107_out,
        add29_13107_out_ap_vld,
        add29_12105_out,
        add29_12105_out_ap_vld,
        add29_11103_out,
        add29_11103_out_ap_vld,
        add29_10101_out,
        add29_10101_out_ap_vld,
        add29_999_out,
        add29_999_out_ap_vld,
        add29_897_out,
        add29_897_out_ap_vld,
        add29_795_out,
        add29_795_out_ap_vld,
        add29_693_out,
        add29_693_out_ap_vld,
        add29_591_out,
        add29_591_out_ap_vld,
        add29_489_out,
        add29_489_out_ap_vld,
        add29_387_out,
        add29_387_out_ap_vld,
        add29_285_out,
        add29_285_out_ap_vld,
        add29_183_out,
        add29_183_out_ap_vld,
        add2981_out,
        add2981_out_ap_vld,
        grp_fu_543_p_din0,
        grp_fu_543_p_din1,
        grp_fu_543_p_opcode,
        grp_fu_543_p_dout0,
        grp_fu_543_p_ce,
        grp_fu_1416_p_din0,
        grp_fu_1416_p_din1,
        grp_fu_1416_p_opcode,
        grp_fu_1416_p_dout0,
        grp_fu_1416_p_ce,
        grp_fu_1420_p_din0,
        grp_fu_1420_p_din1,
        grp_fu_1420_p_opcode,
        grp_fu_1420_p_dout0,
        grp_fu_1420_p_ce,
        grp_fu_1424_p_din0,
        grp_fu_1424_p_din1,
        grp_fu_1424_p_opcode,
        grp_fu_1424_p_dout0,
        grp_fu_1424_p_ce,
        grp_fu_1428_p_din0,
        grp_fu_1428_p_din1,
        grp_fu_1428_p_opcode,
        grp_fu_1428_p_dout0,
        grp_fu_1428_p_ce,
        grp_fu_1432_p_din0,
        grp_fu_1432_p_din1,
        grp_fu_1432_p_opcode,
        grp_fu_1432_p_dout0,
        grp_fu_1432_p_ce,
        grp_fu_1436_p_din0,
        grp_fu_1436_p_din1,
        grp_fu_1436_p_opcode,
        grp_fu_1436_p_dout0,
        grp_fu_1436_p_ce,
        grp_fu_1440_p_din0,
        grp_fu_1440_p_din1,
        grp_fu_1440_p_opcode,
        grp_fu_1440_p_dout0,
        grp_fu_1440_p_ce,
        grp_fu_1444_p_din0,
        grp_fu_1444_p_din1,
        grp_fu_1444_p_opcode,
        grp_fu_1444_p_dout0,
        grp_fu_1444_p_ce,
        grp_fu_1448_p_din0,
        grp_fu_1448_p_din1,
        grp_fu_1448_p_opcode,
        grp_fu_1448_p_dout0,
        grp_fu_1448_p_ce,
        grp_fu_1452_p_din0,
        grp_fu_1452_p_din1,
        grp_fu_1452_p_opcode,
        grp_fu_1452_p_dout0,
        grp_fu_1452_p_ce,
        grp_fu_1456_p_din0,
        grp_fu_1456_p_din1,
        grp_fu_1456_p_opcode,
        grp_fu_1456_p_dout0,
        grp_fu_1456_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 3'd1;
parameter    ap_ST_fsm_pp0_stage1 = 3'd2;
parameter    ap_ST_fsm_pp0_stage2 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] x_0_address0;
output   x_0_ce0;
input  [31:0] x_0_q0;
output  [11:0] x_0_address1;
output   x_0_ce1;
input  [31:0] x_0_q1;
output  [11:0] x_1_address0;
output   x_1_ce0;
input  [31:0] x_1_q0;
output  [11:0] x_1_address1;
output   x_1_ce1;
input  [31:0] x_1_q1;
output  [11:0] x_2_address0;
output   x_2_ce0;
input  [31:0] x_2_q0;
output  [11:0] x_2_address1;
output   x_2_ce1;
input  [31:0] x_2_q1;
output  [11:0] x_3_address0;
output   x_3_ce0;
input  [31:0] x_3_q0;
output  [11:0] x_3_address1;
output   x_3_ce1;
input  [31:0] x_3_q1;
output  [11:0] x_4_address0;
output   x_4_ce0;
input  [31:0] x_4_q0;
output  [11:0] x_4_address1;
output   x_4_ce1;
input  [31:0] x_4_q1;
output  [11:0] x_5_address0;
output   x_5_ce0;
input  [31:0] x_5_q0;
output  [11:0] x_5_address1;
output   x_5_ce1;
input  [31:0] x_5_q1;
output  [11:0] x_6_address0;
output   x_6_ce0;
input  [31:0] x_6_q0;
output  [11:0] x_6_address1;
output   x_6_ce1;
input  [31:0] x_6_q1;
output  [11:0] x_7_address0;
output   x_7_ce0;
input  [31:0] x_7_q0;
output  [11:0] x_7_address1;
output   x_7_ce1;
input  [31:0] x_7_q1;
output  [11:0] x_8_address0;
output   x_8_ce0;
input  [31:0] x_8_q0;
output  [11:0] x_8_address1;
output   x_8_ce1;
input  [31:0] x_8_q1;
output  [11:0] x_9_address0;
output   x_9_ce0;
input  [31:0] x_9_q0;
output  [11:0] x_9_address1;
output   x_9_ce1;
input  [31:0] x_9_q1;
output  [11:0] x_10_address0;
output   x_10_ce0;
input  [31:0] x_10_q0;
output  [11:0] x_10_address1;
output   x_10_ce1;
input  [31:0] x_10_q1;
output  [11:0] x_11_address0;
output   x_11_ce0;
input  [31:0] x_11_q0;
output  [11:0] x_11_address1;
output   x_11_ce1;
input  [31:0] x_11_q1;
output  [11:0] x_12_address0;
output   x_12_ce0;
input  [31:0] x_12_q0;
output  [11:0] x_12_address1;
output   x_12_ce1;
input  [31:0] x_12_q1;
output  [11:0] x_13_address0;
output   x_13_ce0;
input  [31:0] x_13_q0;
output  [11:0] x_13_address1;
output   x_13_ce1;
input  [31:0] x_13_q1;
output  [11:0] x_14_address0;
output   x_14_ce0;
input  [31:0] x_14_q0;
output  [11:0] x_14_address1;
output   x_14_ce1;
input  [31:0] x_14_q1;
output  [11:0] x_15_address0;
output   x_15_ce0;
input  [31:0] x_15_q0;
output  [11:0] x_15_address1;
output   x_15_ce1;
input  [31:0] x_15_q1;
output  [31:0] add29_31143_out;
output   add29_31143_out_ap_vld;
output  [31:0] add29_30141_out;
output   add29_30141_out_ap_vld;
output  [31:0] add29_29139_out;
output   add29_29139_out_ap_vld;
output  [31:0] add29_28137_out;
output   add29_28137_out_ap_vld;
output  [31:0] add29_27135_out;
output   add29_27135_out_ap_vld;
output  [31:0] add29_26133_out;
output   add29_26133_out_ap_vld;
output  [31:0] add29_25131_out;
output   add29_25131_out_ap_vld;
output  [31:0] add29_24129_out;
output   add29_24129_out_ap_vld;
output  [31:0] add29_23127_out;
output   add29_23127_out_ap_vld;
output  [31:0] add29_22125_out;
output   add29_22125_out_ap_vld;
output  [31:0] add29_21123_out;
output   add29_21123_out_ap_vld;
output  [31:0] add29_20121_out;
output   add29_20121_out_ap_vld;
output  [31:0] add29_19119_out;
output   add29_19119_out_ap_vld;
output  [31:0] add29_18117_out;
output   add29_18117_out_ap_vld;
output  [31:0] add29_17115_out;
output   add29_17115_out_ap_vld;
output  [31:0] add29_16113_out;
output   add29_16113_out_ap_vld;
output  [31:0] add29_15111_out;
output   add29_15111_out_ap_vld;
output  [31:0] add29_14109_out;
output   add29_14109_out_ap_vld;
output  [31:0] add29_13107_out;
output   add29_13107_out_ap_vld;
output  [31:0] add29_12105_out;
output   add29_12105_out_ap_vld;
output  [31:0] add29_11103_out;
output   add29_11103_out_ap_vld;
output  [31:0] add29_10101_out;
output   add29_10101_out_ap_vld;
output  [31:0] add29_999_out;
output   add29_999_out_ap_vld;
output  [31:0] add29_897_out;
output   add29_897_out_ap_vld;
output  [31:0] add29_795_out;
output   add29_795_out_ap_vld;
output  [31:0] add29_693_out;
output   add29_693_out_ap_vld;
output  [31:0] add29_591_out;
output   add29_591_out_ap_vld;
output  [31:0] add29_489_out;
output   add29_489_out_ap_vld;
output  [31:0] add29_387_out;
output   add29_387_out_ap_vld;
output  [31:0] add29_285_out;
output   add29_285_out_ap_vld;
output  [31:0] add29_183_out;
output   add29_183_out_ap_vld;
output  [31:0] add2981_out;
output   add2981_out_ap_vld;
output  [31:0] grp_fu_543_p_din0;
output  [31:0] grp_fu_543_p_din1;
output  [0:0] grp_fu_543_p_opcode;
input  [31:0] grp_fu_543_p_dout0;
output   grp_fu_543_p_ce;
output  [31:0] grp_fu_1416_p_din0;
output  [31:0] grp_fu_1416_p_din1;
output  [0:0] grp_fu_1416_p_opcode;
input  [31:0] grp_fu_1416_p_dout0;
output   grp_fu_1416_p_ce;
output  [31:0] grp_fu_1420_p_din0;
output  [31:0] grp_fu_1420_p_din1;
output  [0:0] grp_fu_1420_p_opcode;
input  [31:0] grp_fu_1420_p_dout0;
output   grp_fu_1420_p_ce;
output  [31:0] grp_fu_1424_p_din0;
output  [31:0] grp_fu_1424_p_din1;
output  [0:0] grp_fu_1424_p_opcode;
input  [31:0] grp_fu_1424_p_dout0;
output   grp_fu_1424_p_ce;
output  [31:0] grp_fu_1428_p_din0;
output  [31:0] grp_fu_1428_p_din1;
output  [0:0] grp_fu_1428_p_opcode;
input  [31:0] grp_fu_1428_p_dout0;
output   grp_fu_1428_p_ce;
output  [31:0] grp_fu_1432_p_din0;
output  [31:0] grp_fu_1432_p_din1;
output  [0:0] grp_fu_1432_p_opcode;
input  [31:0] grp_fu_1432_p_dout0;
output   grp_fu_1432_p_ce;
output  [31:0] grp_fu_1436_p_din0;
output  [31:0] grp_fu_1436_p_din1;
output  [0:0] grp_fu_1436_p_opcode;
input  [31:0] grp_fu_1436_p_dout0;
output   grp_fu_1436_p_ce;
output  [31:0] grp_fu_1440_p_din0;
output  [31:0] grp_fu_1440_p_din1;
output  [0:0] grp_fu_1440_p_opcode;
input  [31:0] grp_fu_1440_p_dout0;
output   grp_fu_1440_p_ce;
output  [31:0] grp_fu_1444_p_din0;
output  [31:0] grp_fu_1444_p_din1;
output  [0:0] grp_fu_1444_p_opcode;
input  [31:0] grp_fu_1444_p_dout0;
output   grp_fu_1444_p_ce;
output  [31:0] grp_fu_1448_p_din0;
output  [31:0] grp_fu_1448_p_din1;
output  [0:0] grp_fu_1448_p_opcode;
input  [31:0] grp_fu_1448_p_dout0;
output   grp_fu_1448_p_ce;
output  [31:0] grp_fu_1452_p_din0;
output  [31:0] grp_fu_1452_p_din1;
output  [0:0] grp_fu_1452_p_opcode;
input  [31:0] grp_fu_1452_p_dout0;
output   grp_fu_1452_p_ce;
output  [31:0] grp_fu_1456_p_din0;
output  [31:0] grp_fu_1456_p_din1;
output  [1:0] grp_fu_1456_p_opcode;
input  [31:0] grp_fu_1456_p_dout0;
output   grp_fu_1456_p_ce;

reg ap_idle;
reg x_0_ce0;
reg x_0_ce1;
reg x_1_ce0;
reg x_1_ce1;
reg x_2_ce0;
reg x_2_ce1;
reg x_3_ce0;
reg x_3_ce1;
reg x_4_ce0;
reg x_4_ce1;
reg x_5_ce0;
reg x_5_ce1;
reg x_6_ce0;
reg x_6_ce1;
reg x_7_ce0;
reg x_7_ce1;
reg x_8_ce0;
reg x_8_ce1;
reg x_9_ce0;
reg x_9_ce1;
reg x_10_ce0;
reg x_10_ce1;
reg x_11_ce0;
reg x_11_ce1;
reg x_12_ce0;
reg x_12_ce1;
reg x_13_ce0;
reg x_13_ce1;
reg x_14_ce0;
reg x_14_ce1;
reg x_15_ce0;
reg x_15_ce1;
reg add29_31143_out_ap_vld;
reg add29_30141_out_ap_vld;
reg add29_29139_out_ap_vld;
reg add29_28137_out_ap_vld;
reg add29_27135_out_ap_vld;
reg add29_26133_out_ap_vld;
reg add29_25131_out_ap_vld;
reg add29_24129_out_ap_vld;
reg add29_23127_out_ap_vld;
reg add29_22125_out_ap_vld;
reg add29_21123_out_ap_vld;
reg add29_20121_out_ap_vld;
reg add29_19119_out_ap_vld;
reg add29_18117_out_ap_vld;
reg add29_17115_out_ap_vld;
reg add29_16113_out_ap_vld;
reg add29_15111_out_ap_vld;
reg add29_14109_out_ap_vld;
reg add29_13107_out_ap_vld;
reg add29_12105_out_ap_vld;
reg add29_11103_out_ap_vld;
reg add29_10101_out_ap_vld;
reg add29_999_out_ap_vld;
reg add29_897_out_ap_vld;
reg add29_795_out_ap_vld;
reg add29_693_out_ap_vld;
reg add29_591_out_ap_vld;
reg add29_489_out_ap_vld;
reg add29_387_out_ap_vld;
reg add29_285_out_ap_vld;
reg add29_183_out_ap_vld;
reg add2981_out_ap_vld;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_state6_pp0_stage2_iter1;
wire    ap_block_pp0_stage2_subdone;
reg   [0:0] icmp_ln325_reg_1856;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_state7_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln325_fu_1105_p2;
reg   [0:0] icmp_ln325_reg_1856_pp0_iter1_reg;
wire   [63:0] zext_ln334_fu_1121_p1;
reg   [63:0] zext_ln334_reg_1860;
reg   [31:0] x_1_load_reg_2020;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state5_pp0_stage1_iter1;
wire    ap_block_state8_pp0_stage1_iter2;
wire    ap_block_pp0_stage1_11001;
reg   [31:0] x_2_load_reg_2025;
reg   [31:0] x_3_load_reg_2030;
reg   [31:0] x_4_load_reg_2035;
reg   [31:0] x_5_load_reg_2040;
reg   [31:0] x_6_load_reg_2045;
reg   [31:0] x_7_load_reg_2050;
reg   [31:0] x_8_load_reg_2055;
reg   [31:0] x_9_load_reg_2060;
reg   [31:0] x_10_load_reg_2065;
reg   [31:0] x_11_load_reg_2070;
reg   [31:0] x_12_load_reg_2075;
reg   [31:0] x_13_load_reg_2080;
reg   [31:0] x_14_load_reg_2085;
reg   [31:0] x_15_load_reg_2090;
reg   [31:0] x_0_load_7_reg_2095;
reg   [31:0] x_1_load_7_reg_2100;
reg   [31:0] x_2_load_7_reg_2105;
reg   [31:0] x_3_load_7_reg_2110;
reg   [31:0] x_4_load_7_reg_2115;
reg   [31:0] x_5_load_7_reg_2120;
reg   [31:0] x_6_load_7_reg_2125;
reg   [31:0] x_7_load_7_reg_2130;
reg   [31:0] x_8_load_7_reg_2135;
reg   [31:0] x_9_load_7_reg_2140;
reg   [31:0] x_10_load_7_reg_2145;
reg   [31:0] x_11_load_7_reg_2150;
reg   [31:0] x_12_load_7_reg_2155;
reg   [31:0] x_13_load_7_reg_2160;
reg   [31:0] x_14_load_7_reg_2165;
reg   [31:0] x_15_load_7_reg_2170;
wire    ap_block_pp0_stage2_11001;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln334_1_fu_1146_p1;
reg   [31:0] add2981_fu_132;
reg   [31:0] ap_sig_allocacmp_add2981_load;
wire    ap_block_pp0_stage1;
wire    ap_loop_init;
reg   [31:0] add29_183_fu_136;
reg   [31:0] ap_sig_allocacmp_add29_183_load;
wire    ap_block_pp0_stage2;
reg   [31:0] add29_285_fu_140;
reg   [31:0] ap_sig_allocacmp_add29_285_load;
reg   [31:0] add29_387_fu_144;
reg   [31:0] ap_sig_allocacmp_add29_387_load;
reg   [31:0] add29_489_fu_148;
reg   [31:0] ap_sig_allocacmp_add29_489_load;
reg   [31:0] add29_591_fu_152;
reg   [31:0] ap_sig_allocacmp_add29_591_load;
reg   [31:0] add29_693_fu_156;
reg   [31:0] ap_sig_allocacmp_add29_693_load;
reg   [31:0] add29_795_fu_160;
reg   [31:0] ap_sig_allocacmp_add29_795_load;
reg   [31:0] add29_897_fu_164;
reg   [31:0] ap_sig_allocacmp_add29_897_load;
reg   [31:0] add29_999_fu_168;
reg   [31:0] ap_sig_allocacmp_add29_999_load;
reg   [31:0] add29_10101_fu_172;
reg   [31:0] ap_sig_allocacmp_add29_10101_load;
reg   [31:0] add29_11103_fu_176;
reg   [31:0] ap_sig_allocacmp_add29_11103_load;
reg   [31:0] add29_12105_fu_180;
reg   [31:0] ap_sig_allocacmp_add29_12105_load;
reg   [31:0] add29_13107_fu_184;
reg   [31:0] ap_sig_allocacmp_add29_13107_load;
reg   [31:0] add29_14109_fu_188;
reg   [31:0] ap_sig_allocacmp_add29_14109_load;
reg   [31:0] add29_15111_fu_192;
reg   [31:0] ap_sig_allocacmp_add29_15111_load;
reg   [31:0] add29_16113_fu_196;
reg   [31:0] ap_sig_allocacmp_add29_16113_load;
reg   [31:0] add29_17115_fu_200;
reg   [31:0] ap_sig_allocacmp_add29_17115_load;
reg   [31:0] add29_18117_fu_204;
reg   [31:0] ap_sig_allocacmp_add29_18117_load;
reg   [31:0] add29_19119_fu_208;
reg   [31:0] ap_sig_allocacmp_add29_19119_load;
reg   [31:0] add29_20121_fu_212;
reg   [31:0] ap_sig_allocacmp_add29_20121_load;
reg   [31:0] add29_21123_fu_216;
reg   [31:0] ap_sig_allocacmp_add29_21123_load;
reg   [31:0] add29_22125_fu_220;
reg   [31:0] ap_sig_allocacmp_add29_22125_load;
reg   [31:0] add29_23127_fu_224;
reg   [31:0] ap_sig_allocacmp_add29_23127_load;
reg   [31:0] add29_24129_fu_228;
reg   [31:0] ap_sig_allocacmp_add29_24129_load;
reg   [31:0] add29_25131_fu_232;
reg   [31:0] ap_sig_allocacmp_add29_25131_load;
reg   [31:0] add29_26133_fu_236;
reg   [31:0] ap_sig_allocacmp_add29_26133_load;
reg   [31:0] add29_27135_fu_240;
reg   [31:0] ap_sig_allocacmp_add29_27135_load;
reg   [31:0] add29_28137_fu_244;
reg   [31:0] ap_sig_allocacmp_add29_28137_load;
reg   [31:0] add29_29139_fu_248;
reg   [31:0] ap_sig_allocacmp_add29_29139_load;
reg   [31:0] add29_30141_fu_252;
reg   [31:0] ap_sig_allocacmp_add29_30141_load;
reg   [31:0] add29_31143_fu_256;
reg   [31:0] ap_sig_allocacmp_add29_31143_load;
reg   [15:0] idx_fu_260;
wire   [15:0] add_ln325_fu_1166_p2;
reg   [15:0] ap_sig_allocacmp_i;
wire    ap_block_pp0_stage1_01001;
reg   [31:0] grp_fu_888_p0;
reg   [31:0] grp_fu_888_p1;
reg   [31:0] grp_fu_892_p0;
reg   [31:0] grp_fu_892_p1;
reg   [31:0] grp_fu_896_p0;
reg   [31:0] grp_fu_896_p1;
reg   [31:0] grp_fu_900_p0;
reg   [31:0] grp_fu_900_p1;
reg   [31:0] grp_fu_904_p0;
reg   [31:0] grp_fu_904_p1;
reg   [31:0] grp_fu_908_p0;
reg   [31:0] grp_fu_908_p1;
reg   [31:0] grp_fu_912_p0;
reg   [31:0] grp_fu_912_p1;
reg   [31:0] grp_fu_916_p0;
reg   [31:0] grp_fu_916_p1;
reg   [31:0] grp_fu_920_p0;
reg   [31:0] grp_fu_920_p1;
reg   [31:0] grp_fu_924_p0;
reg   [31:0] grp_fu_924_p1;
reg   [31:0] grp_fu_928_p0;
reg   [31:0] grp_fu_928_p1;
wire   [11:0] lshr_ln_fu_1111_p4;
wire   [11:0] or_ln334_fu_1140_p2;
wire    ap_block_pp0_stage2_00001;
wire    ap_block_pp0_stage0_00001;
wire    ap_block_pp0_stage1_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter1_stage1;
reg    ap_idle_pp0_0to0;
reg   [2:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to2;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

activation_accelerator_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage2)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add2981_fu_132 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add2981_fu_132 <= grp_fu_1456_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add29_10101_fu_172 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add29_10101_fu_172 <= grp_fu_1448_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add29_11103_fu_176 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add29_11103_fu_176 <= grp_fu_1452_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            add29_12105_fu_180 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            add29_12105_fu_180 <= grp_fu_543_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            add29_13107_fu_184 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            add29_13107_fu_184 <= grp_fu_1416_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            add29_14109_fu_188 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            add29_14109_fu_188 <= grp_fu_1420_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            add29_15111_fu_192 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            add29_15111_fu_192 <= grp_fu_1424_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            add29_16113_fu_196 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            add29_16113_fu_196 <= grp_fu_1428_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            add29_17115_fu_200 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            add29_17115_fu_200 <= grp_fu_1432_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            add29_18117_fu_204 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            add29_18117_fu_204 <= grp_fu_1436_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add29_183_fu_136 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add29_183_fu_136 <= grp_fu_543_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            add29_19119_fu_208 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            add29_19119_fu_208 <= grp_fu_1440_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            add29_20121_fu_212 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            add29_20121_fu_212 <= grp_fu_1444_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            add29_21123_fu_216 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            add29_21123_fu_216 <= grp_fu_1448_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            add29_22125_fu_220 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            add29_22125_fu_220 <= grp_fu_1452_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add29_23127_fu_224 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_23127_fu_224 <= grp_fu_543_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add29_24129_fu_228 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_24129_fu_228 <= grp_fu_1416_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add29_25131_fu_232 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_25131_fu_232 <= grp_fu_1420_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add29_26133_fu_236 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_26133_fu_236 <= grp_fu_1424_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add29_27135_fu_240 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_27135_fu_240 <= grp_fu_1428_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add29_28137_fu_244 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_28137_fu_244 <= grp_fu_1432_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add29_285_fu_140 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add29_285_fu_140 <= grp_fu_1416_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add29_29139_fu_248 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_29139_fu_248 <= grp_fu_1436_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add29_30141_fu_252 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_30141_fu_252 <= grp_fu_1440_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add29_31143_fu_256 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_31143_fu_256 <= grp_fu_1444_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add29_387_fu_144 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add29_387_fu_144 <= grp_fu_1420_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add29_489_fu_148 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add29_489_fu_148 <= grp_fu_1424_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add29_591_fu_152 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add29_591_fu_152 <= grp_fu_1428_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add29_693_fu_156 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add29_693_fu_156 <= grp_fu_1432_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add29_795_fu_160 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add29_795_fu_160 <= grp_fu_1436_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add29_897_fu_164 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add29_897_fu_164 <= grp_fu_1440_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add29_999_fu_168 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add29_999_fu_168 <= grp_fu_1444_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln325_fu_1105_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            idx_fu_260 <= add_ln325_fu_1166_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            idx_fu_260 <= 16'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln325_reg_1856 <= icmp_ln325_fu_1105_p2;
        icmp_ln325_reg_1856_pp0_iter1_reg <= icmp_ln325_reg_1856;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln325_reg_1856 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        x_0_load_7_reg_2095 <= x_0_q1;
        x_10_load_7_reg_2145 <= x_10_q0;
        x_10_load_reg_2065 <= x_10_q1;
        x_11_load_7_reg_2150 <= x_11_q0;
        x_11_load_reg_2070 <= x_11_q1;
        x_12_load_7_reg_2155 <= x_12_q0;
        x_12_load_reg_2075 <= x_12_q1;
        x_13_load_7_reg_2160 <= x_13_q0;
        x_13_load_reg_2080 <= x_13_q1;
        x_14_load_7_reg_2165 <= x_14_q0;
        x_14_load_reg_2085 <= x_14_q1;
        x_15_load_7_reg_2170 <= x_15_q0;
        x_15_load_reg_2090 <= x_15_q1;
        x_1_load_7_reg_2100 <= x_1_q0;
        x_1_load_reg_2020 <= x_1_q1;
        x_2_load_7_reg_2105 <= x_2_q0;
        x_2_load_reg_2025 <= x_2_q1;
        x_3_load_7_reg_2110 <= x_3_q0;
        x_3_load_reg_2030 <= x_3_q1;
        x_4_load_7_reg_2115 <= x_4_q0;
        x_4_load_reg_2035 <= x_4_q1;
        x_5_load_7_reg_2120 <= x_5_q0;
        x_5_load_reg_2040 <= x_5_q1;
        x_6_load_7_reg_2125 <= x_6_q0;
        x_6_load_reg_2045 <= x_6_q1;
        x_7_load_7_reg_2130 <= x_7_q0;
        x_7_load_reg_2050 <= x_7_q1;
        x_8_load_7_reg_2135 <= x_8_q0;
        x_8_load_reg_2055 <= x_8_q1;
        x_9_load_7_reg_2140 <= x_9_q0;
        x_9_load_reg_2060 <= x_9_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln325_fu_1105_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        zext_ln334_reg_1860[11 : 0] <= zext_ln334_fu_1121_p1[11 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln325_reg_1856_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add2981_out_ap_vld = 1'b1;
    end else begin
        add2981_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln325_reg_1856_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_10101_out_ap_vld = 1'b1;
    end else begin
        add29_10101_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln325_reg_1856_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_11103_out_ap_vld = 1'b1;
    end else begin
        add29_11103_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln325_reg_1856_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_12105_out_ap_vld = 1'b1;
    end else begin
        add29_12105_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln325_reg_1856_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_13107_out_ap_vld = 1'b1;
    end else begin
        add29_13107_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln325_reg_1856_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_14109_out_ap_vld = 1'b1;
    end else begin
        add29_14109_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln325_reg_1856_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_15111_out_ap_vld = 1'b1;
    end else begin
        add29_15111_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln325_reg_1856_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_16113_out_ap_vld = 1'b1;
    end else begin
        add29_16113_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln325_reg_1856_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_17115_out_ap_vld = 1'b1;
    end else begin
        add29_17115_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln325_reg_1856_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_18117_out_ap_vld = 1'b1;
    end else begin
        add29_18117_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln325_reg_1856_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_183_out_ap_vld = 1'b1;
    end else begin
        add29_183_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln325_reg_1856_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_19119_out_ap_vld = 1'b1;
    end else begin
        add29_19119_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln325_reg_1856_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_20121_out_ap_vld = 1'b1;
    end else begin
        add29_20121_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln325_reg_1856_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_21123_out_ap_vld = 1'b1;
    end else begin
        add29_21123_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln325_reg_1856_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_22125_out_ap_vld = 1'b1;
    end else begin
        add29_22125_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln325_reg_1856_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_23127_out_ap_vld = 1'b1;
    end else begin
        add29_23127_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln325_reg_1856_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_24129_out_ap_vld = 1'b1;
    end else begin
        add29_24129_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln325_reg_1856_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_25131_out_ap_vld = 1'b1;
    end else begin
        add29_25131_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln325_reg_1856_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_26133_out_ap_vld = 1'b1;
    end else begin
        add29_26133_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln325_reg_1856_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_27135_out_ap_vld = 1'b1;
    end else begin
        add29_27135_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln325_reg_1856_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_28137_out_ap_vld = 1'b1;
    end else begin
        add29_28137_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln325_reg_1856_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_285_out_ap_vld = 1'b1;
    end else begin
        add29_285_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln325_reg_1856_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_29139_out_ap_vld = 1'b1;
    end else begin
        add29_29139_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln325_reg_1856_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_30141_out_ap_vld = 1'b1;
    end else begin
        add29_30141_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln325_reg_1856_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_31143_out_ap_vld = 1'b1;
    end else begin
        add29_31143_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln325_reg_1856_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_387_out_ap_vld = 1'b1;
    end else begin
        add29_387_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln325_reg_1856_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_489_out_ap_vld = 1'b1;
    end else begin
        add29_489_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln325_reg_1856_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_591_out_ap_vld = 1'b1;
    end else begin
        add29_591_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln325_reg_1856_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_693_out_ap_vld = 1'b1;
    end else begin
        add29_693_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln325_reg_1856_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_795_out_ap_vld = 1'b1;
    end else begin
        add29_795_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln325_reg_1856_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_897_out_ap_vld = 1'b1;
    end else begin
        add29_897_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln325_reg_1856_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add29_999_out_ap_vld = 1'b1;
    end else begin
        add29_999_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln325_reg_1856 == 1'd0) & (1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (icmp_ln325_reg_1856_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter1_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_add2981_load = grp_fu_1456_p_dout0;
    end else begin
        ap_sig_allocacmp_add2981_load = add2981_fu_132;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_sig_allocacmp_add29_10101_load = grp_fu_1448_p_dout0;
    end else begin
        ap_sig_allocacmp_add29_10101_load = add29_10101_fu_172;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_sig_allocacmp_add29_11103_load = grp_fu_1452_p_dout0;
    end else begin
        ap_sig_allocacmp_add29_11103_load = add29_11103_fu_176;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_add29_12105_load = grp_fu_543_p_dout0;
    end else begin
        ap_sig_allocacmp_add29_12105_load = add29_12105_fu_180;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_add29_13107_load = grp_fu_1416_p_dout0;
    end else begin
        ap_sig_allocacmp_add29_13107_load = add29_13107_fu_184;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_add29_14109_load = grp_fu_1420_p_dout0;
    end else begin
        ap_sig_allocacmp_add29_14109_load = add29_14109_fu_188;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_add29_15111_load = grp_fu_1424_p_dout0;
    end else begin
        ap_sig_allocacmp_add29_15111_load = add29_15111_fu_192;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_add29_16113_load = grp_fu_1428_p_dout0;
    end else begin
        ap_sig_allocacmp_add29_16113_load = add29_16113_fu_196;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_add29_17115_load = grp_fu_1432_p_dout0;
    end else begin
        ap_sig_allocacmp_add29_17115_load = add29_17115_fu_200;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_add29_18117_load = grp_fu_1436_p_dout0;
    end else begin
        ap_sig_allocacmp_add29_18117_load = add29_18117_fu_204;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_sig_allocacmp_add29_183_load = grp_fu_543_p_dout0;
    end else begin
        ap_sig_allocacmp_add29_183_load = add29_183_fu_136;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_add29_19119_load = grp_fu_1440_p_dout0;
    end else begin
        ap_sig_allocacmp_add29_19119_load = add29_19119_fu_208;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_add29_20121_load = grp_fu_1444_p_dout0;
    end else begin
        ap_sig_allocacmp_add29_20121_load = add29_20121_fu_212;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_add29_21123_load = grp_fu_1448_p_dout0;
    end else begin
        ap_sig_allocacmp_add29_21123_load = add29_21123_fu_216;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_add29_22125_load = grp_fu_1452_p_dout0;
    end else begin
        ap_sig_allocacmp_add29_22125_load = add29_22125_fu_220;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_add29_23127_load = grp_fu_543_p_dout0;
    end else begin
        ap_sig_allocacmp_add29_23127_load = add29_23127_fu_224;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_add29_24129_load = grp_fu_1416_p_dout0;
    end else begin
        ap_sig_allocacmp_add29_24129_load = add29_24129_fu_228;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_add29_25131_load = grp_fu_1420_p_dout0;
    end else begin
        ap_sig_allocacmp_add29_25131_load = add29_25131_fu_232;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_add29_26133_load = grp_fu_1424_p_dout0;
    end else begin
        ap_sig_allocacmp_add29_26133_load = add29_26133_fu_236;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_add29_27135_load = grp_fu_1428_p_dout0;
    end else begin
        ap_sig_allocacmp_add29_27135_load = add29_27135_fu_240;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_add29_28137_load = grp_fu_1432_p_dout0;
    end else begin
        ap_sig_allocacmp_add29_28137_load = add29_28137_fu_244;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_sig_allocacmp_add29_285_load = grp_fu_1416_p_dout0;
    end else begin
        ap_sig_allocacmp_add29_285_load = add29_285_fu_140;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_add29_29139_load = grp_fu_1436_p_dout0;
    end else begin
        ap_sig_allocacmp_add29_29139_load = add29_29139_fu_248;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_add29_30141_load = grp_fu_1440_p_dout0;
    end else begin
        ap_sig_allocacmp_add29_30141_load = add29_30141_fu_252;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_add29_31143_load = grp_fu_1444_p_dout0;
    end else begin
        ap_sig_allocacmp_add29_31143_load = add29_31143_fu_256;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_sig_allocacmp_add29_387_load = grp_fu_1420_p_dout0;
    end else begin
        ap_sig_allocacmp_add29_387_load = add29_387_fu_144;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_sig_allocacmp_add29_489_load = grp_fu_1424_p_dout0;
    end else begin
        ap_sig_allocacmp_add29_489_load = add29_489_fu_148;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_sig_allocacmp_add29_591_load = grp_fu_1428_p_dout0;
    end else begin
        ap_sig_allocacmp_add29_591_load = add29_591_fu_152;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_sig_allocacmp_add29_693_load = grp_fu_1432_p_dout0;
    end else begin
        ap_sig_allocacmp_add29_693_load = add29_693_fu_156;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_sig_allocacmp_add29_795_load = grp_fu_1436_p_dout0;
    end else begin
        ap_sig_allocacmp_add29_795_load = add29_795_fu_160;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_sig_allocacmp_add29_897_load = grp_fu_1440_p_dout0;
    end else begin
        ap_sig_allocacmp_add29_897_load = add29_897_fu_164;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_sig_allocacmp_add29_999_load = grp_fu_1444_p_dout0;
    end else begin
        ap_sig_allocacmp_add29_999_load = add29_999_fu_168;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i = 16'd0;
    end else begin
        ap_sig_allocacmp_i = idx_fu_260;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_888_p0 = ap_sig_allocacmp_add29_23127_load;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_888_p0 = ap_sig_allocacmp_add29_12105_load;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_888_p0 = ap_sig_allocacmp_add29_183_load;
    end else begin
        grp_fu_888_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_888_p1 = x_7_load_7_reg_2130;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_888_p1 = x_12_load_reg_2075;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_888_p1 = x_1_load_reg_2020;
    end else begin
        grp_fu_888_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_892_p0 = ap_sig_allocacmp_add29_24129_load;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_892_p0 = ap_sig_allocacmp_add29_13107_load;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_892_p0 = ap_sig_allocacmp_add29_285_load;
    end else begin
        grp_fu_892_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_892_p1 = x_8_load_7_reg_2135;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_892_p1 = x_13_load_reg_2080;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_892_p1 = x_2_load_reg_2025;
    end else begin
        grp_fu_892_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_896_p0 = ap_sig_allocacmp_add29_25131_load;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_896_p0 = ap_sig_allocacmp_add29_14109_load;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_896_p0 = ap_sig_allocacmp_add29_387_load;
    end else begin
        grp_fu_896_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_896_p1 = x_9_load_7_reg_2140;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_896_p1 = x_14_load_reg_2085;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_896_p1 = x_3_load_reg_2030;
    end else begin
        grp_fu_896_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_900_p0 = ap_sig_allocacmp_add29_26133_load;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_900_p0 = ap_sig_allocacmp_add29_15111_load;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_900_p0 = ap_sig_allocacmp_add29_489_load;
    end else begin
        grp_fu_900_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_900_p1 = x_10_load_7_reg_2145;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_900_p1 = x_15_load_reg_2090;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_900_p1 = x_4_load_reg_2035;
    end else begin
        grp_fu_900_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_904_p0 = ap_sig_allocacmp_add29_27135_load;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_904_p0 = ap_sig_allocacmp_add29_16113_load;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_904_p0 = ap_sig_allocacmp_add29_591_load;
    end else begin
        grp_fu_904_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_904_p1 = x_11_load_7_reg_2150;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_904_p1 = x_0_load_7_reg_2095;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_904_p1 = x_5_load_reg_2040;
    end else begin
        grp_fu_904_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_908_p0 = ap_sig_allocacmp_add29_28137_load;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_908_p0 = ap_sig_allocacmp_add29_17115_load;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_908_p0 = ap_sig_allocacmp_add29_693_load;
    end else begin
        grp_fu_908_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_908_p1 = x_12_load_7_reg_2155;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_908_p1 = x_1_load_7_reg_2100;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_908_p1 = x_6_load_reg_2045;
    end else begin
        grp_fu_908_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_912_p0 = ap_sig_allocacmp_add29_29139_load;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_912_p0 = ap_sig_allocacmp_add29_18117_load;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_912_p0 = ap_sig_allocacmp_add29_795_load;
    end else begin
        grp_fu_912_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_912_p1 = x_13_load_7_reg_2160;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_912_p1 = x_2_load_7_reg_2105;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_912_p1 = x_7_load_reg_2050;
    end else begin
        grp_fu_912_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_916_p0 = ap_sig_allocacmp_add29_30141_load;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_916_p0 = ap_sig_allocacmp_add29_19119_load;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_916_p0 = ap_sig_allocacmp_add29_897_load;
    end else begin
        grp_fu_916_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_916_p1 = x_14_load_7_reg_2165;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_916_p1 = x_3_load_7_reg_2110;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_916_p1 = x_8_load_reg_2055;
    end else begin
        grp_fu_916_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_920_p0 = ap_sig_allocacmp_add29_31143_load;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_920_p0 = ap_sig_allocacmp_add29_20121_load;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_920_p0 = ap_sig_allocacmp_add29_999_load;
    end else begin
        grp_fu_920_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_920_p1 = x_15_load_7_reg_2170;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_920_p1 = x_4_load_7_reg_2115;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_920_p1 = x_9_load_reg_2060;
    end else begin
        grp_fu_920_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_924_p0 = ap_sig_allocacmp_add29_21123_load;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_924_p0 = ap_sig_allocacmp_add29_10101_load;
    end else begin
        grp_fu_924_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_924_p1 = x_5_load_7_reg_2120;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_924_p1 = x_10_load_reg_2065;
    end else begin
        grp_fu_924_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_928_p0 = ap_sig_allocacmp_add29_22125_load;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_928_p0 = ap_sig_allocacmp_add29_11103_load;
    end else begin
        grp_fu_928_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_928_p1 = x_6_load_7_reg_2125;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_928_p1 = x_11_load_reg_2070;
    end else begin
        grp_fu_928_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_0_ce0 = 1'b1;
    end else begin
        x_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_0_ce1 = 1'b1;
    end else begin
        x_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_10_ce0 = 1'b1;
    end else begin
        x_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_10_ce1 = 1'b1;
    end else begin
        x_10_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_11_ce0 = 1'b1;
    end else begin
        x_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_11_ce1 = 1'b1;
    end else begin
        x_11_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_12_ce0 = 1'b1;
    end else begin
        x_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_12_ce1 = 1'b1;
    end else begin
        x_12_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_13_ce0 = 1'b1;
    end else begin
        x_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_13_ce1 = 1'b1;
    end else begin
        x_13_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_14_ce0 = 1'b1;
    end else begin
        x_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_14_ce1 = 1'b1;
    end else begin
        x_14_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_15_ce0 = 1'b1;
    end else begin
        x_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_15_ce1 = 1'b1;
    end else begin
        x_15_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_1_ce0 = 1'b1;
    end else begin
        x_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_1_ce1 = 1'b1;
    end else begin
        x_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_2_ce0 = 1'b1;
    end else begin
        x_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_2_ce1 = 1'b1;
    end else begin
        x_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_3_ce0 = 1'b1;
    end else begin
        x_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_3_ce1 = 1'b1;
    end else begin
        x_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_4_ce0 = 1'b1;
    end else begin
        x_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_4_ce1 = 1'b1;
    end else begin
        x_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_5_ce0 = 1'b1;
    end else begin
        x_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_5_ce1 = 1'b1;
    end else begin
        x_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_6_ce0 = 1'b1;
    end else begin
        x_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_6_ce1 = 1'b1;
    end else begin
        x_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_7_ce0 = 1'b1;
    end else begin
        x_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_7_ce1 = 1'b1;
    end else begin
        x_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_8_ce0 = 1'b1;
    end else begin
        x_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_8_ce1 = 1'b1;
    end else begin
        x_8_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_9_ce0 = 1'b1;
    end else begin
        x_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_9_ce1 = 1'b1;
    end else begin
        x_9_ce1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to2 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if (((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add2981_out = add2981_fu_132;

assign add29_10101_out = add29_10101_fu_172;

assign add29_11103_out = add29_11103_fu_176;

assign add29_12105_out = add29_12105_fu_180;

assign add29_13107_out = add29_13107_fu_184;

assign add29_14109_out = add29_14109_fu_188;

assign add29_15111_out = add29_15111_fu_192;

assign add29_16113_out = add29_16113_fu_196;

assign add29_17115_out = add29_17115_fu_200;

assign add29_18117_out = add29_18117_fu_204;

assign add29_183_out = add29_183_fu_136;

assign add29_19119_out = add29_19119_fu_208;

assign add29_20121_out = add29_20121_fu_212;

assign add29_21123_out = add29_21123_fu_216;

assign add29_22125_out = add29_22125_fu_220;

assign add29_23127_out = add29_23127_fu_224;

assign add29_24129_out = add29_24129_fu_228;

assign add29_25131_out = add29_25131_fu_232;

assign add29_26133_out = add29_26133_fu_236;

assign add29_27135_out = add29_27135_fu_240;

assign add29_28137_out = add29_28137_fu_244;

assign add29_285_out = add29_285_fu_140;

assign add29_29139_out = add29_29139_fu_248;

assign add29_30141_out = add29_30141_fu_252;

assign add29_31143_out = add29_31143_fu_256;

assign add29_387_out = add29_387_fu_144;

assign add29_489_out = add29_489_fu_148;

assign add29_591_out = add29_591_fu_152;

assign add29_693_out = add29_693_fu_156;

assign add29_795_out = add29_795_fu_160;

assign add29_897_out = add29_897_fu_164;

assign add29_999_out = add29_999_fu_168;

assign add_ln325_fu_1166_p2 = (ap_sig_allocacmp_i + 16'd32);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

assign grp_fu_1416_p_ce = 1'b1;

assign grp_fu_1416_p_din0 = grp_fu_892_p0;

assign grp_fu_1416_p_din1 = grp_fu_892_p1;

assign grp_fu_1416_p_opcode = 2'd0;

assign grp_fu_1420_p_ce = 1'b1;

assign grp_fu_1420_p_din0 = grp_fu_896_p0;

assign grp_fu_1420_p_din1 = grp_fu_896_p1;

assign grp_fu_1420_p_opcode = 2'd0;

assign grp_fu_1424_p_ce = 1'b1;

assign grp_fu_1424_p_din0 = grp_fu_900_p0;

assign grp_fu_1424_p_din1 = grp_fu_900_p1;

assign grp_fu_1424_p_opcode = 2'd0;

assign grp_fu_1428_p_ce = 1'b1;

assign grp_fu_1428_p_din0 = grp_fu_904_p0;

assign grp_fu_1428_p_din1 = grp_fu_904_p1;

assign grp_fu_1428_p_opcode = 2'd0;

assign grp_fu_1432_p_ce = 1'b1;

assign grp_fu_1432_p_din0 = grp_fu_908_p0;

assign grp_fu_1432_p_din1 = grp_fu_908_p1;

assign grp_fu_1432_p_opcode = 2'd0;

assign grp_fu_1436_p_ce = 1'b1;

assign grp_fu_1436_p_din0 = grp_fu_912_p0;

assign grp_fu_1436_p_din1 = grp_fu_912_p1;

assign grp_fu_1436_p_opcode = 2'd0;

assign grp_fu_1440_p_ce = 1'b1;

assign grp_fu_1440_p_din0 = grp_fu_916_p0;

assign grp_fu_1440_p_din1 = grp_fu_916_p1;

assign grp_fu_1440_p_opcode = 2'd0;

assign grp_fu_1444_p_ce = 1'b1;

assign grp_fu_1444_p_din0 = grp_fu_920_p0;

assign grp_fu_1444_p_din1 = grp_fu_920_p1;

assign grp_fu_1444_p_opcode = 2'd0;

assign grp_fu_1448_p_ce = 1'b1;

assign grp_fu_1448_p_din0 = grp_fu_924_p0;

assign grp_fu_1448_p_din1 = grp_fu_924_p1;

assign grp_fu_1448_p_opcode = 2'd0;

assign grp_fu_1452_p_ce = 1'b1;

assign grp_fu_1452_p_din0 = grp_fu_928_p0;

assign grp_fu_1452_p_din1 = grp_fu_928_p1;

assign grp_fu_1452_p_opcode = 2'd0;

assign grp_fu_1456_p_ce = 1'b1;

assign grp_fu_1456_p_din0 = ap_sig_allocacmp_add2981_load;

assign grp_fu_1456_p_din1 = x_0_q0;

assign grp_fu_1456_p_opcode = 2'd0;

assign grp_fu_543_p_ce = 1'b1;

assign grp_fu_543_p_din0 = grp_fu_888_p0;

assign grp_fu_543_p_din1 = grp_fu_888_p1;

assign grp_fu_543_p_opcode = 2'd0;

assign icmp_ln325_fu_1105_p2 = ((ap_sig_allocacmp_i < 16'd49152) ? 1'b1 : 1'b0);

assign lshr_ln_fu_1111_p4 = {{ap_sig_allocacmp_i[15:4]}};

assign or_ln334_fu_1140_p2 = (lshr_ln_fu_1111_p4 | 12'd1);

assign x_0_address0 = zext_ln334_reg_1860;

assign x_0_address1 = zext_ln334_1_fu_1146_p1;

assign x_10_address0 = zext_ln334_1_fu_1146_p1;

assign x_10_address1 = zext_ln334_fu_1121_p1;

assign x_11_address0 = zext_ln334_1_fu_1146_p1;

assign x_11_address1 = zext_ln334_fu_1121_p1;

assign x_12_address0 = zext_ln334_1_fu_1146_p1;

assign x_12_address1 = zext_ln334_fu_1121_p1;

assign x_13_address0 = zext_ln334_1_fu_1146_p1;

assign x_13_address1 = zext_ln334_fu_1121_p1;

assign x_14_address0 = zext_ln334_1_fu_1146_p1;

assign x_14_address1 = zext_ln334_fu_1121_p1;

assign x_15_address0 = zext_ln334_1_fu_1146_p1;

assign x_15_address1 = zext_ln334_fu_1121_p1;

assign x_1_address0 = zext_ln334_1_fu_1146_p1;

assign x_1_address1 = zext_ln334_fu_1121_p1;

assign x_2_address0 = zext_ln334_1_fu_1146_p1;

assign x_2_address1 = zext_ln334_fu_1121_p1;

assign x_3_address0 = zext_ln334_1_fu_1146_p1;

assign x_3_address1 = zext_ln334_fu_1121_p1;

assign x_4_address0 = zext_ln334_1_fu_1146_p1;

assign x_4_address1 = zext_ln334_fu_1121_p1;

assign x_5_address0 = zext_ln334_1_fu_1146_p1;

assign x_5_address1 = zext_ln334_fu_1121_p1;

assign x_6_address0 = zext_ln334_1_fu_1146_p1;

assign x_6_address1 = zext_ln334_fu_1121_p1;

assign x_7_address0 = zext_ln334_1_fu_1146_p1;

assign x_7_address1 = zext_ln334_fu_1121_p1;

assign x_8_address0 = zext_ln334_1_fu_1146_p1;

assign x_8_address1 = zext_ln334_fu_1121_p1;

assign x_9_address0 = zext_ln334_1_fu_1146_p1;

assign x_9_address1 = zext_ln334_fu_1121_p1;

assign zext_ln334_1_fu_1146_p1 = or_ln334_fu_1140_p2;

assign zext_ln334_fu_1121_p1 = lshr_ln_fu_1111_p4;

always @ (posedge ap_clk) begin
    zext_ln334_reg_1860[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
end

endmodule //activation_accelerator_float_layer_norm2_Pipeline_sum_blocks
